### ISSUE TITLE
-enc-mode 4 is slower than -enc-mode 3

### ISSUE THREAD

**Issue by EwoutH** [OpenVisualCloud/SVT-AV1#100]
`-enc-mode 4` is slower than `-enc-mode 3` (see https://github.com/OpenVisualCloud/SVT-AV1/issues/98#issuecomment-466334218).

| Setting     | Time (ms) | Speed (fps) | Bitrate (kb/s) |
|-------------|----------:|------------:|---------------:|
| -enc-mode 4 |     64663 |       1,856 |         346,95 |
| -enc-mode 3 |     45612 |       2,631 |         345,55 |
| -enc-mode 2 |    178345 |       0,673 |         314,02 |

- **Build:** 425ba777 (2019-02-22)
- **Video:** Morocco (1080p 8-bit 4:2:0)
- **Settings:** `-n 120`
- **System:** i5-4590 (4c/4t, AVX2), 16GB DDR3, Windows 10 64-bit

[Full details](https://docs.google.com/spreadsheets/d/1p3PJQMkyhIrXEL6MBBQiwTnWmGyHY_zuw7_XAD0def4/edit#gid=711455734).

**Comment by hassount** [comment]
@EwoutH 
Found the issue, too many pushes have overlapped in a missing setting, we'll submit a fix very soon

**Comment by hassount** [comment]
@EwoutH 
Does #136  close this ?

**Comment by EwoutH** [comment]
Yes
