### ISSUE TITLE
(very) fast first pass in 2-pass mode

### ISSUE THREAD

**Issue by grill05** [OpenVisualCloud/SVT-AV1#1000]
SVT-AV1 curently supports 2-pass mode with constant-qp, and a 2-pass vbr mode in planned for later. Right now, we can choose a higher enc-mode for the first pass and a lower one for the second-pass (specified with `enc-mode-2p` in the 1-pass command )

While this approach of using a higher speed preset speeds up the first-pass to some extent, it is still sub-optimal. That is because its still doing an actual encode in the first-pass, when all we need is to just gather the stats.

For example, currently libaom does a dummy encode in the first-pass to generate the stats file. This approach allows libaom's first pass to be 10-20 times faster than the second pass

It would be very useful if such an approach (dummy encode in first pass with stats generation) could also be used in SVT-AV1. It would significantly reduce the speed overhead for 2-pass mode (vs 1-pass).

If this approach cannot be used for SVT-AV1 for design reasons, are there any other parameters one could toggle(in the first-pass command line) to reduce the amount of time spent doing the 1st-pass, without significantly reducing the accuracy of the stats generated.

**Comment by hassount** [comment]
Why don't you use -enc-mode 8 which is > 100x faster than -enc-mode 0?
it's not a svt-design reason, it's focus on 2-pass, once it's time, this will ultimately be done.

**Comment by grill05** [comment]
> Why don't you use -enc-mode 8 which is > 100x faster than -enc-mode 0?
I think enc-mode 0 is not viable for people running SVT-AV1 on home machines :) . I think enc-mode 4 (or maybe 3) is more viable for bulk-encodes. 

As mentioned, using enc-mode 8 in first pass will speed things up. But it might still be a sub-optimal solution, since the actual encode (even in M8) is not really needed for the first pass.

> it's not a svt-design reason, it's focus on 2-pass, once it's time, this will ultimately be done.

thats good to hear

**Comment by EwoutH** [comment]
Agreed, especially with #775 this will be very useful!

How aomenc for example runs in two pass by default is awesome.

**Comment by hassount** [comment]
This is now done, please reopen if it's still not the case. the current pass 1 should now be quite fast. the combined 2-pass is merged too.
