### ISSUE TITLE
Seg fault for 10-bit 1080p sequence on mac OS

### ISSUE THREAD

**Issue by mafonsoN** [OpenVisualCloud/SVT-AV1#1007]
Master running on mac OS is crashing for 10-bit content. It seems to be a problem for high resolutions only. If alt-refs are disabled (-enable-altrefs 0), no crash is detected. 

Sample command-line: 
`/Bin/Release/SvtAv1EncApp -i akiyo_1080p_10bit.y4m -o akiyo_1080p_10bit_qp43_encmode8.yuv -q 43 -n 20 -b akiyo_1080p_10bit_qp43_encmode8.ivf -intra-period 100 -bit-depth 10 -enc-mode 8`

akiyo_1080p_10bit.y4m was produced by scaling and converting the original cif source to 1080p and 10-bit, using the following ffmpeg command:
`ffmpeg -i akiyo_cif.y4m -s:v 1920x1080 -pix_fmt yuv420p10le -strict -1 akiyo_1080p_10bit.y4m`

Crashes happen inside the `av1_inter_prediction_hbd()` call.

After using git bisect, it was found that the first bad commit was:
`c72560a` [Mon 16 Dec] port presets from ms-dec1 branch and optimize based on testing data

This issue needs further debugging.

**Comment by hassount** [comment]
@OmranAbdelkafi can we try to reproduce this ?

**Comment by hassount** [comment]
#901
@PhoenixWorthVCD @hguermaz FYI until we can repro

**Comment by mafonsoN** [comment]
I've done a lot of tests and PR #895 seems to be solving this issue. However, this PR was reverted a few days ago, due to a crash with this command line: 

`-enc-mode 1 -w 1920 -h 1080 -bit-depth 8 -q 43 -fps-num 60000 -fps-denom 1000 -n 6 -intra-period 63 -lad 0 -i DOTA2_60f_420.yuv`

This should be debugged with high priority. @hassount @magwyz 

This is blocking @andrey-norkin 's enc-dec-common separation.
