### ISSUE TITLE
Nightly Quality Tests

### ISSUE THREAD

**Issue by hassount** [OpenVisualCloud/SVT-AV1#1012]
Add 1-pass cqp to the nightly test for obj-1-fast

**svt 1-pass cqp command line:**
(time ./SvtAv1EncApp -enc-mode 0 -q 20  -n  60  -intra-period  63 -lad 0 -lp 1  -i  touchdown_pass_1080p_60f.y4m  -b  M0_touchdown_pass_1080p_60f_Q20.bin) > M0_touchdown_pass_1080p_60f_Q20.txt 2>&1

**libaom 1-pass cqp cli:**
./aomenc --codec=av1 --tune=psnr --verbose --passes=1 --threads=1 --i420 --profile=0 --frame-parallel=0 --tile-columns=0 --test-decode=fatal --kf-min-dist=64  --kf-max-dist=64  --end-usage=q  --lag-in-frames=25  --auto-alt-ref=1 --use-fixed-qp-offsets=1 --cq-level=20  --aq-mode=0  --bit-depth=8  --input-bit-depth=8  --fps=30000/1001  --width=1920  --height=1080  --deltaq-mode=0  -o M0_touchdown_pass_1080p_60f_Q20.bin --cpu-used=0   touchdown_pass_1080p_60f.yuv

**Comment by grill05** [comment]
The libaom command-line seems to be targeting the highest possible quality/slowest speed  . So it might be worth considering if `tune=vmaf` should be used in place of `tune=psnr` . Libaom's [new vmaf tune](https://aomedia.googlesource.com/aom/+/615dc24579d531cb3a2c9627ab25a3026f9e2b47) mode gives very significant quality improvements (for a slower encoding speed)

**Comment by EwoutH** [comment]
@hassount Do you want those in the CI or in https://videocodectracker.dev/ ?

**Comment by hassount** [comment]
> The libaom command-line seems to be targeting the highest possible quality/slowest speed for 1-pass cqp.
> So it might be worth considering if `tune=vmaf` should be used in place of `tune=psnr` . Libaom's [new vmaf tune](https://aomedia.googlesource.com/aom/+/615dc24579d531cb3a2c9627ab25a3026f9e2b47) mode gives very significant quality improvements (for a slower encoding speed)

We're following the Common Test Conditions for AV1 which has ``` tune=psnr```

**Comment by hassount** [comment]
> @hassount Do you want those in the CI or in https://videocodectracker.dev/ ?

Just on the video tracker, we just need a tracking for the code base selection

**Comment by hassount** [comment]
will do this otherwise later.
