### ISSUE TITLE
Memory Leaks reported with Windows debug and y4m encoding

### ISSUE THREAD

**Issue by intelmark** [OpenVisualCloud/SVT-AV1#1013]
Using master branch and encoding a 1080p y4m file using VS 2017 on Windows - debug build

-i c:/testfiles/BQTerrace_1920x1080_60p_i420_8bit.y4m -n 50

Getting numerous "aligned memory leaked" messages after encoding

SVT-AV1 Encoder
SVT [version]: SVT-AV1 Encoder Lib v0.7.0
SVT [build] : Visual Studio 2017 64 bit
LIB Build date: Feb 5 2020 14:42:22
Number of logical cores available: 8
Number of PPCS 72
SVT [config]: Main Profile Tier (auto) Level (auto)
SVT [config]: EncoderMode : 8
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight : 1920 / 1080
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType : 30 / 1 / 32 / 1
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure : 4 / 0 / 2
SVT [config]: BRC Mode / QP / LookaheadDistance / SceneChange : CQP / 50 / 33 / 0
SVT Memory Usage:
total allocated memory: 5.60 GB
malloced memory: 4.36 GB
callocated memory: 41.09 MB
allocated aligned memory: 1.20 GB
mutex count: 517
semaphore count: 264
thread count: 55
hash table fulless: 0.095391, hash bucket is healthy
top 10 malloced memory locations:
(1.42 GB): C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureControlSet.c:1174
(1.21 GB): C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureControlSet.c:415
(289.86 MB): C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbCodingUnit.c:60
(239.06 MB): C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbCodingUnit.c:61
(217.44 MB): C:\repos\SVT-AV1\Source\Lib\Encoder\Codec\EbEncHandle.c:3355
(143.05 MB): C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbBitstreamUnit.c:40
(119.06 MB): C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureControlSet.c:98
(95.52 MB): C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbModeDecisionProcess.c:103
(77.44 MB): C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureControlSet.c:418
(54.69 MB): C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbMotionEstimationContext.c:117
Encoding 50
SUMMARY --------------------------------- Channel 1 --------------------------------
Total Frames Frame Rate Byte Count Bitrate
50 30.00 fps 590923 2836.43 kbps

Channel 1
Average Speed: 0.693 fps
Total Encoding Time: 72195 ms
Total Execution Time: 80230 ms
Average Latency: 63696 ms
Max Latency: 72050 ms
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L100
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L92
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L92
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L100
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L92
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L100
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L92
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L100
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L92
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L100
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L100
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L92
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L92
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L100
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L92
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L92
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L100
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L100
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L92
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L100
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L92
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPict

**Comment by tianjunwork** [comment]
@intelmark I didn't reproduce with v0.8.1.
```
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.8.1
SVT [build]  :  Visual Studio 2017 64 bit
LIB Build date: Feb  7 2020 15:02:57
-------------------------------------------
Number of logical cores available: 4
Number of PPCS 72
[asm level on system : up to avx2]
[asm level selected : up to avx2]
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 8
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1920 / 1080
SVT [config]: FrameRate / Gop Size                                              : 30 / 32
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 50 / 33 / 0
-------------------------------------------
SvtMalloc[info]: SVT Memory Usage:
SvtMalloc[info]:     total allocated memory:       3.27 GB
SvtMalloc[info]:         malloced memory:          1.95 GB
SvtMalloc[info]:         callocated memory:        176.03 MB
SvtMalloc[info]:         allocated aligned memory: 1.14 GB
SvtMalloc[info]:     mutex count: 477
SvtMalloc[info]:     semaphore count: 186
SvtMalloc[info]:     thread count: 32
SvtMalloc[info]:     hash table fulless: 0.101435, hash bucket is healthy
SvtMalloc[info]: top 10 malloced memory locations:
SvtMalloc[info]: (828.30 MB): C:\Jun_Dev\SVT_OS\SVT-AV1\Source\Lib\Encoder\Codec\EbPictureControlSet.c:533
SvtMalloc[info]: (225.12 MB): C:\Jun_Dev\SVT_OS\SVT-AV1\Source\Lib\Encoder\Codec\EbCodingUnit.c:51
SvtMalloc[info]: (155.39 MB): C:\Jun_Dev\SVT_OS\SVT-AV1\Source\Lib\Encoder\Codec\EbCodingUnit.c:52
SvtMalloc[info]: (119.06 MB): C:\Jun_Dev\SVT_OS\SVT-AV1\Source\Lib\Encoder\Codec\EbPictureControlSet.c:101
SvtMalloc[info]: (95.37 MB): C:\Jun_Dev\SVT_OS\SVT-AV1\Source\Lib\Common\Codec\EbBitstreamUnit.c:39
SvtMalloc[info]: (69.08 MB): C:\Jun_Dev\SVT_OS\SVT-AV1\Source\Lib\Encoder\Codec\EbModeDecisionProcess.c:199
SvtMalloc[info]: (51.80 MB): C:\Jun_Dev\SVT_OS\SVT-AV1\Source\Lib\Encoder\Codec\EbPictureControlSet.c:1747
SvtMalloc[info]: (51.63 MB): C:\Jun_Dev\SVT_OS\SVT-AV1\Source\Lib\Encoder\Codec\EbPictureControlSet.c:545
SvtMalloc[info]: (47.76 MB): C:\Jun_Dev\SVT_OS\SVT-AV1\Source\Lib\Encoder\Codec\EbModeDecisionProcess.c:102
SvtMalloc[info]: (47.63 MB): C:\Jun_Dev\SVT_OS\SVT-AV1\Source\Lib\Encoder\Codec\EbPictureControlSet.c:102
Encoding        20
SUMMARY --------------------------------- Channel 1  --------------------------------
Total Frames            Frame Rate              Byte Count              Bitrate
          20            30.00 fps                  1792909              21514.91 kbps


Channel 1
Average Speed:          0.297 fps
Total Encoding Time:    67238 ms
Total Execution Time:   71096 ms
Average Latency:        60608 ms
Max Latency:            67187 ms
SvtMalloc[info]: you have no memory leak
Encoder finished
```

**Comment by intelmark** [comment]
It seemed to have gone away for me as well.  Hassene suggested creating the issue just to keep record of it.  It should be OK to close

-mark
