### ISSUE TITLE
-fps integer vs float

### ISSUE THREAD

**Issue by dbkynd** [OpenVisualCloud/SVT-AV1#1021]
I'm just starting to get into AV1 so pardon my ignorance.
But with my NTSC videos, the fps reports as 20000/1001 rate which is 23.976
When I use that value to encode a file, when completed it reports as 23FPS.

And I'm not 100% but there seems to be some audio desync. Presumably from the framerate difference.

Does SVT-AV1 only support integer framerates or does it even matter?

Should I just set 23.976 to 24?

**Comment by hassount** [comment]
fps takes only an int, you might want to use -fps-num and -fps-denom

**Comment by dbkynd** [comment]
Oh, I must have overlooked those. Thanks! That works wonderfully.
