### ISSUE TITLE
Crash caused by config file

### ISSUE THREAD

**Issue by EricLamVCD** [OpenVisualCloud/SVT-AV1#1048]
When running the encoder with the config file, the encoder will crash. If you have an empty config file the crash would not happen. 

The issue was narrowed down and found that if the ErrorFile parameter is enabled within the config file, the Encoder will crash. The crash does not happen if ErrorFile is commented out. 

The issue starts happening at this commit 15f9242720219f2594fc055665f0862aad98fc94 on the master branch. 

In commit 89646314f0d040dda8928649a33a9c6c4e52e344, ErrorFile is commented out as a temporary fix.

**Comment by hassount** [comment]
@xuguangxin Would you be able to take a look at this ?

**Comment by xuguangxin** [comment]
sure. @EricLamVCD could you provide the comandline and test platform?

thanks

**Comment by xuguangxin** [comment]
@EricLamVCD any feedback for this?
thanks

**Comment by EricLamVCD** [comment]
@xuguangxin  It was on Windows. Here is an example command line that I ran: 

> ./SvtAv1EncApp.exe -i E:\\$clip_path\\$clip.yuv -end-mode 8 -w $width -h $height -fps-num $fps_num -fps-denom $fps-denom -c Sample.cfg

**Comment by luigi311** [comment]
@EricLamVCD looks like you used -end-mode 8 instead of -enc-mode 8

**Comment by EricLamVCD** [comment]
@luigi311  Sorry that was a typo. I meant to write :

> ./SvtAv1EncApp.exe -i E:\$clip_path\$clip.yuv -enc-mode 8 -w $width -h $height -fps-num $fps_num -fps-denom $fps-denom -c Sample.cfg

**Comment by luigi311** [comment]
Can you try reading in the sample.cfg prior to all your commands
SvtAv1EncApp.exe -c Sample.cfg -i CrowdRun\_1920x1080.yuv -w 1920 -h 1080 -n 100 -q 30 -intra-period 31 -b CrowdRun\_1920x1080\_qp30.bin

**Comment by EricLamVCD** [comment]
The encoder still crashes if I read the config prior to all the other commands.

**Comment by xuguangxin** [comment]
@EricLamVCD after https://github.com/OpenVisualCloud/SVT-AV1/pull/1056 applied, 
we still need following patches to to make Sample.cfg usable.
could you help check it?

thanks

```

diff --git a/Config/Sample.cfg b/Config/Sample.cfg
index d3b837ad..c560c760 100644
--- a/Config/Sample.cfg
+++ b/Config/Sample.cfg
@@ -17,7 +17,7 @@ SourceHeight                    : 240                       # Frame height

 FrameToBeEncoded                : 20                        # Stop encoding after n input frames
 BufferedInput                   : -1                        # Buffer n input frames
-EncoderColorFormat              : EB_YUV420                 # Set encoder color format(EB_YUV400, EB_YUV420, EB_YUV422, EB_YUV444)
+EncoderColorFormat              : 1                 # Set encoder color format(EB_YUV400, EB_YUV420, EB_YUV422, EB_YUV444)
 Profile                         : 0                         # Bitstream profile number to use(0: main profile[default], 1: high profile, 2: professional profile)

 FrameRate                       : 30                        # Stream frame rate (rate/scale)
@@ -62,7 +62,7 @@ LoopFilterDisable               : 0                         # Disable loop filte
 RestorationFilter               : -1                        # Enable the loop restoration filter(0: OFF ,1: ON ,-1:DEFAULT)
 Mfmv                            : -1                        # Enable motion field motion vector( 0 = OFF, 1 = ON, -1 = DEFAULT)
 RedundantBlock                  : -1                        # use the same md results(mode, residual , costà)as the previously processed identical block(0 = OFF, 1 = ON, -1 = DEFAULT)
-Trellis                         : 3                         # Disable trellis optimization of quantized coefficients (0: OFF 1: ON  2: ON for rd search 3: ON for estimate yrd serch (default))
+Trellis                         : -1                         # Disable trellis optimization of quantized coefficients (0: OFF 1: ON  2: ON for rd search 3: ON for estimate yrd serch (default))
 SpatialSSEfl                    : -1                        # Enable spatial sse full loop(0 = OFF, 1 = ON, -1 = DEFAULT)
 Subpel                          : -1                        # Enable subpel(0 = OFF, 1 = ON, -1 = DEFAULT)
 OverBoundryBlock                : -1                        # Enable over boundary block mode (0 = OFF, 1 = ON, -1 = DEFAULT)


```

**Comment by xuguangxin** [comment]
@EricLamVCD could you help fix the configuration file problem for EncoderColorFormat  and Trellis?

thanks
