### ISSUE TITLE
ffmpeg plugin output bitstream will generate duplicate yuv frames when decoded by libaom

### ISSUE THREAD

**Issue by zpdongtencent** [OpenVisualCloud/SVT-AV1#1077]
**bitstream generate:**
`ffmpeg -vsync 0 -r 60 -s 1280x720 -i Johnny_1280x720_60.yuv  -c:v libsvt_av1  -rc 0 -preset 8 -vframes 60 -y Johnny_1280x720_60.ivf`

**decode with ffmpeg(libaom)**
`ffmpeg -i Johnny_1280x720_60.ivf output.yuv`

you will found that some yuv frames are repeated, which is different yuv sequence as the original one.
but if you add "-vsync 0" to ffmpeg decoding command, the yuv sequence will become normal, but only half frames can be decoded normally.
`ffmpeg -vsync 0 -i Johnny_1280x720_60.ivf output.yuv`

and please note that the bitstream can be decoded normally by dav1d.

this issue is related with the packaging method of ivf, in svt test app, obus are packaged according to temporal delimiter obu, but in ffmpeg plugin, packets are directly contained as ivf, which cause the abnormal decoding behavior.

**Comment by silverbacknet** [comment]
Probably the same as #129, which was fixed in a just-merged patch #1074.

**Comment by zpdongtencent** [comment]
> Probably the same as #129, which was fixed in a just-merged patch #1074.
thanks, confirm fixed.
