### ISSUE TITLE
CI checks against master even if PR is onto a different branch

### ISSUE THREAD

**Issue by adaria** [OpenVisualCloud/SVT-AV1#1098]
For example, https://github.com/OpenVisualCloud/SVT-AV1/pull/1097 is a pull request onto the cs2 branch and it is checked against master.

**Comment by ultrawide** [comment]
@luigi311 
I was concerned about the behavior we wanted, but this is a good example when comparing against the official repo's master isn't always applicable. Based on my understanding, the latest changes we discussed on #983 will cause the CI to checkout the official repo's master. Feedback on this is appreciated!

To address the issue, it looks like we can set the `ref` attribute to `github.base_ref`

See [here](https://help.github.com/en/actions/reference/contexts-and-expression-syntax-for-github-actions#github-context)
![Capture](https://user-images.githubusercontent.com/31168160/75508613-956c6a00-5999-11ea-81d8-b508940ee9a0.PNG)

**Comment by luigi311** [comment]
@ultrawide 
Your right I never really considered people would PR into a non master branch, it would be better to do a binary comparison from the fork/branch into the target branch of the PR. The only problem i could think of would be that that will only work on PR and not pushes which shouldnt really be an issue as long as you open a PR with the [WIP] tag or someway to specify that it is not ready so it does not get accidentally merged. What we can do is limit the binary check test to just the PR event and build the base_ref if i am understanding the description correctly.

@hassount Do you see any reason why we would not be able to limit the binary check test to just PR events? That will include all pushes as long as there is a PR open on that branch.

**Comment by ultrawide** [comment]
Yeah, works with me :)

**Comment by ultrawide** [comment]
@luigi311 I'm going to start making a fix for this issue. Let me know if you've started.

**Comment by luigi311** [comment]
@ultrawide You can go ahead and get started on it.
