### ISSUE TITLE
[ffmpeg_plugin] Unable to set encoding -preset (aka -enc-mode) to anything but 1

### ISSUE THREAD

**Issue by jbeich** [OpenVisualCloud/SVT-AV1#110]
SVT-HEVC and SVT-VP9 don't have such limitation.

```
$ ffmpeg -hide_banner -h encoder=libsvt_av1 | fgrep preset
  -preset            <int>        E..V..... Encoding preset [1, 1] (from 1 to 1) (default 1)

$ curl -O https://media.xiph.org/video/derf/y4m/bus_cif.y4m
$ ffmpeg -hide_banner -i bus_cif.y4m -c:v libsvt_av1 -preset 3 -y bus_cif.ivf
Input #0, yuv4mpegpipe, from 'bus_cif.y4m':
  Duration: 00:00:05.00, start: 0.000000, bitrate: 36496 kb/s
    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p(progressive), 352x288, SAR 128:117 DAR 1408:1053, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> av1 (libsvt_av1))
Press [q] to stop, [?] for help
[libsvt_av1 @ 0x807eb5000] Value 3.000000 for parameter 'preset' out of range [1 - 1]
[libsvt_av1 @ 0x807eb5000] Error setting option preset to value 3.
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
```
https://github.com/OpenVisualCloud/SVT-AV1/blob/425ba7775b84c0177f0ffd576faea4ed7314af94/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch#L493-L494

**Comment by jbeich** [comment]
Also, default value between ffmpeg_plugin and `SvtAv1EncApp` don't match. Unlike SVT-HEVC.
https://github.com/OpenVisualCloud/SVT-AV1/blob/425ba7775b84c0177f0ffd576faea4ed7314af94/Source/Lib/Codec/EbEncHandle.c#L2627

**Comment by hassount** [comment]
@jsunintel 
can you please help us address this issue, we would like the default to be set to MAX_ENC_PRESET this can be found in EbApi.h

**Comment by jsunintel** [comment]
> 
> 
> @jsunintel
> can you please help us address this issue, we would like the default to be set to MAX_ENC_PRESET this can be found in EbApi.h

Please help me review https://github.com/OpenVisualCloud/SVT-AV1/pull/149 and thanks a lot.
