### ISSUE TITLE
report unit test cli command

### ISSUE THREAD

**Issue by chkngit** [OpenVisualCloud/SVT-AV1#1103]
To help debug failed unit tests, it would be good to have the entire encoder cli command reported along with each test. People can take the command and run it in a standalone environment

**Comment by hassount** [comment]
@Cidana-Developers 
is this something easy to do ?

**Comment by ePirat** [comment]
Which tests specifically do you mean?

**Comment by ePirat** [comment]
For the SvtAv1E2ETests you should be able to just run the binary with a filter for the name of the failing test

**Comment by hassount** [comment]
> For the SvtAv1E2ETests you should be able to just run the binary with a filter for the name of the failing test

yes, but it does not allow us to debug further, we would like to be able to reproduce the problem using an the encoder binary / command line.

**Comment by ePirat** [comment]
Hm maybe I misunderstand something but why can't you just attach the debugger when running the test, to debug it?

**Comment by hassount** [comment]
because it's yet another layer of SW on top. if the Test project is calling the encoder then it's best / much easier to debug the encoder on its own when we get the command line being called
