### ISSUE TITLE
encoding error causing by extra large encode size under small qp

### ISSUE THREAD

**Issue by zpdongtencent** [OpenVisualCloud/SVT-AV1#1136]
encoding error for certain yuv using small qp, this issue can be reproduced 100% with certain yuv file.
my command line and error log is like following.
![image](https://user-images.githubusercontent.com/59633475/76589805-37598e00-6526-11ea-890f-9a654c1eff2a.png)

**Comment by zpdongtencent** [comment]
it can be reproduced by all preset modes.

**Comment by hassount** [comment]
seems like we're going beyond PCM

**Comment by hassount** [comment]
@OmranAbdelkafi can you please help reproduce this?
