### ISSUE TITLE
enc-mode 0 regression

### ISSUE THREAD

**Issue by EwoutH** [OpenVisualCloud/SVT-AV1#1142]
I noticed quite a large coding efficiency regression between a56b273 and f9fe700. Is this expected?

[See AWCY](https://beta.arewecompressedyet.com/?job=SVT-AV1-enc-mode-0%402020-02-28T19%3A52%3A34.452Z&job=SVT-AV1-enc-mode-0%402020-03-14) for a detailed comparison.

<img width="480" alt="Screenshot_7" src="https://user-images.githubusercontent.com/15776622/76710891-5e24e980-670b-11ea-81ce-bb96e167ea58.png">

**Comment by hassount** [comment]
@EwoutH 
thank you for reporting the issue, this loss is coming from a QP scaling change that does not work with the default 1-pass mode currently as it is tuned for the constant QP offsets mode which will be the default mode with #1133 with -lad 0 until the CRF mode is fixed for 1-pass (it will work with 2-pass only for now).

**Comment by hassount** [comment]
if you run with --enable-tpl-la 1 --scm 2 this issue will be resolved, please reopen if you believe otherwise
