### ISSUE TITLE
Random bitstream corruption 

### ISSUE THREAD

**Issue by OmranAbdelkafi** [OpenVisualCloud/SVT-AV1#1158]
## Preset affected
 all presets from M0 to M8 
## Occurrence
 Very random
##  Sequence used
3 runs over a set of 150 sequences were performed and each time the issue would happen randomly in a different number of clips 
## Command line Sample
 SvtAv1EncApp -enc-mode 8 -q 32  -n 65  -intra-period 72 -lad 0 -lp 1  -i DaylightRoad2_1280x720_60fps_8bit_65f.y4m  -b Release_M8_DaylightRoad2_1280x720_60fps_8bit_65f_Q32.bin 
## Debugging 
* Branch used for debugging : https://github.com/OpenVisualCloud/SVT-AV1/tree/r2r_March16
* Ported all bug fixes PRs
* Tried finding the set of features/signals causing the issue : Disabled the most suspect ones (altref,gm,overboundary,filters , compounds ) : None solved the issue.
* Tried to use only the basic skeleton of the encoder and yet the bitstream corruption would still appear.
* Last test was to use intra frames only (-intra-period 0) , 8x8 partition only and no coeff : The problem still exist with such test.
 P.S : the reckon for the corrupted bitsream is just fine.

**Comment by silverbacknet** [comment]
Can you also paste in the output of a failed run? Most importantly, the asm level lines. Does a debug build have the same behavior or output anything else? Does --asm 0 change it? (Unfortunately that doesn't entirely disable assembly, just selects simpler SSE.) Unless you stripped out asm in your testing already. Or --lp 1 to disable multithreading?

**Comment by ttrigui** [comment]
> Can you also paste in the output of a failed run? Most importantly, the asm level lines. Does a debug build have the same behavior or output anything else? Does --asm 0 change it? (Unfortunately that doesn't entirely disable assembly, just selects simpler SSE.) Unless you stripped out asm in your testing already. Or --lp 1 to disable multithreading?

Can you please share the command you used to test -asm 0?
