### ISSUE TITLE
FPS output incorrect when using -fps-num and -fps-denom 

### ISSUE THREAD

**Issue by cdgriffith** [OpenVisualCloud/SVT-AV1#116]
I used a video with 60fps and it's fps as reported by ffprobe to encode it into AV1.  However the output video resulted in a 30fps video that was 2x slow. 

```
"ffmpeg" -i "DSC_0260.MOV" -vn -acodec libvorbis -map 0:1 "audio.ogg"
"ffmpeg" -loglevel fatal -i "DSC_0260.MOV" -c:v rawvideo -pix_fmt yuv420p "0000.yuv"
"SvtAv1EncApp.exe" -intra-period 55 -enc-mode 3 -bit-depth 8 -w 1920 -h 1080 -fps-num 60000 -fps-denom 1001 -q 20.0 -i "0000.yuv" -b "0.ivf"
"ffmpeg" -i "0.ivf" -i "audio.ogg" -c copy -map 0:0 -map 1:0 "ShouldBe60FPSButIsNot.mkv"
```

However if I just specified `-fps 60` it worked fine. 

[Video files via filedropper](http://www.filedropper.com/videos_15) (If another method is preferred please let me know!) 

~Edit: Just noticed it was with build 167 which is in PR, retrying with latest master 174~

Build 174 bug present https://github.com/OpenVisualCloud/SVT-AV1/commit/df11eb05714700c84c77bc5958371719f9748821

Edit: I am hoping it is part of this issue, but the video output is also slightly jumpy even when using `-fps` and matching the input `yuv` to a set fps. (It's not just decoders having issue, I convert the result back to x265 to confirm. Will open separate bug if this doesn't fix it.)

Thank you guys for all your hard work!

**Comment by hassount** [comment]
@cdgriffith 
Could you please check if commit 1fe6c26 in #136 addresses this ?

**Comment by cdgriffith** [comment]
@hassount Tested with appveyor build `1.0.234`  (commit https://github.com/OpenVisualCloud/SVT-AV1/commit/1fe6c269718245a085193370d2da63067f6e02a2 as listed) and it works! (I will let you determine if to close issue now or when pushed to master, but this resolves my issue. Thanks!)

**Comment by hassount** [comment]
#136
