### ISSUE TITLE
Github CI: Build/Test with sanitizers enabled

### ISSUE THREAD

**Issue by ePirat** [OpenVisualCloud/SVT-AV1#1160]
We should have a CI job that builds with address, memory and possibly thread sanitizer enabled and runs some tests with the results.

I am not sure which tests would be best for this, I guess to begin with it would be enough to just encode a few frames, 8bit and possibly 10bit content (if that uses different codepaths, which is probably does?).

**Comment by lijing0010** [comment]
This is a good idea, and can we always enable the -fsanitize=address -fno-omit-frame-pointer in debug version?

**Comment by chkngit** [comment]
will this be supported for VisualStudio builds as well?

**Comment by tianjunwork** [comment]
Hi @chkngit , it should be: https://devblogs.microsoft.com/cppblog/addresssanitizer-asan-for-windows-with-msvc/. 
@lijing0010 , not sure if it will slow down debug build a lot. Maybe enable it by parameter?

**Comment by ePirat** [comment]
I believe its mostly useful for individual developers, I guess windows does not has very different codepaths compared to linux that would warrant setting up sanitizer CI runs for that too?

**Comment by 1480c1** [comment]
We could add another build type by using `CMAKE_C_FLAGS_<TYPE>` or similar and make it use the debug + sanitizer flags

**Comment by 1480c1** [comment]
@ePirat do you also want to add the sanitizers for windows? It seems that the ones used in msvc are just based on clang, so I'm not sure how useful those would be outside of certain windows specific code

**Comment by ePirat** [comment]
I am unfamiliar with how to enable sanitizers on Windows, so would feel more comfortable with someone familiar with the Platform to do that.
If it's just using the clang static analyzers, I am not sure either if it will be very useful, although having the Windows specific codepaths tested is probably a good thing even though there are not that many.

**Comment by chkngit** [comment]
most of the SVT R&D development is done on Viusal studio, so we would love to have this option supported at the code dev time

**Comment by 1480c1** [comment]
It seems that sanitizer support within visual studio is based on clang-cl being used and using their sanitizer instead, and I'm not sure if that's available in github actions, since I'm not sure how to install visual studio modules without a gui

**Comment by 1480c1** [comment]
@chkngit can you try running
```powershell
cmake -B asan -G"Visual Studio 16 2019" -A x64 -T "ClangCl" -DCMAKE_C_COMPILER_FLAGS="-fsanitize=address" -DCMAKE_CXX_COMPILER_FLAGS="-fsanitize=address"
cmake --build asan --config Release
```

**Comment by 1480c1** [comment]
You might need to add the clang-cl option in the visual studio installer

**Comment by 1480c1** [comment]
@chkngit ping?

**Comment by chkngit** [comment]
@hassount

**Comment by 1480c1** [comment]
I think the original issue has been addressed, although for now, it seems to be erroring out while not marking the job as failing

**Comment by hassount** [comment]
> I think the original issue has been addressed, although for now, it seems to be erroring out while not marking the job as failing

yes #1308 can track the failure
