### ISSUE TITLE
Github CI: Static analyzer build

### ISSUE THREAD

**Issue by ePirat** [OpenVisualCloud/SVT-AV1#1161]
Make a build with a static analyzer and upload the results somewhere. Possible choices would be the clang static analyzer or cppcheck (never used that one before though).

**Comment by hassount** [comment]
@ePirat 
thank you for logging this, can we use the cppcheck tool ?

**Comment by ePirat** [comment]
We can, although it seems clang static analyzer produces a lot more reports, so we might want to use that. But for a first step we can probably use cppcheck and have it run directly in the CI given the low number of reports it produces.

For clang static analyzer a more complex tooling would be needed.

**Comment by ePirat** [comment]
I've done some research and it seems for now we should use cppcheck, I will make a PR that adds this to the CI setup. Eventually we can set up a codechecker instance to do checks with clang static analyzer.

Something else we can do it set up lgtm.com but that would be something one of the repository admins needs to do. (It should be easy enough, I've already done a test run with this repo, but to have it in PRs, it has to be enabled, which I can not do)
