### ISSUE TITLE
hme_mv_center_check: Values written but never read

### ISSUE THREAD

**Issue by ePirat** [OpenVisualCloud/SVT-AV1#1164]
In hme_mv_center_check, one assignments to `search_center_x` is useless it is never read again:

https://github.com/OpenVisualCloud/SVT-AV1/blob/70b717c2336c8d6e69b5cf7df7d35725fc43ecbd/Source/Lib/Encoder/Codec/EbMotionEstimation.c#L9278-L9281

**Comment by ePirat** [comment]
Same for search_center_y a bit below:

https://github.com/OpenVisualCloud/SVT-AV1/blob/70b717c2336c8d6e69b5cf7df7d35725fc43ecbd/Source/Lib/Encoder/Codec/EbMotionEstimation.c#L9287-L9292

**Comment by ePirat** [comment]
Same for the initialization of both with the functions arguments:

https://github.com/OpenVisualCloud/SVT-AV1/blob/70b717c2336c8d6e69b5cf7df7d35725fc43ecbd/Source/Lib/Encoder/Codec/EbMotionEstimation.c#L9244-L9245

Both search_center_x and search_center_y are overwritten before ever read with the assigned values.

**Comment by hassount** [comment]
@chkngit does this make sense to you to be cleaned ?

**Comment by chkngit** [comment]
all of that function is deleted in svt-01

**Comment by 1480c1** [comment]
I believe this has been addressed through the cppcheck prs
