### ISSUE TITLE
quarter_pel_search_sb: useless assignments

### ISSUE THREAD

**Issue by ePirat** [OpenVisualCloud/SVT-AV1#1165]
In quarter_pel_search_sb, buf1 and buf2 are assigned to itself which seem useless?

https://github.com/OpenVisualCloud/SVT-AV1/blob/70b717c2336c8d6e69b5cf7df7d35725fc43ecbd/Source/Lib/Encoder/Codec/EbMotionEstimation.c#L6596-L6611

**Comment by ePirat** [comment]
@hassount Any info on this? I can make a PR to remove this but maybe it's there for a reason (future work in some branch or so) I am not aware of?

**Comment by hassount** [comment]
@hguermaz does removing the above makes sense to you ?

**Comment by 1480c1** [comment]
I believe this has been addressed through the cppcheck prs
