### ISSUE TITLE
Will a CRF mode be added in the new future?

### ISSUE THREAD

**Issue by praneet195** [OpenVisualCloud/SVT-AV1#1167]
Hi,

Great work on the best AV1 encoder out there. I just wanted to know if a CRF mode will be added and if so by when can we expect it. Again, thank you for your work.

**Comment by hassount** [comment]
@praneet195 
Thank you for the feedback, right now we're targeting Q3'20 time frame

**Comment by hassount** [comment]
Already supported, please use -q <crf value> --enable-tpl-la 1
