### ISSUE TITLE
fastfeat: Memory leak on realloc

### ISSUE THREAD

**Issue by ePirat** [OpenVisualCloud/SVT-AV1#1170]
In the third-party fastfeat library there is a lack for realloc validation, so it will dereference a null pointer in case of allocation failure, causing a crash or other UB.
Additionally it would leak the old memory in error case.

https://github.com/OpenVisualCloud/SVT-AV1/blob/70b717c2336c8d6e69b5cf7df7d35725fc43ecbd/third_party/fastfeat/fast_9.c#L5898

**Comment by ePirat** [comment]
@hassount Any idea what to do about this one?

**Comment by hassount** [comment]
@ePirat sorry for the late response on this. can we add an assert to make sure it's captures if we deref a null ptr ? tagging @1480c1 to see if this is covered in the static analysis work

**Comment by 1480c1** [comment]
these realloc checks/lack of checks on realloc are included in cppcheck and I am planning on going through them, one of them is in then lp_group setting as well.

**Comment by ePirat** [comment]
@hassount If this piece of code is used in the library, it probably should be handled properly like the library handles other allocation failures properly already. Although if its not doable in this case and its very unlikely to fail, maybe abort() in this case (to make sure it does not only happen in debug enabled builds)

**Comment by 1480c1** [comment]
Closed by cppcheck
