### ISSUE TITLE
Crash in 4k Resolution

### ISSUE THREAD

**Issue by EricLamVCD** [OpenVisualCloud/SVT-AV1#1174]
## Preset
 8
## Occurrence
 Reproducible
##  Sequence used
Netflix_ToddlerFountain_4096x2160_60fps_10bit_420_60f
Campfire_3840x2160_30fps_10bit_bt709_420_videoRange_60f
ParkRunning3_3840x2160_50fps_10bit_420_60f
## Command line Sample
SvtAv1EncApp -enc-mode 8 -w 3840 -h 2160 -bit-depth 10 -fps-num 30000 -fps-denom 1000 -q 20  -n  60.0  -intra-period  63 -lad 0 -lp 1  -i  Campfire_3840x2160_30fps_10bit_bt709_420_videoRange_60f.yuv  -b  Campfire_3840x2160_30fps_10bit_bt709_420_videoRange_60f_Q20.bin
## Description
* Used master @ b5cdb0b revision-hash 
* Error Message: `Svt[error]: encode size(5013174) is too largeSvt[error]: bug, no frame in undisplayed queue`
* ran 5 QPs [20,32,43,55,63] and the problem only showed up in QP20
* Error is output in the first few frames 
* Encoding stops around frames 45-48

**Comment by hassount** [comment]
can we validate that #1177 addressed this?
