### ISSUE TITLE
Forcing an IDR

### ISSUE THREAD

**Issue by palexander-14** [OpenVisualCloud/SVT-AV1#1179]
Hi, is there a way to make a certain input frame to become an IDR-frame regardless of scene change detection and GOP configuration? This is helpful when it needs to start new video segment for HLS or DASH.

**Comment by hassount** [comment]
this is supported by the library but not in the commandline application. When the application sends a picture to the library, it can mandate that the picture is an IDR: 

https://github.com/OpenVisualCloud/SVT-AV1/blob/882e97f69ab3dadebb03bd7d4f5f49196a690b6a/Source/App/EncApp/EbAppProcessCmd.c#L948

setting it to EB_AV1_KEY_PICTURE will force an IDR.

**Comment by palexander-14** [comment]
Great, thanks @hassount !
It was helpful. But the following question has been raised.
I noticed that this "forced IDR" doesn't affect appearance of next IDR or CRA frame.
For example, for intra_period_length = 50 I will have 0th and 50th frames are coded as IDR. But if I force 48th frame to be an IDR 50th frame is still coded as IDR.
Is there something to avoid such behavior?

Thanks.

**Comment by hassount** [comment]
I see, this capability is not currently supported.

**Comment by palexander-14** [comment]
Ok. Thank you very much.
