### ISSUE TITLE
Error: LAD=0 is not supported for --key-int 0

### ISSUE THREAD

**Issue by praneet195** [OpenVisualCloud/SVT-AV1#1181]
Hi,
I'm trying to encode a video sequence in all-intra mode. This is the command i've used.

 ~/ffmpeg_sources/ffmpeg/ffmpeg -y -r 30 -i V000.seq -an -f rawvideo -pix_fmt yuv420p - | ~/SVT-AV1/Bin/Release/SvtAv1EncApp -i stdin -rc 2 --fps 30 --tbr 5000  -intra-period 0 -w 640 -h 480 -b V000.ivf

However, I get the following error while encoding:
Error: LAD=0 is not supported

Can you please tell me what's wrong

**Comment by hassount** [comment]
-rc non zero options require a look ahead setting, also rate control is currently not supported with the intra only use case.

**Comment by praneet195** [comment]
Thank you for your reply.
 I used --rc 1, --lad 1 and --intra-period 0 and this worked. I've managed to get a fixed bit rate setting and on analyzing I also see that all frames are key-frames. Is this setting fine or am I doing something wrong?

**Comment by hassount** [comment]
the question is more, what do you intent to do ? are you looking for an all intra case ? if so, then that is the closest possible cmd yes.

**Comment by praneet195** [comment]
I wasn't clear. My fault. Yes I was looking for an all-intra case with a fixed bit-rate condition. 
Thank you for the reply

**Comment by hassount** [comment]
@praneet195 ok then for all Intra coding what you have should be ok, though as I said, the encoder has not been optimized for this use case
