### ISSUE TITLE
Incorrect mapping between token INTRA_ANGLE_DELTA_NEW_TOKEN and set_cdef_mode

### ISSUE THREAD

**Issue by ultrawide** [OpenVisualCloud/SVT-AV1#1184]
Incorrect reference to function for token INTRA_ANGLE_DELTA_NEW_TOKEN in EbAppConfig.c

https://github.com/OpenVisualCloud/SVT-AV1/blob/9fd85743c69b6762bb9dc570fbc9f93d6b7cf247/Source/App/EncApp/EbAppConfig.c#L1182-L1185

**Comment by hassount** [comment]
#1186 is merged
