### ISSUE TITLE
Errors when attempting to use FFmpeg patch.

### ISSUE THREAD

**Issue by nathanielcwm** [OpenVisualCloud/SVT-AV1#1185]
```
error: configure: does not exist in index
error: libavcodec/Makefile: does not exist in index
error: libavcodec/allcodecs.c: does not exist in index
```
There are no errors when using the patch from the stable release.

I was attempting to patch it like this:
`git apply --index 0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch`

**Comment by hassount** [comment]
according to the ci everything is working properly:
https://github.com/OpenVisualCloud/SVT-AV1/runs/571141721

are you trying to apply it on the master of ffmpeg maybe ?

**Comment by nathanielcwm** [comment]
Yes

**Comment by hassount** [comment]
then you would need to checkout the 4.2 release for the patch to work as explained in the README file:
https://github.com/OpenVisualCloud/SVT-AV1/blob/master/ffmpeg_plugin/README.md

**Comment by nathanielcwm** [comment]
So only the stable version of FFmpeg is supported?

**Comment by hassount** [comment]
yes

**Comment by 1480c1** [comment]
I think this can be closed too
