### ISSUE TITLE
Ivy-Bridge and Sandy-Bridge AVX1 ASM planned?

### ISSUE THREAD

**Issue by JouMxyzptlk** [OpenVisualCloud/SVT-AV1#1197]
On my ivy-bridge system:
[asm level on system : up to c]
[asm level selected : up to c]
On my Sandy Bridge System (used dual Xeon 192 GB RAM, bought only 'cause of 192 GB RAM):
[asm level on system : up to c]
[asm level selected : up to c]
On my Ryzen 3900x:
[asm level on system : up to avx2]
[asm level selected : up to avx2]

I.e. practically unusable slow on Ivy-Bridge and Sandy-Bridge, except for "does it work?" with ten seconds videos.
As for Ivy-Bridgy: AVX and SSE 4.2 is avail, those Xeons have AVX.
Anything planned for AVX1 and SSE?

**Comment by hassount** [comment]
@JouMxyzptlk 
thank you for the report. 
this is not on the road map at this point as we  are looking into Broadwell CPUs and later. I ll open this up for contributions though.

**Comment by it2350** [comment]
You'd have to change [this line](https://github.com/OpenVisualCloud/SVT-AV1/blob/73793b03cd9d5948b5a317e68a55879eba500044/Source/Lib/Common/Codec/common_dsp_rtcd.c#L143) for the purpose.
There is check_4thgen_intel_core_features() function, i've tried to make something like check_2ndgen_intel_core_features(), but the code is rather complex, so i've totally disabled check for 4th gen and AVX-512 and simply return "flags" with gen2 ASM instructions (these are the same as for gen4, except AVX2).
Cloned the repository, made these changes and Github Actions made the rest job for me, creating the needed binary.
So, no PR now, but usable workaround.

**Comment by hassount** [comment]
@JouMxyzptlk please reopen if still needed
