### ISSUE TITLE
stdin for input only works if the input is a file, not when streaming from FFmpeg

### ISSUE THREAD

**Issue by sandersaares** [OpenVisualCloud/SVT-AV1#1205]
On Windows 10, given this input file: 
[demo.zip](https://github.com/OpenVisualCloud/SVT-AV1/files/4479702/demo.zip)

Using ffmpeg version git-2020-03-15-c467328 and SVT-AV1 [0.8.1] - 2020-01-28

This sequence of commands works fine:

```
ffmpeg -i demo.mp4 -f yuv4mpegpipe demo.y4m
SvtAv1EncApp.exe -i stdin -w 1920 -h 800 -fps 24 < demo.y4m
```

This does not work:

```
ffmpeg -i demo.mp4 -f yuv4mpegpipe - | SvtAv1EncApp.exe -i stdin -w 1920 -h 800 -fps 24
```

In case 1 I write from FFmpeg to file and then pipe that file to SVT-AV1.

In case 2 I pipe directly from FFmpeg to SVT-AV1, without a file in between.

The latter appears to trigger some fault condition where SVT-AV1 thinks the input is bad. Maybe it tries to read input before FFmpeg has produced any? Just speculating.

The output printed in the second case contains the following relevant lines:

```
Error instance 1: Input yuv does not contain enough frames
Error in configuration, could not begin encoding! ...
Run SvtAv1EncApp.exe -help for a list of options
Encoder finished
```

FFmpeg just sees that pipe was closed:

```
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe
```

**Comment by ePirat** [comment]
I recently did this on Linux and it worked fine, so possibly something specific to how Windows handles pipes?

Did you do this in cmd or Powershell?

**Comment by sandersaares** [comment]
This was in regular cmd.exe shell.

**Comment by sandersaares** [comment]
This seems to happen because `read_command_line()` sets `frames_to_be_encoded` in its "verify" logic and does not seem to account for the fact that the input might be a pipe whose length is not known. It calls `compute_frames_to_be_encoded()` which looks at the (partial) input stream, finds that `file_size < frame_size` and therefore concludes there is nothing in the input stream.

It is not clear to me what the fix here is. There seems to be a built-in assuption in the code that it is possible to know in advance how many frames are to be encoded, no?

**Comment by tianjunwork** [comment]
Hi @sandersaares , thanks reporting the issue and making a PR. I can reproduce on Windows(not on Ubuntu).
