### ISSUE TITLE
Run-to-run mismatch with --preset 8 and VBR

### ISSUE THREAD

**Issue by palexander-14** [OpenVisualCloud/SVT-AV1#1206]
The SVT-AV1 encoder (https://github.com/OpenVisualCloud/SVT-AV1/commit/ea6bf44da949f7a98148a5baba431b2765aa622a) produces different output from run to run. The cmd line is:
./SvtAv1EncApp -i input.yuv -w 1280 -h 720 -b output.ivf --preset 8 --rc 1 --tbr 2400

Debug build shows the problem as well.

In CQP mode there is no problem with --preset 8.

**Comment by hassount** [comment]
@palexander-14 
this is expected as we don't force a certain order of feedback in the encoder when rate control is set.
