### ISSUE TITLE
Add git hash to the build version

### ISSUE THREAD

**Issue by hassount** [OpenVisualCloud/SVT-AV1#1208]
Right now any build would have the same version that is defined statically every tag. to fit better with snap as in #38 we would need to add the git hash to the revision number similar to other encoders such as libaom e.g. g66603e7ee

**Comment by hassount** [comment]
@jbkempf @ePirat

**Comment by ePirat** [comment]
Where in the code is the version defined currently? Should be easy to add this.

**Comment by hassount** [comment]
in multiple locations, check #989 those are all locations we need to change to bump a revision

**Comment by 1480c1** [comment]
https://github.com/OpenVisualCloud/SVT-AV1/blob/59f20e440b3a91526bdc6f456cc67e427e42649b/Source/API/EbSvtAv1.h#L16

https://github.com/OpenVisualCloud/SVT-AV1/blob/5fdf5ef4943d6e7736d051d68baa0f08416b5a50/Source/Lib/Decoder/CMakeLists.txt#L7

https://github.com/OpenVisualCloud/SVT-AV1/blob/2f008174b75333ce29b7a5eabe29f500d979fdac/Source/Lib/Encoder/CMakeLists.txt#L7


Printed out:
https://github.com/OpenVisualCloud/SVT-AV1/blob/57365312464d02ff07d4471a3abf83eb2c0c033e/Source/Lib/Decoder/Codec/EbDecHandle.c#L451

https://github.com/OpenVisualCloud/SVT-AV1/blob/17f08a65cb625e0bc56dcce95b67cbafc9f797ea/Source/Lib/Encoder/Globals/EbEncHandle.c#L3648

**Comment by ePirat** [comment]
Will encoder and decoder have the same version?

**Comment by hassount** [comment]
> Will encoder and decoder have the same version?

yes, they usually go in lock step
