### ISSUE TITLE
Issues with framerate written to IVF header

### ISSUE THREAD

**Issue by mafonsoN** [OpenVisualCloud/SVT-AV1#121]
Found several issues with the framerate written in the IVF bitstream header while debugging issue #120 

For instance:

- the framerate denominator in IVF header is hardcoded to 1001 in EbAppProcessCmd.c.
- the frameRate variable in the config structure in EbAppConfig.c is set to a default value of 30 and this is always written to the IVF header unless it is directly specified in the encoding parameters (also reported by issue #116 ).

BTW, given that the there are frameRateNumerator and frameRateDenominator variables in the EbConfig_s struct, why is it necessary to have a separate variable for frameRate? Also, it isn’t really used by the encoder and it is a rational number. Can we possibly remove it? This would fix these issues.

**Comment by kylophone** [comment]
> BTW, given that the there are frameRateNumerator and frameRateDenominator variables in the EbConfig_s struct, why is it necessary to have a separate variable for frameRate? Also, it isn’t really used by the encoder and it is rational number. Can we possibly remove it? This would fix these issues.

frameRate should be expressed as a rational only. Anything else is a bug.

**Comment by hassount** [comment]
Fix committed to #136 1fe6c26

**Comment by hassount** [comment]
@mafonsoN 
can you please confirm that this issue is fixed in the current master?

**Comment by mafonsoN** [comment]
@hassount Yes, I think these are solved but I still don't understand this bit of code:

```c
static void SetFrameRate                        (const char *value, EbConfig_t *cfg) {
    cfg->frameRate = strtoul(value, NULL, 0);
    if (cfg->frameRate > 1000 ){
        cfg->frameRate = cfg->frameRate;
    }
    else{
        cfg->frameRate = cfg->frameRate << 16;
    }
}
```

What if I input -fps 2000?

**Comment by EwoutH** [comment]
It looks like this got fixed, I encoded a .y4m video with the latest master and it's playing back correctly on VLC, mpv and ffplay.
