### ISSUE TITLE
Decoder mismatch for some streams

### ISSUE THREAD

**Issue by joelsole** [OpenVisualCloud/SVT-AV1#1215]
The issue might be related to storing and retrieving an intermediate buffer in the LR stage.

ivf attached. 

[DayStreet_12fr_256x256_60fps_10bits_420_eo0_pr3_qp50.ivf.log](https://github.com/OpenVisualCloud/SVT-AV1/files/4489836/DayStreet_12fr_256x256_60fps_10bits_420_eo0_pr3_qp50.ivf.log)

**Comment by hassount** [comment]
@joelsole is this a decoder issue or an encode decode mismatch on the encoder side ?

**Comment by joelsole** [comment]
Decoder. 
Dav1d and aomdec provide an output matching the reconstruced yuv by the encoder.

**Comment by nijilk** [comment]
@joelsole PR https://github.com/OpenVisualCloud/SVT-AV1/pull/1219 will fix this issue
