### ISSUE TITLE
Appveyor CI failure

### ISSUE THREAD

**Issue by ePirat** [OpenVisualCloud/SVT-AV1#1221]
Currently Appveyor always fails due to:

```
Maximum allowed artifact storage size of 100000 Mb will be exceeded.
```

One of the SVT-AV1 repo admins probably need to clean up some stuff there.

@hassount

**Comment by 1480c1** [comment]
For appveyor, we can't manually clean up the artifacts, only the appveyor admins can extend the limit. They get auto cleaned after 6 monthes

**Comment by tianjunwork** [comment]
SVT-HEVC/VP9 appveyor also shows this error. @1480c1 disabled uploading artifacts temporarily for CI to pass.
@ePirat is that a way to use other CI tools to upload windows build? Or can it only upload for PR that adds a tag?

**Comment by hassount** [comment]
I submitted a ticket to Appveyor a couple of days ago, I just got a note that the limit has been increased, let's try again

**Comment by ePirat** [comment]
I am not sure what exactly the uploads are there for? If the intention is to have those for tagged commits? Thats certainly possible.

Not sure if it makes sense to upload each build/PR?

**Comment by 1480c1** [comment]
> I am not sure what exactly the uploads are there for? If the intention is to have those for tagged commits? Thats certainly possible.
> 
> Not sure if it makes sense to upload each build/PR?

The main intention is to upload binaries for releases, but I do know that some people on windows rely on those binaries when trying out the latest commit since they do not want to nor know how to compile on windows

**Comment by 1480c1** [comment]
It would be preferable to only upload on the main branch and not on pr's, but according to appveyor, any PR against the master branch is counted as the master branch. So we might need to find a way to skip uploading if it's a PR in the script stage rather than using appveyor's artifacts section

**Comment by 1480c1** [comment]
@ePirat does this issue need to still be open now that we've added artifacts to github actions?

**Comment by ePirat** [comment]
Probably not
