### ISSUE TITLE
Huge BDR regression on wikipedia_420.y4m

### ISSUE THREAD

**Issue by EwoutH** [OpenVisualCloud/SVT-AV1#1228]
In a few AWCY runs I notices a huge BDR regression on the _wikipedia_420.y4m_ clip between 7513210 (december 18th) and f9db11cb (today). In some metrics the BDR regression is over 100%, so over double the bits are needed for identical quality.

The test clip can be found on https://people.xiph.org/~tdaede/sets/objective-1-fast/

**Comparisons**

- [EncMode 8](https://beta.arewecompressedyet.com/?job=SVT-AV1-enc-mode-8%402019-12-18&job=SVT-AV1-enc-mode-8%402020-04-18)
- [EncMode 7](https://beta.arewecompressedyet.com/?job=SVT-AV1-enc-mode-7%402019-12-18&job=SVT-AV1-enc-mode-7%402020-04-18)
- [EncMode 6](https://beta.arewecompressedyet.com/?job=SVT-AV1-enc-mode-6%402019-12-18&job=SVT-AV1-enc-mode-6%402020-04-18)
- [EncMode 5](https://beta.arewecompressedyet.com/?job=SVT-AV1-enc-mode-5%402019-12-18&job=SVT-AV1-enc-mode-5%402020-04-18)

**Comment by hassount** [comment]
@EwoutH 
Thnx for the note, this is very likely due to the new command line change for -scm mode as the detection is now disabled by default.
If you add -scm 2 to your cmd, then you should see it back to normal.

**Comment by EwoutH** [comment]
Thanks!

I noticed that the CLI still outputs: `--scm                           Set screen content detection level([0-2], 2: DEFAULT)`

So I submitted #1232 to fix this.
