### ISSUE TITLE
Fails to build on 32-bit x86

### ISSUE THREAD

**Issue by jbeich** [OpenVisualCloud/SVT-AV1#1231]
x86_abi_support.asm only defines `ARCH_X86_64` but EbDefinitions.h adds `__i386__` to  `ARCH_X86`. However, assembly isn't built if `uname -m` returns `i386` or `i686`.

From [error log](https://github.com/OpenVisualCloud/SVT-AV1/files/4498256/svt-av1-0.8.1.169.log):
```
ld: error: Bin/Release/libSvtAv1Enc.so.0.8.1: undefined reference to Log2f_SSE2
ld: error: Bin/Release/libSvtAv1Enc.so.0.8.1: undefined reference to aom_blend_a64_hmask_sse4_1
ld: error: Bin/Release/libSvtAv1Enc.so.0.8.1: undefined reference to aom_blend_a64_mask_avx2
```
From [error log](https://github.com/OpenVisualCloud/SVT-AV1/files/4498268/svt-av1-0.8.1.169.log) after applying fe54f0274277:
```
Source/Lib/Common/ASM_SSE2/aom_subpixel_8t_sse2.asm:204: error: impossible combination of address sizes
Source/Lib/Common/ASM_SSE2/x86_abi_support.asm:237: ... from macro `ALIGN_STACK' defined here
Source/Lib/Common/ASM_SSE2/aom_subpixel_8t_sse2.asm:213: error: impossible combination of address sizes
Source/Lib/Common/ASM_SSE2/aom_subpixel_8t_sse2.asm:21: ... from macro `GET_FILTERS_4' defined here
```

**Comment by 1480c1** [comment]
32-bit is not supported by SVT-AV1 and probably shouldn't due to the amount of ram required for just running the encoder

**Comment by jbeich** [comment]
Memory usage depends on number of CPUs used e.g., `SvtAv1EncApp` with `--lp 5` seems OK. On x86 32-bit CPUs rarely have more than 4 cores (2 is more common).

**Comment by jbeich** [comment]
Note, my "more common" is based on https://data.firefox.com/dashboard/hardware ;)

**Comment by tianjunwork** [comment]
Hi @jbeich , there is no plan on our side to support 32-bit x86. We welcome contribution from community.

**Comment by hassount** [comment]
Closing this as it is out of scope for now
