### ISSUE TITLE
Test command line printout typo

### ISSUE THREAD

**Issue by hassount** [OpenVisualCloud/SVT-AV1#1233]
the unit test is printing -colour-space instead of -color-format

https://github.com/OpenVisualCloud/SVT-AV1/blob/9ce7f5e74c6f3021e87dc00cbbfa51f01a23bd5e/test/e2e_test/E2eTestVectors.h#L156

@Cidana-Developers can we map this along with command line options to the correct cli options ?

**Comment by tianjunwork** [comment]
Ping @Cidana-Developers :)

**Comment by tianjunwork** [comment]
Hi @Cidana-Developers, Could you take a look?

**Comment by Cidana-Developers** [comment]
> Hi @Cidana-Developers, Could you take a look?

This issue was fixed in PR #1243, which was merged by you just the day you pinged me ;-)
Might be busy forgetting close this issue.

**Comment by tianjunwork** [comment]
@Cidana-Developers Sorry:) Thank you. I will close it.
