### ISSUE TITLE
Add --no-progress option to sample apps

### ISSUE THREAD

**Issue by sandersaares** [OpenVisualCloud/SVT-AV1#1237]
At the moment, the sample apps report the current frame number in their output. In scenarios where the output is piped to a log file, this results in a lot of unnecessary text that makes navigation in the log difficult.

For scenarios where the encoding progress information is not needed, a `--no-progress` switch to disable the output of these numbers would be useful. I request such an enhancement be added to the sample apps.

Example of undesirable numbers in log output when piped to file: 

![image](https://user-images.githubusercontent.com/9914262/79826068-6b389680-83a3-11ea-916c-9b2dbd3e1057.png)

**Comment by tianjunwork** [comment]
Hi @sandersaares , pls refer to this PR https://github.com/OpenVisualCloud/SVT-AV1/pull/809. 2>/dev/null redirect stderr to null.

**Comment by sandersaares** [comment]
I want the rest of the output, just not the repetitive part (the 1....2.....3.... counter).

**Comment by tianjunwork** [comment]
Pls refer to #809:
1. SVT_LOG=4 SVT_LOG_FILE=lib.log SVT_APP_LOG_FILE=app.log SvtEncApp -i test.y4m -b test.ivf
2. SVT_LOG=4 SVT_LOG_FILE=lib.log SVT_APP_LOG_FILE=app.log ffmpeg -i test.y4m -c:v libsvt_av1 test.mp4
You will get the rest part in lib.log.

**Comment by sandersaares** [comment]
I am probably missing something in the referenced issue but even if this can be accomplished by some combination of logging configuration, "don't write progress % to stderr" is a basic feature of data processing tools that the sample apps should support without having to learn about logging configuration.

For comparison, FFmpeg has `-nostats` which does exactly this.

**Comment by tianjunwork** [comment]
Sounds fair. Just to confirm you only request the `progress number` to be controlled not the rest encoding results e.g. `SUMMARY and below`

**Comment by sandersaares** [comment]
Exactly, just the counter that keeps incrementing for each frame.

**Comment by 1480c1** [comment]
@sandersaares, just making sure, you are looking for a `--no-progress` option and not a `-q` or `--quiet` option right?

**Comment by sandersaares** [comment]
Right. I am looking for the analog of FFmpeg `-nostats` or x264 and x265 `--no-progress`.

**Comment by 1480c1** [comment]
So I have made a `--no-progress` option that looks like
```none
<svt header stuff here>
Encoding          
SUMMARY --------------------------------- Channel 1  --------------------------------
Total Frames            Frame Rate              Byte Count              Bitrate
         300            29.97 fps                    90484              72.31 kbps
```

however, due to the current limitations of the args handling, we don't have a switch option so it needs to be enabled by adding something afterward, like `--no-progress 1` or `--no-progress aaaaaaa`

**Comment by tianjunwork** [comment]
Thank you @1480c1 , it should be ok for now.
