### ISSUE TITLE
Target Bit Rate 

### ISSUE THREAD

**Issue by praneet195** [OpenVisualCloud/SVT-AV1#1239]
Hi,
The target bit-rate option does not seem to fix the bit-rate to the required value. For example, I set the --tbr to 500 (kbits/s) but my encoded sequence has a bit-rate of 1Mbits/s Similarly, when I set --tbr to 3000 (kbits/s), my encoded sequence has a bit-rate of 2.2Mbits/s.
 I'm guessing this is the intended behavior as target bit-rate does not mean fixed bit-rate.
 However, is there an option to get fixed bit-rate?

**Comment by hassount** [comment]
@praneet195 
can we have the command line ?

**Comment by praneet195** [comment]
This:
~/SVT-AV1/Bin/Release/SvtAv1EncApp -i input.seq --rc 1  --fps 30 --tbr 500 --intra-period 0 -w 640 -h 480 -b out.ivf
I expect a target bit rate of 500kbits/s but I get a target bit rate of about 900 kbits/s
When I use this:
~/SVT-AV1/Bin/Release/SvtAv1EncApp -i input.seq --rc 1  --fps 30 --tbr 3000 --intra-period 0 -w 640 -h 480 -b out.ivf
I expect a target bit rate of 3000kbits/s but I get a target bit rate of about 2000 kbits/s
Am I doing something wrong?

**Comment by hassount** [comment]
not really the cli is fine, the problem here is that the rate control as I mentioned earlier is not optimized for this use case and so the behavior you are seeing is expected. unfortunately, it is currently not on the roadmap to be addressed.

**Comment by praneet195** [comment]
Alright, thank you for the quick update.

**Comment by yermak** [comment]
I have same issue, as tbr parameter is very confusing.
I tried to use 2pass encoding, here is my command line
SvtAv1EncApp -i  %~n1.y4m -w 3840 -h 2160 -rc 2 -fps-num 24000 -fps-denom 1001 -tbr 8192 -tile-rows 2 -tile-columns 2 -enc-mode 4 -b %~n1.ivf -output-stat-file %~n1.stats 
SvtAv1EncApp -i  %~n1.y4m -w 3840 -h 2160 -rc 2 -fps-num 24000 -fps-denom 1001 -tbr 8192 -tile-rows 2 -tile-columns 2 -enc-mode 4 -b %~n1.ivf -input-stat-file %~n1.stats

I tried to use -rc 2 and -rc 1, non of the approach gives a file of predictable size, unlike aom and rav1e.
I tbr parameter is not a bit rate, I would suggest to update documentation to make it more explicit.

**Comment by yermak** [comment]
@hassount, could you please advise what is the right approach to get predictable output file size with SVT.

**Comment by tianjunwork** [comment]
Hi @yermak , please refer to existing #798, fixing rate control is planned.

**Comment by hassount** [comment]
Please re-test with the new experimental 2-pass and add any feedback in #1458
