### ISSUE TITLE
enable_manual_pred_struct in EbSvtAv1EncConfiguration is not set to False by default

### ISSUE THREAD

**Issue by RidgeSTD** [OpenVisualCloud/SVT-AV1#1245]
The doc of EbSvtAv1Enc.h says `EbSvtAv1EncConfiguration::enable_manual_pred_struct` is supposed to be EB_FALSE by default, while in EbEncHandle.c/`eb_svt_enc_int_parameters`, this field is left unset. This caused access on invalid memory on my build.

**Comment by tianjunwork** [comment]
Hi @RidgeSTD , thank you posting the issue. Could you share your command line to reproduce your issue?

**Comment by RidgeSTD** [comment]
Sure. I tried to test the compiled DLL with simplest code segment: 
```c++
 // step 1: Init handle
return_error = svt_av1_enc_init_handle(&svt_encoder_handle_, svt_callback_data_, eb_enc_parameters_);

// here set some parameters
eb_enc_parameters_->is_16bit_pipeline = 1;
eb_enc_parameters_->source_width = width;
eb_enc_parameters_->source_height = height;
eb_enc_parameters_->render_width = width;
eb_enc_parameters_->render_height = height;
eb_enc_parameters_->frame_rate = 30;
eb_enc_parameters_->enc_mode = 0; // 0 is the best quality, 3 is the highest density mode

 // ERROR: in EbEncHandle.c line 2271, the memcpy will copy from an invalid address since there is actually no pred_struct available
return_error = svt_av1_enc_set_parameter(svt_encoder_handle_, &eb_enc_parameters_);

// step 3: init encoder, THE FOLLOWING CODES ARE IRRELEVANT
......
```
This is caused by enable_manual_pred_struct is not set to its default value EB_FALSE. Line 2271 shall not be executed at all.

My setup is Win10 (Build 17763.1158), Intel i7-6700K with 64GB Ram.

**Comment by RidgeSTD** [comment]
Actually I realised that EB_FALSE is simply 0. Which is funny that on my computer, `enable_manual_pred_struct` is initialised as 205. Same goes with `enable_adaptive_quantization`, which will lead to `EB_ErrorBadParameter`. 

I could not understand that since EbBool is uint8_t, which is supposed to be 0 by default. Looking for the cause.

**Comment by tianjunwork** [comment]
Thanks. I guess you didn't memset eb_enc_parameters_, so the members inside is random value, not 0.
Could you also fix enable_adaptive_quantization in the same PR?

**Comment by tianjunwork** [comment]
Actually, I also found some parameters are missing in `eb_svt_enc_init_parameter`, https://github.com/OpenVisualCloud/SVT-AV1/pull/1241. Pls let me know if you find any else. You can comment in that PR. Thx.
