### ISSUE TITLE
Build broken with NASM < 2.14

### ISSUE THREAD

**Issue by ePirat** [OpenVisualCloud/SVT-AV1#1248]
Due to an interaction of how CMake handles include paths (it always strips the trailing `/`) and a bug in NASM (it does not work with include paths without trailing `/`) building with NASM < 2.14 is currently broken.

It should work with NASM 2.14+ where [this bug](https://bugzilla.nasm.us/show_bug.cgi?id=3392205) should be fixed.

**Comment by ePirat** [comment]
This was apparently never caught by CI, as for some reason we always install both NASM and YASM and the CMake build prefers YASM.

**Comment by tianjunwork** [comment]
Thank you for catching this issue. Since 2.14+ is stable release and out there since 2018-12, we can update CMake with requirement of nasm 2.14+ version. It doesn't show lots benefit to support previous versions.

**Comment by ePirat** [comment]
Good idea, but I don't know how to check the version of nasm in CMake, maybe someone else has an idea how to do this?

**Comment by 1480c1** [comment]
Maybe check `CMAKE_ASM_NASM_COMPILER_VERSION` and do something like
```cmake
if(CMAKE_ASM_NASM_COMPILER_VERSION VERSION_LESS "2.14")
# error or try to find yasm instead
endif()
```
