### ISSUE TITLE
Encoder stuck on 1st frame

### ISSUE THREAD

**Issue by cdgriffith** [OpenVisualCloud/SVT-AV1#125]
```
"svt-av1-1.0.216\SvtAv1EncApp.exe" -intra-period 23 -enc-mode 3 -bit-depth 8 -w 1280 -h 720 -fps 25 -q 30 -i "0000.yuv" -b "0.ivf"
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.4.0
SVT [build]  :  Visual Studio 2017 64 bit
LIB Build date: Feb 28 2019 02:05:50
-------------------------------------------
Number of logical cores available: 16
Number of PPCS 31
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 3
SVT [config]: EncoderBitDepth / CompressedTenBitFormat                          : 8 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1280 / 720
SVT [config]: FrameRate / Gop Size                                              : 25 / 24
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 30 / 33 / 0
-------------------------------------------
Encoding         1
```

~~Build: 216 https://github.com/OpenVisualCloud/SVT-AV1/commit/04f8e2d873fe7938e1c0558d92010e6db61ae73d~~

Update: Bug introduced in build 206 https://github.com/OpenVisualCloud/SVT-AV1/commit/8455b37a8be376eda4be3dce827b5bc1344e8dc8

I went back and tested with 201 and 205 just fine, 206 onward do not work

Usually this file takes about a minute and half to encode, tested with 167 took 85 seconds. On build 126 I let it run for 10 minutes and nothing seemed to happen, using 0% CPU.

Example result on 167:

```
Average Speed:          9.51 fps
Total Encoding Time:    84948 ms
```

Computer: 
* Windows 10 x64
* Intel i9-9900k
* 32 GB DDR4 memory

*Edit: misstyped build number

**Comment by hassount** [comment]
@cdgriffith 
this should be fixed in the next PR that will be fixing the preset tuning

**Comment by j-mas** [comment]
Nothing is going on! Encoding failed with 1 frame! The Master is not usable since three days. Encoding stopped at the first frame!! Please can you make it encoding again!

**Comment by jbeich** [comment]
Encoding via FFmpeg plugin still works. Try passing `-hierarchical-levels 3`.

**Comment by j-mas** [comment]
Thank you!!! This works!

**Comment by cdgriffith** [comment]
How do you run the ffmpeg plugin on Windows, all I see is the pipe example under [Installation](https://github.com/OpenVisualCloud/SVT-AV1#windows-operating-systems-64-bit) and nothing on the [user guide](https://github.com/OpenVisualCloud/SVT-AV1/blob/master/Docs/svt-av1_encoder_user_guide.md#running-the-encoder) ?

**Comment by 1480c1** [comment]
Do you mean compile svt-av1 under windows?

**Comment by cdgriffith** [comment]
Is that what is required for windows and ffmpeg right now, no automatic builds for it currently I assume? (I literally see no documentation for it, so don't know anything about it other than what was said above about `Encoding via FFmpeg plugin still works.` )

**Comment by 1480c1** [comment]
That great, do be careful when compiling since it probably won't be one to one with visual studio (I assume you are using that for compiling since mingw doesn't work right now last time I checked)

**Comment by EwoutH** [comment]
I just tried to test #136 on a 96 vCPU Google Cloud Instance. I used the 1080p .y4m version of the _Sintel trailer_ from [Xiph.org](https://media.xiph.org/). With `-n 72` it got stuck on the first frame, with `-n 60` it apperently ran fine.

The encoder does have a start-up time of about 7 seconds.

**Comment by hassount** [comment]
Fix committed to #136 1fe6c26

**Comment by EwoutH** [comment]
@hassount Thanks for the fix! Next time, if possible, please make separate merge request so it can be tested in isolation of the changing speed levels.

**Comment by hassount** [comment]
@EwoutH 
Agreed, will do.
