### ISSUE TITLE
Does warning "Color format EB_YUV400 not supported" means single-channeled video is not supported?

### ISSUE THREAD

**Issue by RidgeSTD** [OpenVisualCloud/SVT-AV1#1254]
Hello! I am trying to use SVT-AV1 on my depth-camera video stream, which is a 16-bit grayscale stream. My current try is to set configuration as (partially):

```c++
eb_enc_parameters_->is_16bit_pipeline = 1;
eb_enc_parameters_->encoder_color_format = EbColorFormat::EB_YUV400;
```
However the encoder complains the warning "Color format EB_YUV400 not supported, set to EB_YUV420", and later while sending the picture to encoder, `copy_frame_buffer` in EbEncHandle.c will fail since it tries to copy all YUV channels.

Am I setting the wrong parameters? If so, can anyone mention how to encode single-channel video? I couldn't find related info in documents. Thank previously!

**Comment by tianjunwork** [comment]
Hi, for bit depth, you should use encoder_bit_depth, is_16bit_pipeline is to indicate `0: lbd[default], 1: hbd`. Currently only 8bit and 10bit depth is supported.
Yes, svt av1 only supports yuv420 now. @lijing0010 could you comment on the color format support plan? Thank you.

**Comment by lijing0010** [comment]
yes, only I420P 8/10bit is supported

**Comment by tianjunwork** [comment]
Hi @RidgeSTD , if you have no more questions, could you help close the issue? :)
