### ISSUE TITLE
Participate in the MSU Annual Video Codecs Comparison 2020

### ISSUE THREAD

**Issue by EwoutH** [OpenVisualCloud/SVT-AV1#1256]
In succession of #68 :)

The [Call for codecs](http://compression.ru/video/codec_comparison/hevc_2020/call_for_codecs.html) for the MSU Annual Video Codecs Comparison is open for 2020!

The Moscow State University makes an excellent video codec comparison each year, and it would be great if SVT-AV1 would be included. Last years comparison can be [seen here](http://compression.ru/video/codec_comparison/hevc_2019/).

They also still use a silly 6-core Coffee Lake system, maybe you could set them up with a nice Cascade Lake system.

**Comment by hassount** [comment]
request should go to AOM from now on as per #1425
