### ISSUE TITLE
This small video crashes SVT 0.8.3, 0.8.2 and 0.8.1

### ISSUE THREAD

**Issue by JouMxyzptlk** [OpenVisualCloud/SVT-AV1#1262]
This short 8 MB snippet from a DVB-S documentation recording is enough:
https://joumxyzptlk.de/tmp/svt-av1/Die_Planeten_4_Saturn_20200322_2033.SVT-0.8.2_crash_snippet_v2.mkv

Machine: Ryzen 9 3900x / 64 GB ECC RAM (see https://github.com/OpenVisualCloud/SVT-AV1/issues/1159 which was IMHO closed too soon, test if that anime-source video still crashes SVT 0.8.3 too is currently running).

Exact command line and output for 0.8.3 downloaded right now (aka v0.8.2-7-g487f83cc-dirty, version bump forgotten?):
```
c:\prog\ffmpeg\bin\ffmpeg.exe -hide_banner -loglevel quiet -i X:\tmp\video-in\Die_Planeten_4_Saturn_20200322_2033.SVT-0.8.2_crash_snippet_v2.mkv -an  -pix_fmt yuv420p -f yuv4mpegpipe -   | c:\prog\svt-av1\SvtAv1EncApp.exe --input stdin --frames 484 --rc 0 --qp 36 --lp 24 --preset 1 --tile-rows 1 --tile-columns 2 --lookahead 80 --output X:\tmp\video-in\Die_Planeten_4_Saturn_20200322_2033.SVT-0.8.2_crash_snippet_v2.mkv.pr1.qp36.svt-av1.083.ivf
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.8.2-7-g487f83cc-dirty
SVT [build]  :  Visual Studio 2019 64 bit
LIB Build date: Apr 24 2020 21:15:07
-------------------------------------------
Number of logical cores available: 24
Number of PPCS 114
[asm level on system : up to avx2]
[asm level selected : up to avx2]
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 1
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1280 / 720
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 50 / 1 / 48 / 1
SVT [config]: HierarchicalLevels  / PredStructure               : 4 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 36 / 33 / 0
-------------------------------------------
Encoding       289

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-04-24T23:03:50.337001400Z" /> 
  <EventRecordID>21041</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>PC-JOU</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>SvtAv1EncApp.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5ea35716</Data> 
  <Data>SvtAv1Enc.dll</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5ea356e6</Data> 
  <Data>c0000005</Data> 
  <Data>00000000000b4135</Data> 
  <Data>3850</Data> 
  <Data>01d61a8bdb22633a</Data> 
  <Data>c:\prog\svt-av1\SvtAv1EncApp.exe</Data> 
  <Data>c:\prog\svt-av1\SvtAv1Enc.dll</Data> 
  <Data>d52214d0-d334-4b42-a32d-1950cf50cf01</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

Version 0.8.2:
```
c:\prog\ffmpeg\bin\ffmpeg.exe -hide_banner -loglevel quiet -i X:\tmp\video-in\Die_Planeten_4_Saturn_20200322_2033.SVT-0.8.2_crash_snippet_v2.mkv -an  -pix_fmt yuv420p -f yuv4mpegpipe -   | c:\prog\svt-av1\SvtAv1EncApp.exe --input stdin --frames 484 --rc 0 --qp 36 --lp 24 --preset 1 --tile-rows 1 --tile-columns 2 --lookahead 80 --output X:\tmp\video-in\Die_Planeten_4_Saturn_20200322_2033.SVT-0.8.2_crash_snippet_v2.mkv.pr1.qp36.svt-av1.082.ivf
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.8.2-dirty
SVT [build]  :  Visual Studio 2019 64 bit
LIB Build date: Apr 20 2020 02:13:50
-------------------------------------------
Number of logical cores available: 24
Number of PPCS 114
[asm level on system : up to avx2]
[asm level selected : up to avx2]
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 1
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1280 / 720
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 50 / 1 / 48 / 1
SVT [config]: HierarchicalLevels  / PredStructure               : 4 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 36 / 33 / 0
-------------------------------------------
Encoding       190

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-04-24T22:47:46.779098000Z" /> 
  <EventRecordID>21035</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>PC-JOU</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>SvtAv1EncApp.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5e9d0597</Data> 
  <Data>SvtAv1Enc.dll</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5e9d0568</Data> 
  <Data>c0000005</Data> 
  <Data>00000000000b4275</Data> 
  <Data>bc</Data> 
  <Data>01d61a89f41465d2</Data> 
  <Data>c:\prog\svt-av1\SvtAv1EncApp.exe</Data> 
  <Data>c:\prog\svt-av1\SvtAv1Enc.dll</Data> 
  <Data>5959f452-2d1d-41f8-92d8-4198a17ac4d4</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

Version 0.8.1:
```
c:\prog\ffmpeg\bin\ffmpeg.exe -hide_banner -loglevel quiet -i X:\tmp\video-in\Die_Planeten_4_Saturn_20200322_2033.SVT-0.8.2_crash_snippet_v2.mkv -an  -pix_fmt yuv420p -f yuv4mpegpipe -   | c:\prog\svt-av1\SvtAv1EncApp.exe -i stdin -n 484 -rc 0 -q 42 -lp 24 -enc-mode 1 -tile-rows 1 -tile-columns 2 -lad 80 -b X:\tmp\video-in\Die_Planeten_4_Saturn_20200322_2033.SVT-0.8.2_crash_snippet_v2.mkv.em1.q42.svt-av1.081.ivf
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.8.1
SVT [build]  :  Visual Studio 2017 64 bit
LIB Build date: Jan 29 2020 14:56:28
-------------------------------------------
Number of logical cores available: 24
Number of PPCS 114
[asm level on system : up to avx2]
[asm level selected : up to avx2]
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 1
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1280 / 720
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 50 / 1 / 48 / 1
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 42 / 33 / 0
-------------------------------------------
Encoding       194

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-04-24T22:54:38.852406400Z" /> 
  <EventRecordID>21039</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>PC-JOU</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>SvtAv1EncApp.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5e319d54</Data> 
  <Data>SvtAv1Enc.dll</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5e319d25</Data> 
  <Data>c0000005</Data> 
  <Data>000000000005baf5</Data> 
  <Data>18a4</Data> 
  <Data>01d61a8ad2679a1f</Data> 
  <Data>c:\prog\svt-av1\SvtAv1EncApp.exe</Data> 
  <Data>c:\prog\svt-av1\SvtAv1Enc.dll</Data> 
  <Data>a0c3066b-7fe0-4d76-9bc2-ac1f737d7135</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

**Comment by tianjunwork** [comment]
Hi @JouMxyzptlk , for a quick check, I tested with your command on Ubuntu. I didn't crash on 0.8.3 and 0.8.2. Will try on server with Windows OS.

**Comment by JouMxyzptlk** [comment]
Thanks for checking. I forgot to mention: Win10 x64 1909. Good luck reproducing on Windows Server 2019 (=Win10 1809).
Actually it was, originally reproducible crash after 76570 frames, over 25 minutes into the full source video. Which takes QUITE a few hours to reach that point. But I could cut it down to a ~1500 frame snippet and it still crashed, and after a few more tries I ended up with above short snippet which crashes so nicely.
This 23 MB snippet crashes at ~1103 frames here: https://joumxyzptlk.de/tmp/svt-av1/Die_Planeten_4_Saturn_20200322_2033.SVT-0.8.2_crash_snippet.mkv
This is the whole ~45 min video, crash at 76570: https://joumxyzptlk.de/tmp/svt-av1/Die%20Planeten%204%20Saturn%2020200322_2033.mkv

**Comment by tianjunwork** [comment]
Thank you providing the Win version. And making it easier to crash 😄

**Comment by silverbacknet** [comment]
I couldn't reproduce it at all. And then I realized that I'd taken a shortcut by converting to a y4m file before running all tests; as soon as I put it on pipe, as in the original command line, things got very messy in a hurry; not a crash here but "Failed to read proper y4m frame delimeter. Read broken." on about half the frames. Something in the y4m/stdin parsing is broken.

**Comment by JouMxyzptlk** [comment]
Could it be ASM dependent? I.e. if not Zen2 based (or other AVX2 CPU) no problem?

**Comment by JouMxyzptlk** [comment]
> Something in the y4m/stdin parsing is broken.
I use a quite recent ffmpeg version (ffmpeg-20200403-52523b6-win64-static).
Bit this is indeed a hint that i should have tested with a naked yuv file too, maybe it is a pipe problem with svt-av1 on Windows.
Though I could convert with rav1e, including a test with a longer 4k movie which took about three weeks and did use pipe. Rav1e is just not yet as good as SVT-AV1, the result looks like a too strong unsharp-filter somewhere.

**Comment by JouMxyzptlk** [comment]
Update: Not a pipe issue.
This is the yuv4 version of the pipe in the opening comment:
https://joumxyzptlk.de/tmp/svt-av1/SVT-0.8.1-0.8.2-0.8.3-test.yuv4.7z
Crash at nearly exact the same frame as when using the pipe:

C:\tmp>c:\prog\svt-av1\SvtAv1EncApp.exe --input SVT-0.8.1-0.8.2-0.8.3-test.yuv4 --frames 484 --rc 0 --qp 36 --lp 24 --preset 1 --tile-rows 1 --tile-columns 2 --lookahead 80 --output test.ivf
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.8.2-7-g487f83cc-dirty
SVT [build]  :  Visual Studio 2019 64 bit
LIB Build date: Apr 24 2020 21:15:07
-------------------------------------------
Number of logical cores available: 24
Number of PPCS 114
[asm level on system : up to avx2]
[asm level selected : up to avx2]
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 1
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1280 / 720
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 50 / 1 / 48 / 1
SVT [config]: HierarchicalLevels  / PredStructure               : 4 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 36 / 33 / 0
-------------------------------------------
Encoding       288

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-04-25T09:57:50.168705200Z" /> 
  <EventRecordID>21106</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>PC-JOU</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>SvtAv1EncApp.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5ea35716</Data> 
  <Data>SvtAv1Enc.dll</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5ea356e6</Data> 
  <Data>c0000005</Data> 
  <Data>00000000000b4135</Data> 
  <Data>1278</Data> 
  <Data>01d61ae731dbfebd</Data> 
  <Data>c:\prog\svt-av1\SvtAv1EncApp.exe</Data> 
  <Data>c:\prog\svt-av1\SvtAv1Enc.dll</Data> 
  <Data>056842aa-7dd4-4976-8e9b-34233f1ee0b5</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

**Comment by tianjunwork** [comment]
Thanks reporting the issue.
