### ISSUE TITLE
SegFault when enabling option NATIVE

### ISSUE THREAD

**Issue by mtangtencent** [OpenVisualCloud/SVT-AV1#1269]
When I compile the project with cmake option `NATIVE` set to ON, the encoder crashes using the following command line on Linux,
`./SvtAv1EncApp  -i ~/codec_test/videos/480p/BasketballDrill_832x480_50.yuv -w 832 -h 480 -b out.ivf -enc-mode 0 -n 10 -rc 0 -q 30 -irefresh-type 1 -fps-num 60 -fps-denom 1`

The environment was Centos 7.2 and gcc 4.8.5.
The commit number of SVT-AV1 I used is c810eca98c5a7a13f77e92847009751a57332817

**Comment by tianjunwork** [comment]
I guess it is illegal instruction set.
Could you run `gcc -c -Q -march=native --help=target | grep march`. Assume it gives you `-march=XXXX`.
Then replace `native` with `XXXX` in `list(APPEND flags_to_test -march=native)`.
Let me know if it works.

**Comment by tianjunwork** [comment]
And gcc is too old. You may consider upgrade.

**Comment by mtangtencent** [comment]
Hi @tianjunwork, Thanks for the suggestion. It looks fine on ubuntu 18.04 with gcc 7.4.0. But it still fails on centos 7.2 + gcc 4.8.5 even when march is set to xxxx.

**Comment by tianjunwork** [comment]
The encoder runs on any 5th Generation Intel Core™ Processors (formerly Broadwell) CPUs (Xeon E5-v4) or newer. Yeah, that's would be better to skip the old OS system.

**Comment by silverbacknet** [comment]
It's possible you might have better luck using one of the Devtools-* from CentOS's SCL. They're currently packaging gcc 7.x, 8.x, and 9.x for CentOS 7, although 7.2 is quite a long ways behind itself (currently 7.7 I think?), as well.

The method is simply,
```
yum --enablerepo=extras install centos-release-scl
yum install devtools-9
```
