### ISSUE TITLE
Travis not reporting error properly

### ISSUE THREAD

**Issue by joelsole** [OpenVisualCloud/SVT-AV1#127]
Travis reporting MacOS build state as passed:
  https://github.com/OpenVisualCloud/SVT-AV1/pull/113/checks

but there were errors:
  https://travis-ci.com/OpenVisualCloud/SVT-AV1/jobs/181183973

**Comment by 1480c1** [comment]
It's because we are using the script which has `exit` at the end signaling a exit code of 0.

**Comment by 1480c1** [comment]
It would be better to use the direct commands, but it's better to leave it until Mac becomes either fully supported or we have to make it an allowed failure.

**Comment by 1480c1** [comment]
This can be closed probably
