### ISSUE TITLE
Confused about 'Unprocessed tokens'

### ISSUE THREAD

**Issue by Selur** [OpenVisualCloud/SVT-AV1#1271]
calling:
```
ffmpeg -y -loglevel fatal -noautorotate -nostdin -threads 8 -i "F:\TestClips&Co\files\test.avi" -map 0:0 -an -sn -vf zscale=rangein=tv:range=tv -pix_fmt yuv420p10le -strict -1 -vsync 0  -f rawvideo - | SvtAv1EncApp --qp 50 --use-default-me-hme 0 --search-w 256 --search-h 256 --hme-tot-l0-w 256 --hme-tot-l0-h 256 --hme-l0-w 256 --hme-l0-h 256 --hme-l1-w 256 --hme-l1-h 256 --hme-l2-w 256 --hme-l2-h 256  --input stdin  -n 429 --width 640 --height 352 --fps-num 25 --fps-denom 1 --input-depth 10 --output "E:\Temp\17_57_36_8410_01.av1"
```
I get:
```
Unprocessed tokens:  --hme-l0-w  --hme-l2-h  --hme-l0-h  --hme-l1-w  --hme-l1-h  --hme-l2-w

Error in configuration, could not begin encoding! ...
Run SvtAv1EncApp -help for a list of options
Encoder finished
```
But the help states:
```
--hme-l0-w                	Set hierarchical motion estimation level0 search area in Width
--hme-l0-h                	Set hierarchical motion estimation level0 search area in height
--hme-l1-w                	Set hierarchical motion estimation level1 search area in Width
--hme-l1-h                	Set hierarchical motion estimation level1 search area in height
--hme-l2-w                	Set hierarchical motion estimation level2 search area in Width
--hme-l2-h                	Set hierarchical motion estimation level2 search area in height
```
So why are those setting not processed?

**Comment by adaria** [comment]
We missed these when passing to double-dash command line parameters. Will fix it. In the meantime, single dash versions should work.
`-hme-tot-l0-w 256 -hme-tot-l0-h 256 -hme-l0-w 256 -hme-l0-h 256 -hme-l1-w 256 -hme-l1-h 256 -hme-l2-w 256 -hme-l2-h 256`

**Comment by Selur** [comment]
You might want to check others too since I also get that message for:
--enable-intra-edge-sk
--enable-prune-ref-rec-partv
--enable-spatial-sse-f
--enable-class-12
--chroma-m

**Comment by 1480c1** [comment]
@adaria you might also want to check places like https://github.com/OpenVisualCloud/SVT-AV1/blob/ea8f1532e4e085fa766e2e7ee6a43736839408d7/Source/App/EncApp/EbAppMain.c#L420 since they still print out single dash options

**Comment by 1480c1** [comment]
@Selur are you sure you spelled those tokens correctly? Looking at Source/AppEncAppEbAppConfig.c, some of the ones that you mentioned don't exist, but there are ones that are one letter off.

`--enable-intra-edge-sk` vs
`--enable-intra-edge-skp`

**Comment by 1480c1** [comment]
Also, @adaria are you currently working on this? If not I can start working on it

**Comment by adaria** [comment]
Hi @1480c1, I haven't got round to starting on this yet. If you have cycles available, please go ahead. Thank you!
