### ISSUE TITLE
crash when tile is enbaled and enc_dec segment number is reduced

### ISSUE THREAD

**Issue by ttrigui** [OpenVisualCloud/SVT-AV1#1276]
-i F:\stream\kirland_640_480_30.yuv -w 352 -h 288 -bit-depth 8 -tile-rows 1 -tile-columns 1 -enc-mode 0 -lp 2 -n 3 -b output.ivf -o recon.yuv
issue triggered with #1275

**Comment by tszumski** [comment]
Hi, I tried to reproduce this issue with 9efce7ab812f3dfae662eb261e98495745a5b0f6 as a HEAD, both on visual studio 2019 and gcc 7.3.1 Debug/Release build and I cannot get "crash", I tried to modify tile-rows/tile-columns/lp/n parameters but still without crash.
Current HEAD 33f6a51f93d9d71e5422a6a98d98a2013c74081f also doesn't crash.
