### ISSUE TITLE
SVT-AV1 (still) crash at about ~440 to 450 frames.

### ISSUE THREAD

**Issue by JouMxyzptlk** [OpenVisualCloud/SVT-AV1#1280]
HI There ! Actually reopening https://github.com/OpenVisualCloud/SVT-AV1/issues/1159 - maybe a another bug, maybe the same bug, I don't know.
Source still the same video: https://joumxyzptlk.de/tmp/svt-av1-0.8.1-bug/svt-0.8.1-input-video.7z
Versions used: All between the ones noted in issue 1159, the last one was this version; https://ci.appveyor.com/project/tianjunwork/svt-av1/builds/32597284/job/xo3fxma5a9h22myc/artifacts
Still the same Win10 x64 1909, 64 GB RAM, Ryzen 3900x.

Command line and output:
```
c:\prog\svt-av1\SvtAv1EncApp.exe --input input.yuv420p --frames 5038 --rc 0 --qp 35 --lp 24 --preset 1 --tile-rows 1 --tile-columns 2 --lookahead 80 --scm 2 --palette 6 --wn-filter-mode 3 --output out.ivf"
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.8.3-15-ga37c122d-dirty
SVT [build]  :  Visual Studio 2019 64 bit
LIB Build date: May  2 2020 05:17:55
-------------------------------------------
Number of logical cores available: 24
Number of PPCS 88
[asm level on system : up to avx2]
[asm level selected : up to avx2]
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 1
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1920 / 1080
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 500 / 21 / 16 / 1
SVT [config]: HierarchicalLevels  / PredStructure               : 4 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 35 / 33 / 0
-------------------------------------------
Encoding       443
```

I use --scm 2 --palette 6 --wn-filter-mode 3 since without it smudges less color details in some anime videos. The smudging looks like _-vf hqdn3d=4:3:4:3_ -vcodec libx264 -preset:v veryslow -tune:v Anime -crf 20. But it still smudges the details too much, visible in above mentioned test video at 00:13 to 00:42 - the bra outline it completely gone, and a few other details. If you have any encoding hints on that please tell. The only way to keep the bra outline is to use --qp 24, then it matches -vcodec libx264 -preset:v veryslow -tune:v Anime -crf 20 which keeps that detail. But the SVT-AV1 has the same bitrate as the x264, making it useless. That detail loss issue is also the reason why I don't use h265, only with "no strong intra" filter or ridiculous high bitrate such details are kept. Would be nice not to repeat that with AV1.
Or should I open a separate bug for the detail loss issue?

**Comment by tianjunwork** [comment]
Hi @JacksonDagger , Yeah, open another separate issue to discuss the encoding quality is good idea, since this one is for the crash.

**Comment by tianjunwork** [comment]
Hi @JacksonDagger , hope you finished testing the crash issue. Any update? If it is fixed, could you close this one and open another one to track encoding quality?

**Comment by JacksonDagger** [comment]
@tianjunwork Hi Jun, I left Intel a while ago

**Comment by tianjunwork** [comment]
> @tianjunwork Hi Jun, I left Intel a while ago

Sorry, @ the wrong people 😓

**Comment by tianjunwork** [comment]
Hi @JouMxyzptlk hope you finished testing the crash issue. Any update? If it is fixed, could you close this one and open another one to track encoding quality?

**Comment by JouMxyzptlk** [comment]
Up to now no crash. Though: I "only" encoded ~123000 frames so far for six days in one go without crashing. So it is more stable than ever before, at least for me. I hope I'll get around to create an artificial quality-problem sample video over the weekend instead of just suggesting Ojisan to Marshmallow episode 02.

**Comment by tianjunwork** [comment]
Thank you for confirming with such a long encoding:)
Yeah, a sample video would be better to target the quality issue.
