### ISSUE TITLE
Add/clarify documentation for Constant Quantizer Setting

### ISSUE THREAD

**Issue by jackch1** [OpenVisualCloud/SVT-AV1#1284]
Hi, 
I was wondering if it would be possible to add some clarification to the constant quantizer mode.

I understand this mode supports 2-passes, as explained [here:](https://github.com/OpenVisualCloud/SVT-AV1/issues/730#issuecomment-545104906)
'The 2-pass implementation that is currently in the master is a milestone that is meant to add support of a second pass block level qp modulation / qp scaling / temporal filtering settings.'

If the quantization parameter can be modulated when running a 2-pass encode, does this mean the constant quantizer mode doesn't necessarily have constant quantization? And if so, are you able to provide some more clarity on what is 'constant' about it?

Thanks

**Comment by tianjunwork** [comment]
Hi @jackch1 , for `--rc 0` CQP mode, the `-q` value is used as an initial qp level in `adaptive_qindex_calc_two_pass` to adjust qp. `--max-qp` and `--min-qp` can be used to cap the final qp applied.

**Comment by hassount** [comment]
please use the qp file if you need a constant QP everywhere along with ```--lad 0``` which would remove the adaptive quantization per block. please re-open if you have more questions.
