### ISSUE TITLE
There is no PSNR results output when completing the SVT AV1 encoding

### ISSUE THREAD

**Issue by yangluchina** [OpenVisualCloud/SVT-AV1#1289]
when I do the video transcoding in ffmpeg, x.264/x.265 can output the psnr results automatically, but SVT not. Then, I can use the command "ffmpeg -i inputvideo -i mytranscoding_video -lavfi psnr="stats_file=psnr.log" -f null - " to calculate the SVT HEVC psnr result, but there is no method to calculate the psnr of SVT AV1. I think SVT AV1 should integrate the psnr calculation into the ffmpeg as well.

**Comment by yangluchina** [comment]
the error when using the command "ffmpeg -i inputvideo -i svtav1_video -lavfi psnr="stats_file=psnr.log" -f null - " is :
Decoder (codec av1) not found for input stream #1:0

**Comment by silverbacknet** [comment]
Your ffmpeg is way out of date then; update it and you should get PSNR back with the same workflow. SSIM reporting is apparently coming, but I doubt PSNR ever will.

**Comment by yangluchina** [comment]
> Your ffmpeg is way out of date then; update it and you should get PSNR back with the same workflow. SSIM reporting is apparently coming, but I doubt PSNR ever will.

I built the ffmpeg last month from 'git clone https://github.com/FFmpeg/FFmpeg'

**Comment by 1480c1** [comment]
> `Decoder (codec av1) not found for input stream #1:0`

does your FFmpeg have libaom-av1 or libdav1d as an av1 decoder?

**Comment by yangluchina** [comment]
> > `Decoder (codec av1) not found for input stream #1:0`
> 
> does your FFmpeg have libaom-av1 or libdav1d as an av1 decoder?

I tried to install the libaom-av1, but it seems that SVT-AV1 has conflict with libaom-av1. Like the issue in "libsvtav1 conflicts with other libraries in ffmpeg. Does not run unless they are disabled. #567", it hasn't resolved.

**Comment by silverbacknet** [comment]
You still need at least one AV1 decoder in your ffmpeg build. Yes, SVT and libaom have symbols that conflict (that's going away very soon), until then you need to pick one. Or just build with libdav1d since that's generally the fastest software decoder of all. Or just install a pre-built ffmpeg that includes it.

**Comment by tianjunwork** [comment]
Thanks @silverbacknet @1480c1 for helping out.

**Comment by yangluchina** [comment]
> You still need at least one AV1 decoder in your ffmpeg build. Yes, SVT and libaom have symbols that conflict (that's going away very soon), until then you need to pick one. Or just build with libdav1d since that's generally the fastest software decoder of all. Or just install a pre-built ffmpeg that includes it.

libdav1d works now. thanks.

**Comment by tianjunwork** [comment]
Glad to see decoder works. Please close the issue if no more help is needed.

**Comment by yangluchina** [comment]
> Glad to see decoder works. Please close the issue if no more help is needed.

ok, let me close this issue now. 
And hope the issue  #567 can be fixed asap.
