### ISSUE TITLE
Request for static Windows release libs similarly to SVT-HEVC

### ISSUE THREAD

**Issue by oviano** [OpenVisualCloud/SVT-AV1#1301]
I recently integrated SVT-HEVC into my project, which links against the FFmpeg libraries. I build FFmpeg using ShiftMediaProject which makes it possible to build natively using Visual Studio.

It was very useful to be able to download the header files and static libs for SVT-HEVC without needing to build SVT at all.

It seems that the same is not available here - could it be added?

**Comment by tianjunwork** [comment]
Hi @oviano , thanks providing feedback. Sure, we will look into it.

**Comment by 1480c1** [comment]
@oviano it would be better if you commented on https://github.com/OpenVisualCloud/SVT-AV1/pull/1300 since that is where things are currently being decided on for releases

**Comment by oviano** [comment]
> @oviano it would be better if you commented on #1300 since that is where things are currently being decided on for releases

Done, thanks https://github.com/OpenVisualCloud/SVT-AV1/pull/1300#issuecomment-628754031.

**Comment by tianjunwork** [comment]
Hi @oviano, assets are updated in https://github.com/OpenVisualCloud/SVT-AV1/releases/tag/v0.8.3 as discussed in #1300.
