### ISSUE TITLE
Artifacts when encoding non multiple of 8 resolution, 10 bit videos

### ISSUE THREAD

**Issue by quietvoid** [OpenVisualCloud/SVT-AV1#1302]
Hi.

I'm seeing artifacts (mostly chroma related) at the bottom of non multiple of 8 resolution videos.
These kind of artifacts have been around for a while, back to at least v0.7.0.

Basically, 10 bit source videos with non mod 8 resolutions like 1920x804 are being encoded like this by SVT-AV1:
`SVT [config]: SourceWidth / SourceHeight                                        : 1920 / 808`

I've tested all my options and the artifacts are consistently reproducible with this simple CLI:
>.\SvtAv1EncApp.exe -i source-non-mod8.y4m --input-depth 10 --rc 0 --qp 5 --preset 4 -b out.ivf

Encode log: https://0x0.st/iLcp.txt

Presets from 2-7 are affected, however `preset 8` does not seem to be.
0 and 1 might be too, but too slow to test. :)

There are no artifacts if the source file is 8 bit.

I have uploaded the source sample and some encoded files here: https://mega.nz/folder/NBkQVYwD#sAdFDs6HNP_oDideGELHjg
The artifacts are visible at the bottom of frames 2, 4, and 10.

The decoder used does not matter in reproducing the artifacts.
Discussion here: https://github.com/OpenVisualCloud/SVT-AV1/issues/1225#issuecomment-628361521

This is how the bottom left of frame 4 looks like zoomed in:
<img width="848" alt="frame3" src="https://user-images.githubusercontent.com/39477805/81879776-aa4ca880-9559-11ea-8950-7ee34a090994.png">
There is a green line in the image. It seems to only be present in the U and V planes, the Y plane seems to be fine.

In frame 10, there is also this artifact (but it only appears using `--preset 4`):
![image](https://user-images.githubusercontent.com/39477805/81880682-13352000-955c-11ea-8b3a-30b61d4db798.png)

To reproduce the images above, this can be used on the decoded YUV (also included in the link above):
>.\ffmpeg.exe -video_size 1920x804 -r 24 -pixel_format yuv420p10 -color_primaries 1 -colorspace 1 -i decoded-encode.yuv -pix_fmt rgb24 -sws_flags +full_chroma_int+accurate_rnd frame-%d.png

**Comment by EricLamVCD** [comment]
For git tag v0.8.3, I tested presets 0 to 8. I was able to reproduce the issue for presets 0 to 7. 
Also, I tested using master 34dbc84 for presets 0 to 8. I did not see the issue. 

@quietvoid Could you test the latest master to see if you see the issue again?

**Comment by quietvoid** [comment]
Hi @EricLamVCD. I have built master and encoded the sample file and the issue is not present wit preset 4.

Log:
>SVT [version]:	SVT-AV1 Encoder Lib v0.8.3-37-g14a7a6ae
SVT [build]  :	GCC 10.1.0	 64 bit

So it does seem that the artifacts have been corrected. Thank you.
