### ISSUE TITLE
A question about deblocking filter level

### ISSUE THREAD

**Issue by MindyYoung** [OpenVisualCloud/SVT-AV1#1305]
Hi, 
 I notice that the loop filter (deblocking filter ) level is set as a function of AC quantization step size. The parameters of the function seem to be carefully designed,  but I cannot find any articles or annotations (in svt-AV1) describing the details of the design. Are these parameters obtained through assessment experiments？ Is there any mathematical derivation？At your convenience, would you please tell me more detials ? Thank you for your assistance.

`

        // These values were determined by linear fitting the result of the
        // searched level for 8 bit depth:
        // Keyframes: filt_guess = q * 0.06699 - 1.60817
        // Other frames: filt_guess = q * 0.02295 + 2.48225
        //
        // And high bit depth separately:
        // filt_guess = q * 0.316206 + 3.87252
        int32_t filt_guess;
        switch (scs_ptr->static_config.encoder_bit_depth) {
        case EB_8BIT:
            filt_guess = (frm_hdr->frame_type == KEY_FRAME)
                             ? ROUND_POWER_OF_TWO(q * 17563 - 421574, 18)
                             : ROUND_POWER_OF_TWO(q * 6017 + 650707, 18);
            break;
        case EB_10BIT: filt_guess = ROUND_POWER_OF_TWO(q * 20723 + 4060632, 20); break;
        case EB_12BIT: filt_guess = ROUND_POWER_OF_TWO(q * 20723 + 16242526, 22); break;
        default:
            assert(0 &&
                   "bit_depth should be AOM_BITS_8, AOM_BITS_10 "
                   "or AOM_BITS_12");
            return;
        }
        if (scs_ptr->static_config.encoder_bit_depth != EB_8BIT && frm_hdr->frame_type == KEY_FRAME)
            filt_guess -= 4;
        filt_guess = filt_guess > 2 ? filt_guess - 2 : filt_guess > 1 ? filt_guess - 1 : filt_guess;
        int32_t filt_guess_chroma = filt_guess > 1 ? filt_guess / 2 : filt_guess;

        // TODO(chengchen): retrain the model for Y, U, V filter levels
        lf->filter_level[0] = clamp(filt_guess, min_filter_level, max_filter_level);
        lf->filter_level[1] = clamp(filt_guess, min_filter_level, max_filter_level);
        lf->filter_level_u  = clamp(filt_guess_chroma, min_filter_level, max_filter_level);
        lf->filter_level_v  = clamp(filt_guess_chroma, min_filter_level, max_filter_level);
`

**Comment by tianjunwork** [comment]
Hi @chkngit @hguermaz could you help to comment on this question? Thank you.

**Comment by hassount** [comment]
@MindyYoung 
this seems to be coming from the libaom code / spec, it does not seem to be an SVT-AV1 implementation detail.
