### ISSUE TITLE
FFMPEG version 4.2.3 segmentation fault (core dumped)

### ISSUE THREAD

**Issue by NilsThie** [OpenVisualCloud/SVT-AV1#1314]
When I run the encoder in the latest version of FFMPEG, I get the following errors:

`segmentation fault (core dumped)`
`memory access error (memory dumped)`

I'm using Ubuntu 18.04.
SVT-AV1 standalone and in older FFMPEG versions, it works fine.

**Comment by NilsThie** [comment]
I disabled libaom, now it works. Maybe a problem with new libaom 2.0.

**Comment by 1480c1** [comment]
SVT-AV1 and libaom have symbol conflicts for now

**Comment by 1480c1** [comment]
Related issue: https://github.com/OpenVisualCloud/SVT-AV1/issues/567

**Comment by 1480c1** [comment]
@NilsThie if there's nothing else, can you close the issue?
