### ISSUE TITLE
[SVT_AV1] Open Dev Meeting June 3-2020 [SVT-AV1 Re-licensing NOTICE ]

### ISSUE THREAD

**Issue by hassount** [OpenVisualCloud/SVT-AV1#1315]
Hello All

I hope this message finds all of you, family and loved ones safe and healthy.

The sixth Open Dev Team is scheduled for June 3rd 2020, @ 8:30 - 9:30 am PDT

Created a new issue to track the discussion items for this meeting, please let us know your thoughts / suggestions for topics on the Agenda.

Using the same dialup info from last time:
Join Hangouts Meet
meet.google.com/rty-mkxi-wvi

Meeting ID
https://meet.google.com/rty-mkxi-wvi?hs=122

Phone Numbers
(‪US‬) +1 929-269-1840‬
PIN: ‪542 747#‬

More phone numbers
https://meet.google.com/tel/rty-mkxi-wvi?pin=9055644317111&hs=1

**Comment by quietvoid** [comment]
Hi. In #932 it was mentioned that the `--film-grain` switch would be looked at.

It could be an interesting topic to revisit, as I don't think it works in current master.
Also an extension to the topic, whether there are plans to allow users to pass a film grain model file (like aomenc does). Since the current implementation is the same.

Thank you. :smile:

**Comment by EwoutH** [comment]
Would be interested in updates about preset tuning and rate control. Also maybe a roadmap to a 1.0 release, if this is in sight yet, and an update on future ABI stability.

I see a huge amount of work is done on the [svt-01](https://github.com/OpenVisualCloud/SVT-AV1/tree/svt-01) branch. I would be interested in the scope of this branch and the potential size of the PR (it shouldn't be too large in my opinion).

**Comment by hassount** [comment]
One more topic to be added to tomorrow's meeting:
We're planning to re-license the SVT-AV1 project using the [AOM license](https://github.com/OpenVisualCloud/SVT-AV1/blob/master/LICENSE_AOM.md) as a large portion of the code is coming from libaom and carrying that license and to avoid any confusions on dual licensing.
Reaching out to the following contributors to make sure there are no objections to this:
@1480c1 @EwoutH @DesWurstes @jstebbins @luigi311 @klillevo @Kagami @jbeich @tux3 @tmatth @sandersaares @Spacefish @vibhoothiiaanand @murillo128 @markshuttle @gnafuthegreat @ferdnyc @eclipseo @RidgeSTD @dprestegard @novedevo @brion 

For any questions / objections, please join us in tomorrow's meeting.

**Comment by 1480c1** [comment]
@hassount you might have better luck doing what vmaf did and trying to email the authors from the commits and trying asking them though emailing them rather than pinging them


`git shortlog --summary --numbered --email`
https://github.com/Netflix/vmaf/commit/dedaa94dc73a0b8f3cbc5df4dd2b24d1375e037f

**Comment by markshuttle** [comment]
No objections here, of course :)

**Comment by RidgeSTD** [comment]
No objections from here.

Mit freundlichen Grüßen!
Wenlan
在 2020年6月2日 +0200 23:02，Hassene Tmar <notifications@github.com>，写道：

**Comment by klillevo** [comment]
No objections.

**Comment by Kagami** [comment]
No objections.

**Comment by gnafuthegreat** [comment]
I don't think I've contributed any code, but I saw I was pinged :-).  I don't have any objections; seems like a reasonable move.

**Comment by vibhoothiiaanand** [comment]
I have not contributed to Codebase as a whole, as I have been tagged, I have no objections for this, this looks like an important change which is required for wider adoption of AV1 in general since Licensing is important :)

**Comment by tmatth** [comment]
No objections.

**Comment by jstebbins** [comment]
On Tue, 2020-06-02 at 14:02 -0700, Hassene Tmar wrote:
> 
> One more topic to be added to tomorrow's meeting:
> 
> We're planning to re-license the SVT-AV1 project using the AOM
> license as a large portion of the code is coming from libaom and
> carrying that license and to avoid any confusions on dual licensing.
> 
> Reaching out to the following contributors to make sure there are no
> objections to this:
> 
> @1480c1 @EwoutH @DesWurstes @jstebbins @luigi311 @klillevo @Kagami
> @jbeich @tux3 @tmatth @sandersaares @Spacefish @vibhoothiiaanand
> @murillo128 @markshuttle @gnafuthegreat @ferdnyc @eclipseo @RidgeSTD
> @dprestegard @novedevo @brion
> For any questions / objections, please join us in tomorrow's meeting.
> 
> 

I have no objection to the relicensing.

**Comment by novedevo** [comment]
No objections from me.

**Comment by DesWurstes** [comment]
No objections,

**Comment by hassount** [comment]
> Hi. In [#932 (comment)](https://github.com/OpenVisualCloud/SVT-AV1/issues/932#issuecomment-572175617) it was mentioned that the `--film-grain` switch would be looked at.
> 
> It could be an interesting topic to revisit, as I don't think it works in current master.
> Also an extension to the topic, whether there are plans to allow users to pass a film grain model file (like aomenc does). Since the current implementation is the same.
> 
> Thank you. 😄

@andrey-norkin could  you please look into that @quietvoid could you please start an issue on this with whatever you see dis-functional

**Comment by quietvoid** [comment]
> > Hi. In [#932 (comment)](https://github.com/OpenVisualCloud/SVT-AV1/issues/932#issuecomment-572175617) it was mentioned that the `--film-grain` switch would be looked at.
> > It could be an interesting topic to revisit, as I don't think it works in current master.
> > Also an extension to the topic, whether there are plans to allow users to pass a film grain model file (like aomenc does). Since the current implementation is the same.
> > Thank you. smile
> 
> @andrey-norkin could you please look into that @quietvoid could you please start an issue on this with whatever you see dis-functional

No problem, I'll run some tests and open an issue.

**Comment by 1480c1** [comment]
> One more topic to be added to tomorrow's meeting:
> We're planning to re-license the SVT-AV1 project using the [AOM license](https://github.com/OpenVisualCloud/SVT-AV1/blob/master/LICENSE_AOM.md) as a large portion of the code is coming from libaom and carrying that license and to avoid any confusions on dual licensing.
> Reaching out to the following contributors to make sure there are no objections to this:
> @1480c1 @EwoutH @DesWurstes @jstebbins @luigi311 @klillevo @Kagami @jbeich @tux3 @tmatth @sandersaares @Spacefish @vibhoothiiaanand @murillo128 @markshuttle @gnafuthegreat @ferdnyc @eclipseo @RidgeSTD @dprestegard @novedevo @brion
> 
> For any questions / objections, please join us in tomorrow's meeting or post a comment in this discussion.

no objections.

**Comment by luigi311** [comment]
No objections

**Comment by hassount** [comment]
> One more topic to be added to tomorrow's meeting:
> We're planning to re-license the SVT-AV1 project using the [AOM license](https://github.com/OpenVisualCloud/SVT-AV1/blob/master/LICENSE_AOM.md) as a large portion of the code is coming from libaom and carrying that license and to avoid any confusions on dual licensing.
> Reaching out to the following contributors to make sure there are no objections to this:
> @1480c1 @EwoutH @DesWurstes @jstebbins @luigi311 @klillevo @Kagami @jbeich @tux3 @tmatth @sandersaares @Spacefish @vibhoothiiaanand @murillo128 @markshuttle @gnafuthegreat @ferdnyc @eclipseo @RidgeSTD @dprestegard @novedevo @brion
> 
> For any questions / objections, please join us in tomorrow's meeting or post a comment in this discussion.

Thank you for the answers on the re licencing, a second note pinging:
@EwoutH @jbeich @tux3 @sandersaares @Spacefish @murillo128 @ferdnyc @eclipseo @dprestegard @brion

**Comment by jbeich** [comment]
No objections.

**Comment by tux3** [comment]
No objections as well.

**Comment by EwoutH** [comment]
No objections, I like the idea of a single license!

**Comment by 1480c1** [comment]
@hassount you might want to create a new issue tracking license change stuff

**Comment by sandersaares** [comment]
No objections from me.

**Comment by hassount** [comment]
> @hassount you might want to create a new issue tracking license change stuff

By the time I thought about this, it seems like we're almost done :)

**Comment by hassount** [comment]
> > One more topic to be added to tomorrow's meeting:
> > We're planning to re-license the SVT-AV1 project using the [AOM license](https://github.com/OpenVisualCloud/SVT-AV1/blob/master/LICENSE_AOM.md) as a large portion of the code is coming from libaom and carrying that license and to avoid any confusions on dual licensing.
> > Reaching out to the following contributors to make sure there are no objections to this:
> > @1480c1 @EwoutH @DesWurstes @jstebbins @luigi311 @klillevo @Kagami @jbeich @tux3 @tmatth @sandersaares @Spacefish @vibhoothiiaanand @murillo128 @markshuttle @gnafuthegreat @ferdnyc @eclipseo @RidgeSTD @dprestegard @novedevo @brion
> > For any questions / objections, please join us in tomorrow's meeting or post a comment in this discussion.
> 
> Thank you for the answers on the re licencing, a second note pinging:
> @EwoutH @jbeich @tux3 @sandersaares @Spacefish @murillo128 @ferdnyc @eclipseo @dprestegard @brion

so we have the following contributors left: @Spacefish @murillo128 @ferdnyc @eclipseo @dprestegard @brion

**Comment by ferdnyc** [comment]
Oh, sorry, didn't realize you needed an explicit answer. I didn't have any objections to raise, so I didn't! 😉

Anyway: No objections here.

**Comment by dprestegard** [comment]
Thumbs up from me

**Comment by EwoutH** [comment]
@hassount Would it be possible to rebase the _svt-01_ branch on master this week, to allow testing and comparisons?

**Comment by hassount** [comment]
@EwoutH the team is still trying to stabilize the branch and cleanup the extra experimental code . The plan is then to organize the branch in a way that could be broken down into small PRs that make sense then it would be rebased. Then PRs would start populating. The branch would probably be good to be tested towards the beginning of July, then PRs would take place during July.

**Comment by hassount** [comment]
Hi all, 

the re licensing PR #1362 is almost merged last FYI for the few contributors if there are any objections to this:
 @Spacefish @murillo128 @eclipseo  @brion

**Comment by eclipseo** [comment]
No objections.

Whatever I contributed must have been minimal.

Good luck.

**Comment by hassount** [comment]
> No objections.
> 
> Whatever I contributed must have been minimal.
> 
> Good luck.

@eclipseo thank you, agreed, we wanted to check with everyone as much as possible out of respect to the contributors.

**Comment by hassount** [comment]
Close for #1385
