### ISSUE TITLE
Random/non-standard sized videos show corruption after encoding 

### ISSUE THREAD

**Issue by intelmark** [OpenVisualCloud/SVT-AV1#1318]
Generated several non-standard sized test videos using GStreamer. After encoding the streams show corruption.

(Similar issue found in SVT-HEVC and found to be reproducible with v1.2.0 tag (10/2018)
[https://github.com/OpenVisualCloud/SVT-HEVC/issues/533](url)

![image](https://user-images.githubusercontent.com/50715202/83174467-4c7a9d80-a0cf-11ea-81f0-ff77a959eb84.png)

gst-launch-1.0 videotestsrc num-buffers=200 ! video/x-raw, framerate=25/1, width=3204, height=1008! filesink location=3204x1008_420_200.yuv

gst-launch-1.0 videotestsrc num-buffers=200 ! video/x-raw, framerate=25/1, width=804, height=240! filesink location=804x240_420_200.yuv

_Bin/Debug/SvtAv1EncApp -i /testfiles/videotest3204x1008_420_200.yuv -w 3204 -h 1008 -bit-depth 8 -b videotest3204x1008.av1
Video shows corruption when played

Bin/Debug/SvtAv1EncApp -i /testfiles/videotest804x240_420_200.yuv -w 804 -h 240 -bit-depth 8 -b videotest804x240.av1
Video shows corruption when played

**Comment by tianjunwork** [comment]
Video files generated by gst with those resolution looks corrupted.
