### ISSUE TITLE
release source filename missing app info

### ISSUE THREAD

**Issue by th0ma7** [OpenVisualCloud/SVT-AV1#1319]
The filename for all releases doesn't include the package name but rather only the version:
```
https://github.com/OpenVisualCloud/SVT-AV1/archive/v0.8.3.zip
https://github.com/OpenVisualCloud/SVT-AV1/archive/v0.8.3.tar.gz
```
This will eventually cause issues for packagers.
At the very least `svt-av1_v0.8.3.tar.gz` or similar would be meaningful

**Comment by 1480c1** [comment]
Pretty sure that's github's fault

**Comment by 1480c1** [comment]
When I download using curl or wget, it will resolve to the basename of the link, but when you download through the browser, the file name will be generated as `SVT-AV1-0.8.3.tar.gz`

**Comment by 1480c1** [comment]
I guess we can try using https://git-scm.com/docs/git-archive, but idk if it's really worth setting up

**Comment by th0ma7** [comment]
btw, mouse-over or right clicking provides a URL with only a version number.  Same issue with hevc-av1 and pretty much the first time I notice this on github project.

**Comment by th0ma7** [comment]
After further investigating this is a false positive: it's the default expected behaviour.  closing.
