### ISSUE TITLE
The --film-grain switch has no effect

### ISSUE THREAD

**Issue by quietvoid** [OpenVisualCloud/SVT-AV1#1322]
Hi.

I'm opening this issue because the `--film-grain` switch does not seem to work.
Also related: https://github.com/OpenVisualCloud/SVT-AV1/issues/1315#issuecomment-638280908
There is no denoising nor film-grain parameters added in the bitstream.

I have built the binary on Linux from master.
>SVT [version]:	SVT-AV1 Encoder Lib v0.8.3-40-g88c125c7
SVT [build]  :	GCC 10.1.0	64 bit
LIB Build date: Jun  3 2020 13:53:26

I am running these CLIs to encode CQP in 2 passes:
>SvtAv1EncApp -i 8bit-filmgrain.y4m --preset 4 --film-grain 50 --fps-num 24000 --fps-denom 1000 --irefresh-type 2 --rc 0 --qp 20 --output-stat-file out.stats --enc-mode-2p 4 -b filmgrain50.ivf

>SvtAv1EncApp -i 8bit-filmgrain.y4m --preset 4 --film-grain 50 --fps-num 24000 --fps-denom 1000 --irefresh-type 2 --rc 0 --qp 20  --input-stat-file out.stats --preset 4 -b filmgrain50.ivf

And repeating for both `--film-grain 50` and `--film-grain 0`

Regardless of the value used, the final encode bitrate is identical.

Decoding the encodes (dav1d 0.7.0):
>dav1d -i filmgrain0.ivf -o david-fg0.yuv
>dav1d -i filmgrain50.ivf -o david-fg50.yuv

The SHA-1 sum of both files:
>017febcf63073bc1123e5be89a511da747708970  david-fg0.yuv
>017febcf63073bc1123e5be89a511da747708970  david-fg50.yuv

Using dav1d with the `--filmgrain 0` switch results in the same decoded YUV.

Sample log available here: https://0x0.st/iOp1.txt
Samples & derived files here: https://mega.nz/folder/EEkEAYLA#CokKkNxBXDsUny9hhwrEfQ

In comparison, `aomenc` with this CLI:
>aomenc -v --codec=av1 --good --fps=24000/1000 --cpu-used=5 --denoise-noise-level=50 --passes=2 --end-usage=q --cq-level=20 --ivf --fpf=out.stats -o aomenc-noise-level-50.ivf 8bit-filmgrain.y4m

The bitrate difference is significant:
>--denoise-noise-level=0 -> 61.3 Mb/s
--denoise-noise-level=50 -> 5.1 Mb/s

**Comment by wswartzendruber** [comment]
I have encountered this with the 0.8.4 tag.

**Comment by hassount** [comment]
Please track in #1444
