### ISSUE TITLE
Build error ffmpeg plugin

### ISSUE THREAD

**Issue by FreddyX078** [OpenVisualCloud/SVT-AV1#1327]
Today, I'm trying to build SVT-AV1 and the plugin for FFMPEG but it fails with the following error:

`
libavcodec/libsvt_av1.c:416:5: error: implicit declaration of function 'ff_side_data_set_encoder_stats' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    ff_side_data_set_encoder_stats(pkt, headerPtr->qp * FF_QP2LAMBDA, NULL, 0, pict_type);
    ^
1 warning and 1 error generated.
make: *** [libavcodec/libsvt_av1.o] Error 1
`

My build system is MacOS Catalina 10.15.5. 
If more info needed, let me know. Thanks.

**Comment by 1480c1** [comment]
are you building on the master branch of FFmpeg?

related pr https://github.com/OpenVisualCloud/SVT-AV1/pull/1326

**Comment by FreddyX078** [comment]
Yes, I'm building on ffmpeg master branch.

**Comment by 1480c1** [comment]
If you want to compile SVT-AV1 with FFmpeg's master branch, you will either need to use the patches linked in #1326 or you can use these https://gist.github.com/1480c1/ecc1dd3a15093398492c86f2314f4a67

Else, to use the ones currently in the master branch, you will need to use n4.2.3

**Comment by FreddyX078** [comment]
Thank you, that did the trick!
