### ISSUE TITLE
Crash when use-default-me-hme is set as 0 without presetting search area height

### ISSUE THREAD

**Issue by Cidana-Developers** [OpenVisualCloud/SVT-AV1#1328]
The CLI I used is:
-i ../../test/vectors/niklas_640_480_30.yuv -w 640 -h 480 -b output.ivf -o recon.yuv -stat-report 1 -q 15 --use-default-me-hme 0

I run the program in Visual Studio 2019, in Release mode

The program crashed as soon as i run it, the crash was a "Access violation reading"
![img1](https://user-images.githubusercontent.com/59598349/82621965-23f62d80-9c0f-11ea-8a11-31aab3bf20ca.png)

After i turned on the DEBUG INFO in release mode, I found it crashed at about line 5105 in file EbMotionEstimation.c (interpolation TL position calculation), there, search_region_index was calculated as negative number, and it crashed when calculated distortion_top_left_pos in the next line.

Then, i figured out it is because y_search_index is negative, and it made search_region_index to be negative, and the y_search_index was calculated at the beginning of this function 

“int32_t y_search_index = (y_mv >> 2) - y_search_area_origin;”

then I printed out the values of p_best_MV, y_mv and y_search_area_origin trying to find the relationship between them, then, I found y_search_area_origin was position when *p_best_MV and y_mv were 0, it was the reason why y_search_index was negative.

There mush be something wrong with y_search_area_origin or y_mv, i went up 2 levels of call stack to check context_ptr->y_search_area_origin[list_index][ref_pic_index], (I also checked the pos_j_buffer but nothing strange found) 

The context_ptr->y_search_area_origin[list_index][ref_pic_index] values were calculated (updated) in function integer_search_sb (EbMotionEstimation.c about line 9500), in this function, y_search_area_origin was calculated as negative number. 

I compared the y_search_area_origin values when use-default-me-hme set as 0 and when use-default-me-hme set as 1, there were some y_search_area_origin mismatches. 

![img2](https://user-images.githubusercontent.com/59598349/82622030-5869e980-9c0f-11ea-8430-8fa3765dc825.png)

By debugging step by step, i found the “Update ME search region size based on hme-data part” (about line 9595), search_area_height was calculated as 0 (There is no reason search area size can be 0, right?!)

![img3](https://user-images.githubusercontent.com/59598349/82622074-70da0400-9c0f-11ea-8237-abecbfe41eb0.png)

Search_area_height got the value from context_ptr->search_area_height, and context_ptr->search_area_height is initialized either by predefined value or argument settings from user. 

Since “--use-default-me-hme 0” is set in CLI, I found the function where it was initialized, function “set_me_hme_params_from_config” in EbMotionEstimationProcess.c

![img4](https://user-images.githubusercontent.com/59598349/82622090-7afc0280-9c0f-11ea-846f-a09fec42abe4.png)

When use-default-me-hme is set to 0, search_area_height should get value from user by “--search-h”, what if user forgets to set the parameter? It is initialized in EbEncHandle.c about line 2964 

![img5](https://user-images.githubusercontent.com/59598349/82622112-8818f180-9c0f-11ea-8488-883e0a0b7569.png)

Its initial value is 7. so this is the reason why search_area_height is calculated as 0 when user does not set search height in the argument.

**Comment by ttrigui** [comment]
@Cidana-Developers Thank you for the detailed explanation.
@Tomasz, I confirmed the issue I used master with the following command line -i F:\stream\kirland_640_480_30.yuv -w 640 -h 480 -b output.ivf -o recon.yuv -stat-report 1 -q 15 --use-default-me-hme 0
The issue is fixed when I set the search are height to a minimum value (4).
else if (context_ptr->reduce_me_sr_flag[list_index][ref_pic_index]) {
                search_area_width = ((search_area_width / 8) + 7) & ~0x07;
                search_area_height = MAX(4,(search_area_height / 8));
            }
Please try to reproduce it, apply the fix to all cases to make sure the search area height is never 0.conduct more tests (pick any random clips using the same command line) and PR the fix is everything is fine.
yuv can be found under \\vccv01a-cifs.vc.intel.com\emblaze_devshare\Tahani\ToTomasz

**Comment by hassount** [comment]
@tszumski has this been addressed ?

**Comment by tszumski** [comment]
@hassount 
I didn't address this issue(I think that Tahani assigned wrong person to this issue). I can look into this and prepare fix in next week

**Comment by tszumski** [comment]
Hi @ttrigui 
With current master(3df380d2802ae253272f19336b24d03d2417b4bf) I cannot reproduce this issue.
The cases for which your fix should be applied are under ```ME_HME_PRUNING_CLEANUP``` flag (which means unused in code)
```
#define ME_HME_PRUNING_CLEANUP  1 // cleanup HME/ME ref pruning and HME-based ME SR reduction

#if ME_HME_PRUNING_CLEANUP
            search_area_width = ((search_area_width / context_ptr->reduce_me_sr_divisor[list_index][ref_pic_index]) + 7) & ~0x07;
            search_area_height = MAX(1, (search_area_height / context_ptr->reduce_me_sr_divisor[list_index][ref_pic_index]));
#else
            if (context_ptr->reduce_me_sr_flag[list_index][ref_pic_index] == SC_HME_TH_STILL) {
                search_area_width = ((search_area_width / SC_SR_DENOM_STILL) + 7) & ~0x07;
                search_area_height = (search_area_height / SC_SR_DENOM_STILL);
            }
            else if (context_ptr->reduce_me_sr_flag[list_index][ref_pic_index] == SC_HME_TH_EASY) {
                search_area_width = ((search_area_width / SC_SR_DENOM_EASY) + 7) & ~0x07;
                search_area_height = (search_area_height / SC_SR_DENOM_EASY);
            }
            else if (context_ptr->reduce_me_sr_flag[list_index][ref_pic_index]) {
                search_area_width = ((search_area_width / 8) + 7) & ~0x07;
                search_area_height = (search_area_height / 8);
            }
            else {
                search_area_width = (search_area_width + 7) & ~0x07;
            }
#endif
```

Should I apply changes even though this part of code is unused ?

**Comment by hassount** [comment]
> or which your fix should be applied are under `ME_HME_PRUNING_CLEANUP` flag (which means u

@tszumski thank you, this code will then be removed when we perform the macros cleanup

**Comment by ttrigui** [comment]
> Hi @ttrigui
> With current master([3df380d](https://github.com/OpenVisualCloud/SVT-AV1/commit/3df380d2802ae253272f19336b24d03d2417b4bf)) I cannot reproduce this issue.
> The cases for which your fix should be applied are under `ME_HME_PRUNING_CLEANUP` flag (which means unused in code)
> 
> ```
> #define ME_HME_PRUNING_CLEANUP  1 // cleanup HME/ME ref pruning and HME-based ME SR reduction
> 
> #if ME_HME_PRUNING_CLEANUP
>             search_area_width = ((search_area_width / context_ptr->reduce_me_sr_divisor[list_index][ref_pic_index]) + 7) & ~0x07;
>             search_area_height = MAX(1, (search_area_height / context_ptr->reduce_me_sr_divisor[list_index][ref_pic_index]));
> #else
>             if (context_ptr->reduce_me_sr_flag[list_index][ref_pic_index] == SC_HME_TH_STILL) {
>                 search_area_width = ((search_area_width / SC_SR_DENOM_STILL) + 7) & ~0x07;
>                 search_area_height = (search_area_height / SC_SR_DENOM_STILL);
>             }
>             else if (context_ptr->reduce_me_sr_flag[list_index][ref_pic_index] == SC_HME_TH_EASY) {
>                 search_area_width = ((search_area_width / SC_SR_DENOM_EASY) + 7) & ~0x07;
>                 search_area_height = (search_area_height / SC_SR_DENOM_EASY);
>             }
>             else if (context_ptr->reduce_me_sr_flag[list_index][ref_pic_index]) {
>                 search_area_width = ((search_area_width / 8) + 7) & ~0x07;
>                 search_area_height = (search_area_height / 8);
>             }
>             else {
>                 search_area_width = (search_area_width + 7) & ~0x07;
>             }
> #endif
> ```
> 
> Should I apply changes even though this part of code is unused ?

Thank you @tszumski for looking into this. There is no need to add the fix as the code is not used anymore.
