### ISSUE TITLE
How to disable restoration filter

### ISSUE THREAD

**Issue by zyue128** [OpenVisualCloud/SVT-AV1#1333]
Hi, I am trying to run some performance comparison with restoration filter ON/OFF.
But by toggling  --enable-restoration-filtering between 1/0 does not show any difference. I am wondering if I am missing anything that block the enabling/disabling.
here is the commend line I used:
./SvtAv1EncApp -i input.yuv -w 352 -h 288  -b out.ivf --fps-num 30 --fps-denom 1 -n 10 --scm 0 --latency-mode 0 --preset 8 --enable-stat-report 1 --rc 0 -q 37 --lookahead 0 --keyint 59 --enable-restoration-filtering 1 

Thank you for your help.

**Comment by hassount** [comment]
@zyue128 
interesting, I believe this is due to restoration being off already in --preset 8 but ON should be able to force it on. @adaria would you be able to help with this ?

**Comment by adaria** [comment]
Sure thing. I'll have a look

**Comment by adaria** [comment]
Hi @zyue128,
The restoration filter is indeed off for presets >=8 and `--enable-restoration-filtering 1` forces it on. I ran a quick test with your command line parameters on multiple 8- and 10-bit sources and I do see a BD rate difference from restoration filtering, see results below. Could you elaborate on not seeing a difference in your experiments? Thanks!

**BD rates for restoration-filtering-on vs restoration-filtering-off**
|       |   PSNR Y   |  PSNR U    |  PSNR V     |  PSNR YUV   |  VMAF    |
|-------| -----------| -----------| -----------| -----------| -----------| 
|count  | 39.000000  | 39.000000  | 39.000000  | 39.000000  | 39.000000  | 
|mean   | -0.146256  | -0.000128  | -0.027513  | -0.124128  | 0.165000   |
|std    | 0.265448   | 0.596287   | 0.813665   | 0.266481   | 1.292004   | 
|min    | -0.652000  | -1.069000  | -1.532000  | -0.646000  | -2.525000  | 
|25%    | -0.299500  | -0.397000  | -0.542500  | -0.313000  | -0.594000  | 
|50%    | -0.141000  | -0.003000  | -0.123000  | -0.130000  | 0.307000   | 
|75%    | 0.047000   | 0.298000   | 0.429500   | 0.035500   | 1.029000   |
|max    | 0.406000   | 1.118000   | 3.510000   | 0.386000   | 2.695000   | 

restoration on command example:
`
SvtAv1EncApp -w 640 -h 360  -q 20 --scm 0 --latency-mode 0 --preset 8 --enable-stat-report 1 --rc 0 --lookahead 0 --enable-restoration-filtering 1 --lp 48 --keyint 120 -n 60 --input-depth 8 --fps-num 30 --fps-denom 1 -i input.yuv -b output.ivf
`

restoration off command example:
`
SvtAv1EncApp -w 640 -h 360  -q 20 --scm 0 --latency-mode 0 --preset 8 --enable-stat-report 1 --rc 0 --lookahead 0 --enable-restoration-filtering 0 --lp 48 --keyint 120 -n 60 --input-depth 8 --fps-num 30 --fps-denom 1 -i input.yuv -b output.ivf
`

**Comment by zyue128** [comment]
Thank you for your help. Seems like it's indeed working. It might be because the resolution of the test suites I am running is very low, thus the benefit of LRF is not very obvious. 
I will try to lower the presets to play around the params.
Imma close the issue now. Thank you so much!
