### ISSUE TITLE
Broken Pipe using ffmpeg: av_interleaved_write_frame() and Error writing trailer of pipe

### ISSUE THREAD

**Issue by jamescheaton** [OpenVisualCloud/SVT-AV1#1344]
I am using ffmpeg & AV1 to encode a short mp4 video, however upon completion of the encoding I get the error messages above. The Encoder seems to be working fine, and there is no other information along with these error messages from where I can go forward - has anyone encountered this issue before? I saw an issue with a similar error message however this was due to the size of the video, which I have ensured is correct (the encoding fails otherwise).
Here is the ouput I get:

```none
SUMMARY --------------------------------- Channel 1  --------------------------------
Total Frames            Frame Rate              Byte Count              Bitrate
          60            30.00 fps                    59494              237.98 kbps


Channel 1
Average Speed:          1.480 fps
Total Encoding Time:    40551 ms
Total Execution Time:   43307 ms
Average Latency:        34721 ms
Max Latency:            40415 ms
SvtMalloc[info]: you have no memory leak
Encoder finished
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe
frame=   61 fps=1.4 q=-0.0 Lsize=   81000kB time=00:00:02.03 bitrate=326337.1kbits/s dup=7 drop=0 speed=0.0456x
video:82350kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
```

**Comment by 1480c1** [comment]
Please at least put in the command line you ran, there's no information on how to reproduce or anything at all essentially.

**Comment by jamescheaton** [comment]
Apologies, missed that. I was just using the sample command:
ffmpeg -i [input.mp4] -nostdin -f rawvideo -pix_fmt yuv420p - | SvtAv1EncApp.exe -i stdin -n 60 -w 1280 -h 720

**Comment by 1480c1** [comment]
This seems like to me that because you limited the input frame count of SvtAv1EncApp, it closed the pipe after reading 60 frames. FFmpeg has no way to reliably detect such a closure and has no way to push to a closed pipe, so it will report `Broken pipe`

**Comment by 1480c1** [comment]
You might instead want to move the frame counting to ffmpeg's side by using
```bash
ffmpeg -i input.mp4 -vframes 60 -f yuv4mpegpipe - | SvtAv1EncApp -i stdin ...
```

**Comment by jamescheaton** [comment]
Ok thanks, was just about to ask about this frame count. Cheers for your help!
