### ISSUE TITLE
Release files should be packed

### ISSUE THREAD

**Issue by stax76** [OpenVisualCloud/SVT-AV1#1346]
Hello,
I think release files should be packed as zip or 7z to preserve timestamps and avoid issues with browsers and anti malware software.

**Comment by 1480c1** [comment]
Which exact ones? We currently provide

- static SvtAv1DecApp.exe and SvtAv1EncApp.exe
- static SvtAv1Enc.lib
- shared SvtAv1Enc-shared.7z (contains shared app and libs)
- GitHub autogenerated source code archives

**Comment by stax76** [comment]
I use only SvtAv1EncApp.exe in staxrip.
