### ISSUE TITLE
SvtAv1EncApp: Do not use a static variable to count encode frame number. 

### ISSUE THREAD

**Issue by xuguangxin** [OpenVisualCloud/SVT-AV1#1369]
https://github.com/OpenVisualCloud/SVT-AV1/blob/d9522f82f4510b3d886b7b3c41d441a974d50f4b/Source/App/EncApp/EbAppProcessCmd.c#L1140

it may introduce double frame count issue for 2 passes encode. 
see 
https://github.com/OpenVisualCloud/SVT-AV1/pull/1365#issuecomment-655253829
for details

**Comment by tianjunwork** [comment]
I guess it is fine to be static. Only need to set it to 0 again in init function.

**Comment by hassount** [comment]
It’s meant to be static to measure all frames processed when multi- instance encoding is used

**Comment by xuguangxin** [comment]
thanks for information.
static variable or global variable is a flavor of bad code. Let me check we can do something or not.
thanks
