### ISSUE TITLE
Tiles bitrate overhead

### ISSUE THREAD

**Issue by hassount** [OpenVisualCloud/SVT-AV1#137]
A quick speed test I ran overnight between a few recent builds from the master branch. The 70% performance increase claimed by #69 was reproduced (75,7%), while the bit-rate dropped by 6,5%.

| Build    | Build date | Time (ms) | Speed (fps) | Bitrate (kb/s) |
|----------|-----------:|----------:|------------:|---------------:|
| 77174da0 |      02-21 |    938296 |       0,128 |         298,91 |
| a39acb2f |      02-21 |    946272 |       0,127 |         298,91 |
| aee586f1 |      02-20 |   1662581 |       0,072 |         319,68 |
| 476fc452 |      02-19 |   1703176 |       0,070 |         319,68 |

Also a quick test on tiling performance, adding 4 tiles (`-tile-columns 2`) increased the bitrate by 16,9%. I will run a more extensive test soon.

| Build    | Build date | Time (ms) | Speed (fps) | Bitrate (kb/s) | Exta options    |
|----------|-----------:|----------:|------------:|---------------:|-----------------|
| 77174da0 |      02-21 |    953014 |       0,126 |         349,54 | -tile-columns 2 |
| 77174da0 |      02-21 |    938296 |       0,128 |         298,91 |                 |

- **Video:** Morocco (1080p 8-bit 4:2:0)
- **Settings:** ` -enc-mode 0 -n 120`
- **System:** i5-4590 (4c/4t, AVX2), 16GB DDR3, Windows 10 64-bit

[Full details](https://docs.google.com/spreadsheets/d/1p3PJQMkyhIrXEL6MBBQiwTnWmGyHY_zuw7_XAD0def4/edit?usp=sharing).

_Originally posted by @EwoutH in https://github.com/OpenVisualCloud/SVT-AV1/issues/98#issuecomment-466315174_

**Comment by EwoutH** [comment]
@hassount Sure this is a bug? Some overhead from tiling is expected. Here are two more tables (also from https://github.com/OpenVisualCloud/SVT-AV1/issues/98).

| Bitrate (kb/s)    | -tile-rows 0 | -tile-rows 1 | -tile-rows 2 |
|-----------------|-------------:|-------------:|-------------:|
| **-tile-columns 0** |       314,02 |       318,48 |       327,22 |
| **-tile-columns 1** |       336,15 |       341,05 |       354,43 |
| **-tile-columns 2** |       362,07 |       372,46 |       388,68 |
| **-tile-columns 3** |       399,21 |       421,10 |       447,41 |

| Bitrate (%)     | -tile-rows 0 | -tile-rows 1 | -tile-rows 2 |
|-----------------|-------------:|-------------:|-------------:|
| **-tile-columns 0** |       100,0% |       101,4% |       104,2% |
| **-tile-columns 1** |       107,0% |       108,6% |       112,9% |
| **-tile-columns 2** |       115,3% |       118,6% |       123,8% |
| **-tile-columns 3** |       127,1% |       134,1% |       142,5% |

Note that the [clip I tested](https://www.youtube.com/watch?v=hVvEISFw9w0) (first 120 frames / 2 sec) has a lot of vertical motion. I will try to test some other clips with different motion patterns at (implementing #91 would help).

**Comment by hassount** [comment]
We have tested this over the AOM test set and compared it to the behavior of libaom and we have noticed that the overhead becomes much larger than expected as we grow the number of tiles. that said, maybe the bug classification is not appropriate and should be an enhancement instead?

**Comment by EwoutH** [comment]
If it's much larger then expected then it's indeed a bug, thanks for confirming.

**Comment by hassount** [comment]
M5-SVT-AV1 |   |   | PSNR | SSIM | AEVRAGE |  
-- | -- | -- | -- | -- | -- | --
  |   | svt-av1 | Y | U | V | YUV | Y | U | V | YUV | Y | YUV | BD-rate_COST | BitRate   Deviation
Row1 Column1 | vs. | M5 | 3.9% | 2.9% | 2.9% | 3.5% | 4.0% | 3.2% | 3.2% | 3.8% | 3.9% | 3.6% | 3.8% | 3.1%
Row2 Column1 | vs. | M5 | 6.0% | 5.2% | 4.9% | 5.7% | 6.7% | 5.6% | 5.5% | 6.4% | 6.4% | 6.0% | 6.2% | 5.3%
Row1 Column2 | vs. | M5 | 7.8% | 5.4% | 5.2% | 7.5% | 7.0% | 5.5% | 5.8% | 6.6% | 7.4% | 7.1% | 7.2% | 5.3%
Row2 Column2 | vs. | M5 | 6.6% | 6.6% | 6.7% | 6.6% | 8.2% | 8.2% | 7.5% | 8.0% | 7.4% | 7.3% | 7.3% | 8.2%
  |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |  
CPU5 - AOM |   |   | PSNR | SSIM | AEVRAGE |  
  |   | AOM | Y | U | V | YUV | Y | U | V | YUV | Y | YUV | BD-rate_COST | BitRate   Deviation
Row1 Column1 | vs. | M5 | -0.1% | -0.5% | -0.2% | -0.1% | 0.7% | -0.6% | 0.1% | 0.6% | 0.3% | 0.2% | 0.3% | 1.2%
Row2 Column1 | vs. | M5 | 1.0% | 0.6% | 1.0% | 1.0% | 2.0% | 0.5% | 1.3% | 1.9% | 1.5% | 1.4% | 1.5% | 2.03%
Row1 Column2 | vs. | M5 | 2.1% | 1.3% | 0.7% | 1.8% | 2.0% | 0.8% | 1.5% | 1.9% | 2.1% | 1.9% | 2.0% | 2.12%
Row2 Column2 | vs. | M5 | 2.3% | 1.9% | 2.5% | 2.3% | 3.6% | 2.1% | 3.0% | 3.4% | 3.0% | 2.9% | 2.9% | 3.17%

**Comment by hassount** [comment]
Addressed in #235
