### ISSUE TITLE
 Developer survey

### ISSUE THREAD

**Issue by tianjunwork** [OpenVisualCloud/SVT-AV1#1372]
We'd like to hear your thoughts on open source projects in [OpenVisualCloud](https://github.com/OpenVisualCloud).
Help us to continue to shape the future of video processing on cloud.

Take our quick survey in https://intel.az1.qualtrics.com/jfe/form/SV_3OFSYX1RYKrEphP?Source=GitHub. Survey can be found also in [01.org OVC page](https://01.org/openvisualcloud). You may be a lucky winner of a $25 gift card.
We very much appreciate your valuable input.

**Comment by sandersaares** [comment]
FYI "Which of these industry events do you typically attend? Select all that apply." refuses to accept 0 selections.
