### ISSUE TITLE
wedge_mode = 2,3 raises segmentation fault

### ISSUE THREAD

**Issue by nasirhemed** [OpenVisualCloud/SVT-AV1#1382]
I was reading about wedge_mode in the appendix for compound prediction. I wanted to try using estimate_wedge_sign mode. When I try to change `pcs_ptr->wedge_mode = 2;` in [EbPictureDecisionProcess.c](https://github.com/OpenVisualCloud/SVT-AV1/blob/master/Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c#L1100) and build again, I am getting segmentation fault

Commit message used:
ba72bc8511ed6a31544152590740e85f99a41300

Video used: 
[soccer.y4m](https://media.xiph.org/video/derf/y4m/soccer_qcif_15fps.y4m) converted to yuv

Encoder command: 
`SvtAv1EncApp -w 176 -h 144 --preset 3 --compound 2 -i soccer.yuv`

Error output:
`217596 segmentation fault  SvtAv1EncApp -w 176 -h 144 --preset 3 --compound 2 -i soccer.yuv`

**Comment by nasirhemed** [comment]
It seems like this is due to the fact that wedge_index was defined to be -1 [here](https://github.com/OpenVisualCloud/SVT-AV1/blob/master/Source/Lib/Encoder/Codec/EbEncInterPrediction.c#L657) but `interinter_comp->wedge_index` is an unsigned int, so it gets set to 255. With there being at most 32 wedge indices, it makes sense that we get a seg fault

What should the wedge index be when we estimate the wedge_sign ?

**Comment by hassount** [comment]
@chkngit could you please take a quick look at this ?

**Comment by nasirhemed** [comment]
Found the issue and opened a pr #1392
