### ISSUE TITLE
[SVT_AV1] Open Dev Meeting July 22-2020 [SVT-AV1 Re-licensing NOTICE ]

### ISSUE THREAD

**Issue by hassount** [OpenVisualCloud/SVT-AV1#1385]
Hello All

I hope this message finds all of you, family and loved ones safe and healthy.

The sixth Open Dev Team is scheduled for July 22nd 2020, @ 8:30 - 9:30 am PDT

Created a new issue to track the discussion items for this meeting, please let us know your thoughts / suggestions for topics on the Agenda.

Using the same dialup info from last time:
Join Hangouts Meet
meet.google.com/rty-mkxi-wvi

Meeting ID
https://meet.google.com/rty-mkxi-wvi?hs=122

Phone Numbers
(‪US‬) +1 929-269-1840‬
PIN: ‪542 747#‬

More phone numbers
https://meet.google.com/tel/rty-mkxi-wvi?pin=9055644317111&hs=1

**Comment by hassount** [comment]
Linking #1372

**Comment by hassount** [comment]
Topic to be discussed, svt-01 branch rebasing and merging, being done in the m-synch branch.

**Comment by adaria** [comment]
Please find attached the recording of the meeting. Thank you everyone!
[open-dev-meeting-July22-2020.zip](https://github.com/OpenVisualCloud/SVT-AV1/files/4961071/open-dev-meeting-July22-2020.zip)

**Comment by Richard-li** [comment]
> 
> 
> Please find attached the recording of the meeting. Thank you everyone!
> [open-dev-meeting-July22-2020.zip](https://github.com/OpenVisualCloud/SVT-AV1/files/4961071/open-dev-meeting-July22-2020.zip)

The zip file just includes a empty folder?? (75 bytes), Would you please check it again? @adaria

**Comment by adaria** [comment]
There was a file access issue with the above, my bad. You can access the recording below. 
Let me know if you still have trouble.  
[open-dev-meeting-July22-2020](https://drive.google.com/file/d/1VqM7K-wumZ7sizwgi2wuLW7zLBXyDa7E/view?usp=sharing)

**Comment by hassount** [comment]
Closed for 1430
