### ISSUE TITLE
Question about the out of memory message

### ISSUE THREAD

**Issue by palexander-14** [OpenVisualCloud/SVT-AV1#1387]
Hello,

I've seen in https://github.com/OpenVisualCloud/SVT-AV1/blob/73793b03cd9d5948b5a317e68a55879eba500044/Source/Lib/Common/Codec/EbMalloc.h#L35
an unconditional output of the error message to the stderr.
Was that done on purpose or just wasn't wrapped into the SVT_ERROR or SVT_FATAL or whatever macro?

**Comment by hassount** [comment]
@xuguangxin

**Comment by xuguangxin** [comment]
@palexander-14 , we may forgot to wrapper it with SVT_ERROR. 
welcome for the patch, if you are interested .

**Comment by 1480c1** [comment]
As far as I know, although the message itself is not wrapped in SVT_ERROR, almost all instances of `EB_NO_THROW_ADD_MEM` is followed by `EB_CHECK_MEM`, which has the main return

**Comment by 1480c1** [comment]
Although @xuguangxin, do you remember if there was a reason why we have `EB_NO_THROW_MALLOC` instead of just having that expanded inside `EB_MALLOC`? It does not seem to be used anywhere outside of that macro

**Comment by xuguangxin** [comment]
EB_NO_THROW_MALLOC  will not return immediately, you can check the malloc result and release other resources. 

follow example is for EB_NO_THROW_NEW, but the idea is the same.
https://github.com/OpenVisualCloud/SVT-AV1/blob/73793b03cd9d5948b5a317e68a55879eba500044/Source/Lib/Encoder/Globals/EbEncHandle.c#L3177

**Comment by palexander-14** [comment]
> @palexander-14 , we may forgot to wrapper it with SVT_ERROR.
> welcome for a patch, if you are interested .

Here it is.

[0001-fprintf-was-replaced-with-SVT_FATAL-when-memory-allo.patch.zip](https://github.com/OpenVisualCloud/SVT-AV1/files/5054907/0001-fprintf-was-replaced-with-SVT_FATAL-when-memory-allo.patch.zip)

**Comment by xuguangxin** [comment]
could you send a pull request for this, so we can discuss it in  pr

**Comment by 1480c1** [comment]
I think this issue can be closed now

**Comment by palexander-14** [comment]
https://github.com/OpenVisualCloud/SVT-AV1/pull/1407
