### ISSUE TITLE
Why use q-index rather than QP directly?

### ISSUE THREAD

**Issue by Dillon14281118** [OpenVisualCloud/SVT-AV1#1398]
During the quantization process,why use q-index rather than QP directly?

**Comment by hassount** [comment]
Qindex is what the AV1specification uses and it gives more

**Comment by hassount** [comment]
Q index is what is specified in the AV1 spec. Also qindex gives more granularity, for every 1 qp level there are 4 q indices. All in all w index ranges from 0-255 while qp ranges from 0-63
