### ISSUE TITLE
R2R introduced by cd898e8 (PR1416)

### ISSUE THREAD

**Issue by ccccheung** [OpenVisualCloud/SVT-AV1#1442]
I tested for r2r on commit 3df380d and found that there were r2r in some of the 10 bit and 8 bit clips I tested.
We have tracked the issue back to commit cd898e8 (PR1416) and found that reverting that PR fixes the PR.

The R2R showed up across every enc mode

The sample command line that I have tested is this:
```/usr/bin/time --verbose   ./SvtAv1EncApp -enc-mode 0 -w 1920 -h 1080 -bit-depth 10 -fps-num 50000 -fps-denom 1000  -n 60 -q 20  -intra-period  119  -enable-tpl-la 1  -i input.yuv```

Using the same command line with --lp 1 does not show an r2r, so this R2R only appears when the --lp option is not used

**Comment by OmranAbdelkafi** [comment]
Boxing the issue further : Removing the variance check would make the r2r disappear. The variance calculation might be the problem.
