### ISSUE TITLE
[Bug] 2 pass with lp 1/2 failed

### ISSUE THREAD

**Issue by luigi311** [OpenVisualCloud/SVT-AV1#1451]
Running two pass crf with a low lp of 1/2 will cause the encoder to get stuck on frame 29 and not progress from there. This can be reproduced by running the two commands below, the first will run pass 1 and generate the stats file while the second one will actually do the encoding and is what gets stuck on frame 29. Doing a single pass works and generating the stats on the 1st pass works so it appears to be an issue with the 2nd pass mode only.

```bash
SvtAv1EncApp -i ../akiyo_cif.y4m --preset 8 --keyint 56 --irefresh-type 2 --pass 1 --lp 2 --stats akiyo.log -q 20
SvtAv1EncApp -i ../akiyo_cif.y4m --preset 8 --keyint 56 --irefresh-type 2 --pass 2 --lp 2 --stats akiyo.log -q 20 -b akiyo.ivf
```

**Comment by 1480c1** [comment]
I am able to reproduce with a build on latest master on Linux, and the second command doesn't start for me on windows, but it could be it has a > 3 minute init time

**Comment by hassount** [comment]
Can we test this with --keyint 64 instead ?

**Comment by luigi311** [comment]
Looks like 63+ lets it finish

**Comment by hassount** [comment]
> Looks like 63+ lets it finish

ok so this issue is because the gop size having to be a multiple of lookahead.

**Comment by luigi311** [comment]
does keyint automatically choose the correct value for different irefresh-type?

**Comment by hassount** [comment]
> does keyint automatically choose the correct value for different irefresh-type?

it chooses 1 by default, if it's preferred the default could be changed to irefresh-type 2.

**Comment by luigi311** [comment]
I am not sure about changing the default value of irefresh-type, looks like x265 defaults to open gops similar to how this is setup now but anything with adaptive bitrates should be using closed. I think it really depends on who is using it, people that are encoding videos themselves are only really going to keep a single encode so wont really be using ABR technology so they dont need closed gops but companies like netflix and google do use ABR so they would benefit from closed gops, enough to change the default im not sure since the base scripts will probably already have it set to closed similar to how they are encoding x265 currently in netflixes case.

**Comment by luigi311** [comment]
As far as my original question of keyint being set automatically you answered it here 
https://github.com/OpenVisualCloud/SVT-AV1/pull/1455#discussion_r481336434 
with yes you are under the assumption that keyint will be automatically adjusted when you are using open or closed.

**Comment by luigi311** [comment]
I guess the next question is why does it only freeze with LP <= 2 while >= 3 finish the encoding without any issues.

**Comment by hassount** [comment]
> I guess the next question is why does it only freeze with LP <= 2 while >= 3 finish the encoding without any issues.

It will freeze everywhere just getting lucky for the lp cases while it's not freezing, we need to fix the underlying problem
