### ISSUE TITLE
Crash in 2 pass with long non-multiple of 8 resolution clip

### ISSUE THREAD

**Issue by ccccheung** [OpenVisualCloud/SVT-AV1#1477]
I observed a crash in when using the following sample command line for revision d2fb559 

```
./SvtAv1EncApp -enc-mode 3 --passes 2 --irefresh-type 2 -q 20  -intra-period  119  -enable-tpl-la 1  -lp 1 -i  input.y4m --stats output.stat  -b  output.bin 
```

The encoder exits with signal 6 (SIGABRT) due to 
``` realloc(): invalid next size ```
on frame 101

The parameters of the y4m I used are the following:
240 Frames
854x478

**Comment by hassount** [comment]
this should be fixed by #1479
