### ISSUE TITLE
Tag PR's to indicate changing stats or performance

### ISSUE THREAD

**Issue by EwoutH** [OpenVisualCloud/SVT-AV1#159]
(@hassount) Would it be possible to tag PR's with `perf` if they change encoder performance, and `stats-change` if they change encoder output? This way it gets easier to track down performance and efficiency regressions if they may happen.

At Google/aom they also use `STATS_CHANGED` in the commit message if a commit alters output, but I think on GitHub a tag would suffice.

**Comment by hassount** [comment]
@EwoutH 
Sure, I think that's fair. 
Should we just create labels ? for them or adding such to the commit title ? 
Also the commits would be usually of the following types:
1.  Increase the speed with a loss in coding efficiency
2.  Increase the speed without a loss in coding efficiency [lossless or near-lossless]
3.  Decrease the speed with a gain in coding efficiency
4.  Cleanup [No speed nor output change]

Do you have a suggestion on how to label these ? then we can follow it accordingly

**Comment by EwoutH** [comment]
@hassount We could use `S+`, `S-` and `S0` for speed increased, decreases and no change, and `C+`, `C-` and `C0` the same way for coding efficiency. And maybe `S~` and `C~` if it changed, but depends on content or speed setting?

**Comment by hassount** [comment]
Agreed, adding @kylophone @joelsole 
Any thoughts on the above ?

**Comment by EwoutH** [comment]
This is happening now :)
