### ISSUE TITLE
win binary?

### ISSUE THREAD

**Issue by necros2k7** [OpenVisualCloud/SVT-AV1#163]
subj

**Comment by 1480c1** [comment]
https://ci.appveyor.com/project/OpenVisualCloud/SVT-AV1/build/artifacts

**Comment by 1480c1** [comment]
Download the SvtAv1Enc.dll and the .lob and the SvtAv1EncApp.exe and put them in one folder, something like `C:\SVT-AV1` or something memorable and when you want to call the encoder, run 
`C:\SVT-AV1\SvtAv1EncApp.exe ...`

**Comment by 1480c1** [comment]
Is there anything else you may need? If not then this can be closed

**Comment by kylophone** [comment]
Closing, since as pointed out Appveyor provides these.
