### ISSUE TITLE
ffmpeg pipe command throws "av_interleaved_write_frame(): Broken pipe" error

### ISSUE THREAD

**Issue by singhkays** [OpenVisualCloud/SVT-AV1#17]
Trying to encode an input .mkv file using the ffmpeg command below

`kay@svtav1:~/ffmpeg41$ ./ffmpeg -i tears.mkv -nostdin -f rawvideo -pix_fmt yuv420p - | ./SvtAv1EncApp -i stdin -w 1280 -h 534 -q 21 -b tears.bin`

which throws the following error

```
Input #0, matroska,webm, from 'tears.mkv':
  Metadata:
    title           :
    DATE_RELEASED   :
    GENRE           :
    ARTIST          :
    COMPOSER        :
    SYNOPSIS        :
    ENCODER         : Lavf58.20.100
  Duration: 00:01:00.12, start: 0.007000, bitrate: 3126 kb/s
    Stream #0:0(eng): Video: h264 (Main), yuv420p(tv, bt709, progressive), 1280x534 [SAR 1:1 DAR 640:267], 24 fps, 24 tbr, 1k tbn, 180k tbc (default)
    Metadata:
      DURATION        : 00:01:00.124000000
    Stream #0:1(eng): Audio: aac (LC), 44100 Hz, stereo, fltp (default)
    Metadata:
      DURATION        : 00:01:00.007000000
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> rawvideo (native))
Error Instance 1: Only multiple of 8 resolutions are supported
Encoding
Error encoding at channel 1! Check error log file for more details ...
Encoder finished
Output #0, rawvideo, to 'pipe:':
  Metadata:
    title           :
    DATE_RELEASED   :
    GENRE           :
    ARTIST          :
    COMPOSER        :
    SYNOPSIS        :
    encoder         : Lavf58.20.100
    Stream #0:0(eng): Video: rawvideo (I420 / 0x30323449), yuv420p, 1280x534 [SAR 1:1 DAR 640:267], q=2-31, 196853 kb/s, 24 fps, 24 tbn, 24 tbc (default)
    Metadata:
      DURATION        : 00:01:00.124000000
      encoder         : Lavc58.35.100 rawvideo
**av_interleaved_write_frame(): Broken pipe**
    Last message repeated 83 times
**Error writing trailer of pipe:: Broken pipe**
frame=   84 fps=0.0 q=-0.0 Lsize=   84105kB time=00:00:03.50 bitrate=196853.8kbits/s dup=83 drop=0 speed=  99x
video:84105kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
Conversion failed!
```

**Comment by singhkays** [comment]
nm, read the error closer and figured out height of the input video wasn't a multiple of 8

**Comment by kylophone** [comment]
Good, thanks.

**Comment by RR2301** [comment]
HI 
I am getting a following error. Can some one suggest why the conversion is failing..

**Command** 
`
pi@raspberrypi:~ $ ffmpeg  -thread_queue_size 512 -rtsp_transport tcp -i "rtsp://home:HomeXXXX@192.168.1.XX:554/cam/realmonitor?channel=4&subtype=0" -f lavfi -i aevalsrc=0 \-c:a libmp3lame  http://127.0.0.1:8090/video.ffm 
'
**Result**

`
'ffmpeg version 3.2.14-1~deb9u1+rpt1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --prefix=/usr --extra-version='1~deb9u1+rpt1' --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-omx-rpi --enable-mmal --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --arch=armhf --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, rtsp, from 'rtsp://home:HoXXXXX@192.168.1.XX:554/cam/realmonitor?channel=4&subtype=0':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.298000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 2304x1296 [SAR 1:1 DAR 16:9], 20 fps, 20 tbr, 90k tbn, 40 tbc
Input #1, lavfi, from 'aevalsrc=0':
  Duration: N/A, start: 0.000000, bitrate: 2822 kb/s
    Stream #1:0: Audio: pcm_f64le, 44100 Hz, mono, dbl, 2822 kb/s
[swscaler @ 0x73c440] deprecated pixel format used, make sure you did set range correctly
[libvpx @ 0x732df0] v1.6.1
Output #0, ffm, to 'http://127.0.0.1:8090/video.ffm':
  Metadata:
    title           : Media Server
    creation_time   : now
    encoder         : Lavf57.56.101
    Stream #0:0: Audio: vorbis (libvorbis), 22050 Hz, mono, fltp, 64 kb/s
    Metadata:
      encoder         : Lavc57.64.101 libvorbis
    Stream #0:1: Video: vp8 (libvpx), yuv420p, 720x486 [SAR 6:5 DAR 16:9], q=10-42, 400 kb/s, 20 fps, 1000k tbn, 30 tbc
    Metadata:
      encoder         : Lavc57.64.101 libvpx
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 800000 vbv_delay: -1
Stream mapping:
  Stream #1:0 -> #0:0 (pcm_f64le (native) -> vorbis (libvorbis))
  Stream #0:0 -> #0:1 (h264 (native) -> vp8 (libvpx))
Press [q] to stop, [?] for help
av_interleaved_write_frame(): Connection reset by peer0.03 bitrate=1966.0kbits/s dup=1 drop=0 speed=0.0211x    

`
**Error writing trailer of http://127.0.0.1:8090/video.ffm: Connection reset by peerframe=    2 fps=1.2 q=0.0 Lsize=      32kB time=00:00:00.03 bitrate=7864.2kbits/s dup=1 drop=0 speed=0.02x    
video:21kB audio:0kB subtitle:0kB other streams:0kB global headers:4kB muxing overhead: 53.243229%**
Conversion failed!
`
