### ISSUE TITLE
No way to jump in the video at any given time 

### ISSUE THREAD

**Issue by j-mas** [OpenVisualCloud/SVT-AV1#170]
After encoding video with SvtAv1EncApp in .ivf and merging with opus audio with FFMPEG no fast-forwarding and rewinding as well as jumping in VLC and MPC possible.

**Comment by jbeich** [comment]
Also reported in https://github.com/OpenVisualCloud/SVT-AV1/issues/33#issuecomment-469924934.

**Comment by j-mas** [comment]
@hassount 

With setting intra-refresh-type 2 it works! 
No Problems to jump forward or backward.
You can close the issue #170.
Thank you very much!

**Comment by hassount** [comment]
@j-mas 
Glad to hear that :)

**Comment by ksuhiyp** [comment]
@hassount I am using the plugin, how can i set intra-refresh-type 2 in ffmpeg?

**Comment by jbeich** [comment]
`SvtAv1EncApp ... -irefresh-type 2` is probably `ffmpeg ... -c:v libsvt_av1 -forced-idr true`.
https://github.com/OpenVisualCloud/SVT-AV1/blob/eb2b6551d6559c039b8e1036167f51351e9870ab/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch#L303
```
$ ffmpeg -hide_banner -h encoder=libsvt_av1 | fgrep idr
  -forced-idr        <boolean>    E..V..... If forcing keyframes, force them as IDR frames. (default false)
```
