### ISSUE TITLE
**Encoding with rc 2 always stopped at frame 1982  !!!

### ISSUE THREAD

**Issue by j-mas** [OpenVisualCloud/SVT-AV1#175]
**Encoding with rc 2 always stopped at frame 1982  !!!
Encoding with the SvtAv1EncApp!**

Number of logical cores available: 28
Number of PPCS 45
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 7
SVT [config]: EncoderBitDepth / CompressedTenBitFormat                          : 8 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1920 / 1080
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 24000 / 1001 / 16 / 1
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 3 / 0 / 2
SVT [config]: RCMode / TargetBitrate / LookaheadDistance / SceneChange          : VBR / 1100000 / 15 / 0
-------------------------------------------
Encoding      1982
C:\>

_Originally posted by @j-mas in https://github.com/OpenVisualCloud/SVT-AV1/pull/174#issuecomment-472219584_

**Comment by anaghdin** [comment]
Hi Could you share the CLI that you used? I am not able to reproduce the deadlock?Thanks

**Comment by anaghdin** [comment]
I managed to reproduce the problem and pushed a patch to fix it. Thanks for reporting.

**Comment by j-mas** [comment]
Thank you!
