### ISSUE TITLE
Semaphore issue on MacOS

### ISSUE THREAD

**Issue by mafonsoN** [OpenVisualCloud/SVT-AV1#178]
This error happens very often in Mac OS even with the latest commit f2a87ad. Not sure where the problem is. Any easy fix?

```
errno: 28
Encoding          
Could not allocate enough memory for channel 1
```

**Comment by 1480c1** [comment]
Can you put the full command line? And if possible information on the input file (height width etc)

**Comment by mafonsoN** [comment]
This crash cannot be reproduced using the same command line since it only happens after running the encoder a few times in Mac OS (even using the same config parameters and input). 

Anyways, I was encoding a video with CIF resolution (352x288), using the command line:

./SvtAv1EncApp -i akiyo_cif.y4m -o akiyo_cif_SVT-AV1_cq40.yuv -q 40 -b akiyo_cif_SVT-AV1_cq40.bin -intra-period 31 -lad 8

**Comment by 1480c1** [comment]
Can you check ran usage and see if the enc app is properly releasing memory after it finishes?

**Comment by kylophone** [comment]
I've seen this from time to time too. I believe the message is a red herring, it may actually have something to do with not having enough file descriptors for semaphores.

**Comment by 1480c1** [comment]
If talking about semaphores and Mac, Mac doesn't support sem_init and destroy.

**Comment by 1480c1** [comment]
They are there, but labeled as depreciated. Mac uses Mach sem or something like that

**Comment by 1480c1** [comment]
Either that or sysv, can't remember

**Comment by jbeich** [comment]
@1480c1, macOS uses `sem_open`/`sem_close` instead of `sem_init`/`sem_destroy`.  Are those buggy/unsupported as well?
https://github.com/OpenVisualCloud/SVT-AV1/blob/f0d0768813fc1b7148ea15507589b20bc192305f/Source/Lib/Codec/EbThreads.c#L207-L216
https://github.com/OpenVisualCloud/SVT-AV1/blob/f0d0768813fc1b7148ea15507589b20bc192305f/Source/Lib/Codec/EbThreads.c#L271-L272

**Comment by 1480c1** [comment]
This should be the correct ones, however I think apple was picky on that you have to sem_unlink it before opening it.

**Comment by 1480c1** [comment]
Maybe it's because sem_close doesn't actually destroy them, and so the files don't actually go away, so you end up with orphaned semaphores?

**Comment by 1480c1** [comment]
So add a sem_unlink after sem_close I think. Currently not anywhere near my computers to be able to test anything that would require a good amount of attention.

**Comment by 1480c1** [comment]
<https://bugs.chromium.org/p/nativeclient/issues/detail?id=686>
It seems that chromium had a similar problem in 2010, the reason was that using only sem_open and sem_close did not make the named semaphores go away, contributing to the global semaphore limit in mac.

**Comment by kylophone** [comment]
> kylophone changed the title Error with memory allocation Semaphore issue on MacOS just now

I've retitled this issue.

**Comment by Gentoli** [comment]
I have a similar issue without having to run the encoder a few times.
The same command works under a Ubuntu VM.
command:
```bash
./SvtAv1EncApp -i ~/test.yuv -w 1280 -h 720 -b test2.bin
```
output:
``` log
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:	SVT-AV1 Encoder Lib v0.4.0
SVT [build]  :	GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.3)	 64 bit
LIB Build date: Apr  9 2019 16:09:39
-------------------------------------------
Number of logical cores available: 12
Number of PPCS 66
------------------------------------------- 
SVT [config]: Main Profile	Tier (auto)	Level (auto)	
SVT [config]: EncoderMode 							: 8 
SVT [config]: encoder_bit_depth / compressed_ten_bit_format				: 8 / 0 
SVT [config]: source_width / source_height					: 1280 / 720 
SVT [config]: frame_rate / Gop Size						: 30 / 32 
SVT [config]: hierarchical_levels / BaseLayerSwitchMode / pred_structure		: 4 / 0 / 2 
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange			: CQP / 50 / 33 / 0 
------------------------------------------- 
errno: 24
Encoding          
Could not allocate enough memory for channel 1
Encoder finished
```

I have the issue on c06ce99 and master(38818d95ec77d8695c3eac726baaae7c820061cf).

**Comment by 1480c1** [comment]
Could you change the fprint to perror so that the text will be displayed instead of the number? Also when it shows the error, can you run `sudo zprint semaphore`?

**Comment by Gentoli** [comment]
perror:
```Too many open files```
```bash
$ sudo zprint semaphore
                            elem         cur         max        cur         max         cur  alloc  alloc    
zone name                   size        size        size      #elts       #elts       inuse   size  count    
-------------------------------------------------------------------------------------------------------------
semaphores                    96        152K       5332K       1621       56874        1490     8K     85  C
$ sysctl kern.maxfiles kern.maxfilesperproc
kern.maxfiles: 49152
kern.maxfilesperproc: 24576
```

**Comment by 1480c1** [comment]
Are you running through ssh?

**Comment by 1480c1** [comment]
Can you run `ulimit -n` and show the max amount of open files available? I had that problem when I tried with SVT-HEVC before and I noticed that it only allowed 256 files for me.

**Comment by Gentoli** [comment]
no

**Comment by 1480c1** [comment]
<https://www.macobserver.com/tips/deep-dive/evade-macos-many-open-files-error-pushing-limits/>

Under "Configuring Your New File Limits" with the `sudo nano /Library/LaunchDaemons/limit.maxfiles.plist`
That's how I circumvented the problem.

**Comment by 1480c1** [comment]
It might be necessary to limit the amount of semaphores for macOS or point macOS users to that issue for ssh users since for debian, the default is 1024, but for macOS, the default is 256

**Comment by Gentoli** [comment]
Changing to ```ulimit -n 1000``` made it work.
It should have some error message about increasing the file descriptors counts.

**Comment by 1480c1** [comment]
Remember that using ulimit is limited to that shell only and will not be applied next time you use it

**Comment by 1480c1** [comment]
This can probably be closed with <https://github.com/OpenVisualCloud/SVT-AV1#linux-operating-systems-64-bit> note about macOS

**Comment by kylophone** [comment]
I believe there is still an issue with semaphores not being cleaned up. Will investigate.

**Comment by rbultje** [comment]
@EwoutH asked me to leave a comment here.

I did the commands from that note (`sudo sysctl -w kern.maxfiles=20480` as well as `sudo launchctl limit maxfiles 65536 200000`) and it still crashes for me with the same error, on Mac as well as on an Amazon T2 machine.

By comparison, I can get it to work a little bit on Amazon m4xlarge machines, but there it dies a bit later with:

```
SVT-AV1 Encoder
Error found when reading the y4m file parameters.
Error in configuration, could not begin encoding! ...
Run SvtAv1EncApp -help for a list of options
Encoder finished
height not found in y4m header
SvtAv1EncApp -i stdin -b out.ivf -rc 0 -q 20 -intra-period 120 -lp 1 -enc-mode 1
```

This is a 1080p30 8-bit version of [RollerCoaster](https://media.xiph.org/video/derf/Chimera/Netflix_RollerCoaster_4096x2160_60fps_10bit_420.y4m); the first line of the y4m is `YUV4MPEG2 W1920 H1080 F30:1 Ip A1:1 C420jpeg XYSCSS=420JPEG`. I'm using 6fd564611bdb48a2a6d2c7b90a91b4b1bdbe74b9.

**Comment by chenjin3** [comment]
> Changing to `ulimit -n 1000` made it work.
> It should have some error message about increasing the file descriptors counts.

It works.

**Comment by hassount** [comment]
@mafonsoN @kylophone 
Is this still an issue or has it been addressed ?

**Comment by hassount** [comment]
Closing this
