### ISSUE TITLE
CQP mode does not honor QP value specified through command line

### ISSUE THREAD

**Issue by PDX-Runner** [OpenVisualCloud/SVT-AV1#179]
command line:
SvtAv1EncApp.exe -i D:\YUVs\4K001_960x544.yuv -b 4K001_960x544.ivf -w 960 -h 544 -enc-mode 0 -fps 60.0 -lad 25 -rc 0 -q 22 -min-qp 22 -max-qp 22 -n 60

try to specify CQP mode using QP=22 for all frames, however, the encoded bit streams have different QPs for all frames.

**Comment by hassount** [comment]
CQP mode uses a qp scaling functionality that assigns different frame qps based on their hierarchical positioning to get better coding efficiencies. 
you can force CQP on all pictures by using the qp file functionality:
```
UseQpFile                       : 0                       # When set to 1, overwrite the picture qp assignment using qp values in QpFile
QpFile                          : SVTQPFile.txt           # File with rows of QP values corresponding to QP values for each frame
```
set UseQpFile  to 1 and create a .txt file that contains only one qp value in one line. that should assign the qp value to every frame in the queue. Please let me know if this does not work.

**Comment by PDX-Runner** [comment]
if we specify -q, -min-qp and -max-qp, then it is expected that all QP used should be within the min-qp and max-qp range, even encoder can changed it based on frame type and temporal layer. what I am seeing is that the encoder seems completely ignore the qp value specified through command line.

**Comment by zyue128** [comment]
Hey, I am wondering if this (using .txt) is still the only way to fix the frame level QP values? Thank you.

**Comment by hassount** [comment]
> Hey, I am wondering if this (using .txt) is still the only way to fix the frame level QP values? Thank you.

Yes

**Comment by zyue128** [comment]
Thank you so much.

**Comment by hassount** [comment]
the qp file should address this request
