### ISSUE TITLE
Code style guidelines

### ISSUE THREAD

**Issue by THETCR** [OpenVisualCloud/SVT-AV1#18]
The current guideline seems inadequate/incomplete to me. 
https://github.com/OpenVisualCloud/SVT-AV1/blob/master/STYLE.md

Is it preferable to add  ,for example, a ".clang-format" file?

**Comment by kylophone** [comment]
A `.clang-format` file would be good. It would at least allow us to lint new commits via CI. You'll notice that the codebase is sort of a mash-up right now, and that there's a lot of work to do if we want to actually conform to `STYLE.md`. 

@THETCR, patches are welcome. If you'd like to put together a `.clang-format` file that matches `STYLE.md` that'd be a good start.

**Comment by THETCR** [comment]
Sure, I would like to contribute. 

With a `.clang-format` file it will become easier to conform to `STYLE.md` since the codebase can then be refactored.

**Comment by joelsole** [comment]
A .clang-format file is under the test folder (to be moved?). We can close this issue once that file is aligned with STYLE.md.

**Comment by 1480c1** [comment]
Is the current .clang-format aligned properly with the current style @hassount @chouquette? Can this issue be closed now?

**Comment by hassount** [comment]
I believe the file has now been added, we might need to run a cleanup later, but I believe this issue has been resolved as to the existence of the clang-format file
