### ISSUE TITLE
In rare cases, it can not encode normally.

### ISSUE THREAD

**Issue by f11894** [OpenVisualCloud/SVT-AV1#182]
SVT-AV1 39aad812
Windows 10 64bit ver. 10.0.18356.1
Ryzen 2400G

input video
https://media.xiph.org/video/derf/
pedestrian_area_1080p25.y4m

output video
![名称未定-1](https://user-images.githubusercontent.com/16046279/54469453-8073e680-47db-11e9-8d59-cf28e08ec028.png)
https://www.dropbox.com/s/xoebscchllu2efy/pedestrian_area_1080p25_SVT-AV1_e7_q50.ivf?dl=0

Commandline
```
ffmpeg.exe -y -loglevel quiet -i pedestrian_area_1080p25.y4m -an -nostdin -f rawvideo -pix_fmt yuv420p - | SvtAv1EncApp.exe -i stdin -enc-mode 7 -q 50 -n 375 -w 1920 -h 1080 -fps-num 25 -fps-denom 1 -b pedestrian_area_1080p25_SVT-AV1_e7_q50.ivf
```

log
```
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.4.0
SVT [build]  :  Visual Studio 2017 64 bit
LIB Build date: Mar 16 2019 00:52:53
-------------------------------------------
Number of logical cores available: 8
Number of PPCS 41
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 7
SVT [config]: EncoderBitDepth / CompressedTenBitFormat                          : 8 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1920 / 1080
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 25 / 1 / 32 / 1
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 50 / 33 / 0
-------------------------------------------
Encoding       375
SUMMARY --------------------------------- Channel 1  --------------------------------
Total Frames            Frame Rate              Byte Count              Bitrate
         375            25.00 fps                  2270794              1211.09 kbps


Channel 1
Average Speed:          4.660 fps
Total Encoding Time:    80464 ms
Total Execution Time:   81732 ms
Average Latency:        14731 ms
Max Latency:            19429 ms
Encoder finished
```

P.S. I use google translation.

**Comment by 1480c1** [comment]
I am currently on mobile and can't play that video, what is exactly wrong? Looking at the picture, nothing seems wrong.

What is your language?

**Comment by f11894** [comment]
The difference is easy to understand when compared with the source video.
The right part of the image is abnormal.
差はSourceの動画と比較をするとわかりやすいです。
映像の右端の部分が異常です。

![Source](https://user-images.githubusercontent.com/16046279/54470342-78bb3e80-47e9-11e9-922d-98e6eceb35fc.png)

> What is your language?

My native language is Japanese.

**Comment by 1480c1** [comment]
ええと、だったら、もうすぐ家につくので、その時にsourceを見れるので。いまsource映画まだ見られないので。sourceのframe番号は何ですか?

**Comment by 1480c1** [comment]
そうゆう意味ですか、やっと見えました。右にある細い線のこと。Githubのbackgroundに混ざっていました。

**Comment by 1480c1** [comment]
![image](https://user-images.githubusercontent.com/8345542/54472071-7b3d7a00-4790-11e9-9546-c5df9a48edac.png)

見たところ、一個のスライスは左から右に動かされましたそうです。FFmpegかstdinかivfのcodeかどちの方が悪いのかはわかりません。

I can reproduce the same problem, it seems that the video is not inputted properly or not written properly and a slice from the left side goes to the right. I'm not sure if it is FFmpeg, stdin input code, or ivf output code that is the problem.

**Comment by f11894** [comment]
This problem no longer occurs if you output to a yuv file using FFpmeg and then encode it.
However, SVT-HEVC is weird because it can be correctly encoded even with pipe input.
FFpmegでyuvファイルに出力してからエンコードするようにしたことろ、この問題は発生しなくなりました。
しかし、SVT-HEVCはパイプ入力でも正常にエンコード出来ているので不可解です。

**Comment by ROYduan** [comment]
code bug with y4m inputfile

**Comment by hassount** [comment]
#235  may address this issue, can some one please check?

**Comment by f11894** [comment]
> #235 may address this issue, can some one please check?

When I tried it, I was able to encode correctly.
I think the issue has been solved.
私が試してみたところ、正常にエンコードできるようになっています。
問題は解決したように思います。
