### ISSUE TITLE
能否支持下linux全静态编译

### ISSUE THREAD

**Issue by zhongyizengzy** [OpenVisualCloud/SVT-AV1#183]
add support for static binaries without libraries
to build SvtAv1EncApp without .so and .a

**Comment by 1480c1** [comment]
https://github.com/OpenVisualCloud/SVT-AV1/pull/67
If I am reading correctly, you are asking for static build?

**Comment by zhongyizengzy** [comment]
yes，i need a static executable build

**Comment by hassount** [comment]
#39 duplicate

**Comment by kylophone** [comment]
Closing for now, since this is already being tracked in #39.
