### ISSUE TITLE
add support for static binaries without libraries 

### ISSUE THREAD

**Issue by zhongyizengzy** [OpenVisualCloud/SVT-AV1#184]
add support for static binaries without libraries
for the ability to build SvtAv1EncApp without .so and .a
i need a static svtav1encapp file without any .so or .a file for uploading to a encoder assessment system on linux ubuntu 16.x

**Comment by hassount** [comment]
this is a duplicate for #39

**Comment by kylophone** [comment]
Closing, we will track this in issue #39.
