### ISSUE TITLE
[AV1 ffmpeg-plugin] the number of frames encoded by ffmpeg libsvt_av1 encoder is not the same with the number of input YUV frames.

### ISSUE THREAD

**Issue by waterflag0614** [OpenVisualCloud/SVT-AV1#224]
The number of encoding frames is correct from the following LOG information.
ffmpeg -r 25 -video_size 1280x720 -pixel_format yuv420p -f rawvideo -i videoconf1_720p_60.yuv  -c:v libsvt_av1 -qp 31 -preset 8 -r 25  -vframes 300 out3.ivf
'''
**frame=  300** fps=5.8 q=-0.0 Lsize=    1691kB time=00:00:11.68 bitrate=1185.7kbits/s speed=0.227x
video:1687kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.226729%
'''
but the number of decoding frames that above encoding stream is as input  is not the same with input frames.
ffmpeg -i out3.ivf  -pixel_format yuv420p  -f rawvideo out.yuv
'''
**frame=  299** fps=173 q=-0.0 Lsize=  403650kB time=00:00:11.96 bitrate=276480.0kbits/s dup=148 drop=0 speed=6.93x
video:403650kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
'''
SvtAv1EncApp encoded the same YUV file, the above issue is not reproduced.
SvtAv1EncApp -i videoconf1_720p_60.yuv -w 1280 -h 720 -fps-num 25 -fps-denom 1 -enc-mode 8 -latency-mode 0 -irefresh-type 2 -q 31 -n 300 -b out.ivf

There is not restrictions on input YUV file.

**Comment by hassount** [comment]
@jsunintel

**Comment by xuguangxin** [comment]
I belive this fixed. @waterflag0614 , could you help double confirm it?
thanks

**Comment by hassount** [comment]
Closing, please open a new issue if need be
