### ISSUE TITLE
Basic x86-64 build fails in COMMON_C_DEFAULT

### ISSUE THREAD

**Issue by krcroft** [OpenVisualCloud/SVT-AV1#226]
As of April 16, 2019 Master Branch, reproduce with:

```
cd /dev/shm
git clone --depth 1 https://github.com/OpenVisualCloud/SVT-AV1
cd SVT-AV1/Build
cmake .. && make 

```

Result:

    [ 51%] Linking C static library ../../../../lib/libCOMMON_C_DEFAULT.a
    [ 51%] Built target COMMON_C_DEFAULT
    Scanning dependencies of target COMMON_ASM_SSE2
    [ 51%] Building ASM_NASM object Source/Lib/Common/ASM_SSE2/CMakeFiles/COMMON_ASM_SSE2.dir/EbPictureOperators_SSE2.asm.o
    /dev/shm/SVT-AV1/Source/Lib/Common/ASM_SSE2/EbPictureOperators_SSE2.asm:6: fatal: unable to open include file `x64inc.asm'
    Source/Lib/Common/ASM_SSE2/CMakeFiles/COMMON_ASM_SSE2.dir/build.make:62: recipe for target 'Source/Lib/Common/ASM_SSE2/CMakeFiles/COMMON_ASM_SSE2.dir/EbPictureOperators_SSE2.asm.o' failed
    make[2]: *** [Source/Lib/Common/ASM_SSE2/CMakeFiles/COMMON_ASM_SSE2.dir/EbPictureOperators_SSE2.asm.o] Error 1
    CMakeFiles/Makefile2:1124: recipe for target 'Source/Lib/Common/ASM_SSE2/CMakeFiles/COMMON_ASM_SSE2.dir/all' failed
    make[1]: *** [Source/Lib/Common/ASM_SSE2/CMakeFiles/COMMON_ASM_SSE2.dir/all] Error 2
    Makefile:140: recipe for target 'all' failed
    make: *** [all] Error 2

**Comment by 1480c1** [comment]
I'm going to assume that it's because you are using nasm. The CMakeList does not have the necessary logic to force switch to yasm (simple, but haven't been implemented) so you will need to use `-DCMAKE_ASM_NASM_COMPILER=yasm` when using cmake.

**Comment by krcroft** [comment]
That fixed it; thank you @1480c1 !
