### ISSUE TITLE
ffmpeg-plugin: the value of RC mode in ffmpeg-plugin is inconsistent with the value in svt-av1 library.

### ISSUE THREAD

**Issue by waterflag0614** [OpenVisualCloud/SVT-AV1#228]
The values of RC mode are the following in SVT-AV1 library.
CQP: 0
ABR: 1
VBR: 2
CVBR: 3
The values of RC mode are the following in ffmpeg-plugin.
CQP: 0
VBR: 1

**Comment by jsunintel** [comment]
Where did you get the name ABR from? In the SVT native APP, 1 & 2 are both named VBR, and 3 is constraint VBR. I asked around but no one knows what that was, or the difference between 2 VBR.

@hassount  could you please let someone give us such information? Updating that in the docs is even better.

**Comment by gnafuthegreat** [comment]
@jsunintel I'm guessing "ABR" comes from PR #199.  At least, that's what I thought of when I was reading @waterflag0614's initial comment.  Maybe not implemented yet, but it seems from that PR that it will eventually be "RC mode 1".

**Comment by hassount** [comment]
RC modes 1 and 2 will be merged then we'll have a VBR and a CVBR

**Comment by waterflag0614** [comment]
./Config/Sample.cfg:RateControlMode                 : 0             # Rate control mode (0: OFF(CQP), 1: ABR, 2: VBR, 3: CVBR)

SvtAv1EncApp -i ~/mntstream/mediasdk_streams/YUV/videoconf1_720p_60.yuv -w 1280 -h 720 -fps-num 25 -fps-denom 1 -enc-mode 8 -latency-mode 0 -irefresh-type 2 -rc 3 -n 100 -b out4.ivf

Option '-rc' is set to 0, 1, 2 and 3.
RCMode information as following.
"""
CQP / 31 / 33 / 0
VBR / 7000000 / 32 / 0
VBR / 7000000 / 32 / 0
Constraint VBR / 7000000 / 32 / 0
"""

**Comment by hassount** [comment]
RC option 1 is now disabled and RC modes 1 and 2 will be merged into one mode soon.

**Comment by jsunintel** [comment]
> 
> 
> RC option 1 is now disabled and RC modes 1 and 2 will be merged into one mode soon.

Thanks for the information. And how about RC3 (CVBR)? Is there any doc introducing what CVBR is?

**Comment by jsunintel** [comment]
@hassount any updates on this? When will RC1 and RC2 get merged and the VBR fully work? And how about RC3? Could you share some information on what it's and how it's supposed to work?

**Comment by hassount** [comment]
@jsunintel 
sorry for the late reply. yes RC3 remains, CVBR stands for Constrained Variable Bit Rate. This mode restricts the encoder to achieve the target bitrate at every gop but can vary within the gop. The VBR can used bitrates from one gop to the other.
still don't have a timeline on the merge, but we'll target doing it as soon as possible.

**Comment by jsunintel** [comment]
> 
> 
> @jsunintel
> sorry for the late reply. yes RC3 remains, CVBR stands for Constrained Variable Bit Rate. This mode restricts the encoder to achieve the target bitrate at every gop but can vary within the gop. The VBR can used bitrates from one gop to the other.
> still don't have a timeline on the merge, but we'll target doing it as soon as possible.

Please give us a heads-up when it's merged. And for CVBR, is it ready to get exposed in ffmpeg plugin and get validated?

**Comment by hassount** [comment]
yes RC 3 should be ready for use

**Comment by hassount** [comment]
this can now change, -rc 1 and rc 2
