### ISSUE TITLE
Tag minor release?

### ISSUE THREAD

**Issue by eclipseo** [OpenVisualCloud/SVT-AV1#233]
Hi,

I don't know the roadmap for SVT-AV1 but it would be nice to tag a minor release for Linux distribution integrators to start packaging it.

Thanks.

**Comment by 1480c1** [comment]
Related: #29

**Comment by hassount** [comment]
@eclipseo 
we'll make sure this is done more often now, can we close this issue ?

https://github.com/OpenVisualCloud/SVT-AV1/releases

**Comment by joelsole** [comment]
Yes, looks like
