### ISSUE TITLE
i've just downloaded SVT-AV1, created visual sln-project. However, i can't compile it, i obtain the following error: 

### ISSUE THREAD

**Issue by shevachr** [OpenVisualCloud/SVT-AV1#236]

**Comment by shevachr** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3721	The command ""C:/Windows/System32/yasm.exe" -o "COMMON_ASM_SSE2.dir\Release\EbPictureOperators_SSE2.obj" -fwin64 -I"C:\Tools\SVT-AV1-master\Source\API\\" -I"C:\Tools\SVT-AV1-master\Source\Lib\Common\Codec\\" -I"C:\Tools\SVT-AV1-master\Source\Lib\Common\C_DEFAULT\\" -I"C:\Tools\SVT-AV1-master\Source\Lib\Common\ASM_SSE2\\" -D"CMAKE_INTDIR="Release"" -D"WIN64"  "C:\Tools\SVT-AV1-master\Source\Lib\Common\ASM_SSE2\EbPictureOperators_SSE2.asm"" exited with code 1.	COMMON_ASM_SSE2	C:\Program Files\CMake\share\cmake-3.13\Templates\MSBuild\nasm.targets	33

**Comment by shevachr** [comment]
i use Visual Studio 2017

**Comment by 1480c1** [comment]
Could you provide more information? There is currently not enough information to understand what's wrong other than yasm failing

**Comment by 1480c1** [comment]
Also, do you actually have yasm under system32?

**Comment by shevachr** [comment]
i took yasm from
http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe
This is 64-bits version, i put the program under "system32" but it should
not make a problem

**Comment by shevachr** [comment]
i failed to generate common_asm_sse2 library:
C:\Program
Files\CMake\share\cmake-3.13\Templates\MSBuild\nasm.targets(33,5): error
MSB3721: The command ""C:/Windows/System32/yasm.exe" -o
"COMMON_ASM_SSE2.dir\Release\EbPictureOperators_SSE2.obj" -fwin64
-I"C:\Tools\SVT-AV1-master\Source\API\\"
-I"C:\Tools\SVT-AV1-master\Source\Lib\Common\Codec\\"
-I"C:\Tools\SVT-AV1-master\Source\Lib\Common\C_DEFAULT\\"
-I"C:\Tools\SVT-AV1-master\Source\Lib\Common\ASM_SSE2\\"
-D"CMAKE_INTDIR="Release"" -D"WIN64"
"C:\Tools\SVT-AV1-master\Source\Lib\Common\ASM_SSE2\EbPictureOperators_SSE2.asm""
exited with code 1.

**Comment by shevachr** [comment]
i started from the beginning, there is only one problem " Looking for
pthread.h - not found ", however i don't think it's related to yasm:

C:\Tools\SVT-AV1-master\Build\windows>generate_vs17.bat

C:\Tools\SVT-AV1-master\Build\windows>cmake ../.. -G "Visual Studio 15 2017
Win64" -DCMAKE_ASM_NASM_COMPILER="yasm.exe"
-DCMAKE_INSTALL_PREFIX=C:\svt-encoders
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
-- The C compiler identification is MSVC 19.16.27025.1
-- The CXX compiler identification is MSVC 19.16.27025.1
-- The ASM_NASM compiler identification is YASM
-- Found assembler: C:/Windows/System32/yasm.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual
Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual
Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual
Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual
Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: C:/Python27/python.exe (found version "2.7.15")
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Tools/SVT-AV1-master/Build/windows

**Comment by shevachr** [comment]
Then i open Visual Studio 2017 and build COMMON_ASM_SSE2:

>------ Rebuild All started: Project: COMMON_ASM_SSE2, Configuration:
Release x64 ------
2>Building Custom Rule
C:/Tools/SVT-AV1-master/Source/Lib/Common/ASM_SSE2/CMakeLists.txt
2>CMake does not need to re-run because
C:/Tools/SVT-AV1-master/Build/windows/Source/Lib/Common/ASM_SSE2/CMakeFiles/generate.stamp
is up-to-date.
2>Assembling EbPictureOperators_SSE2.asm
2>C:\Program
Files\CMake\share\cmake-3.13\Templates\MSBuild\nasm.targets(33,5): error
MSB3721: The command ""C:/Windows/System32/yasm.exe" -o
"COMMON_ASM_SSE2.dir\Release\EbPictureOperators_SSE2.obj" -fwin64
-I"C:\Tools\SVT-AV1-master\Source\API\\"
-I"C:\Tools\SVT-AV1-master\Source\Lib\Common\Codec\\"
-I"C:\Tools\SVT-AV1-master\Source\Lib\Common\C_DEFAULT\\"
-I"C:\Tools\SVT-AV1-master\Source\Lib\Common\ASM_SSE2\\"
-D"CMAKE_INTDIR="Release"" -D"WIN64"
"C:\Tools\SVT-AV1-master\Source\Lib\Common\ASM_SSE2\EbPictureOperators_SSE2.asm""
exited with code 1.
2>Done building project "COMMON_ASM_SSE2.vcxproj" -- FAILED.
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========

**Comment by shevachr** [comment]
Ooops, i've forgotten to clean cache

C:\Tools\SVT-AV1-master\Build\windows>generate_vs17.bat

C:\Tools\SVT-AV1-master\Build\windows>cmake ../.. -G "Visual Studio 15 2017
Win64" -DCMAKE_ASM_NASM_COMPILER="yasm.exe"
-DCMAKE_INSTALL_PREFIX=C:\svt-encoders
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
-- The C compiler identification is MSVC 19.16.27025.1
-- The CXX compiler identification is MSVC 19.16.27025.1
-- The ASM_NASM compiler identification is YASM
-- Found assembler: C:/Windows/System32/yasm.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual
Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual
Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual
Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual
Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: C:/Python27/python.exe (found version "2.7.15")
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Tools/SVT-AV1-master/Build/windows

However the same error appears

**Comment by Chipcraft** [comment]
Seems to be an issue related to YASM itself.

Worked fine on the latest, self built (Mingw64 GCC 8.1) binary.

https://github.com/yasm/yasm

**Comment by hassount** [comment]
closing this as it seems to be addressed
