### ISSUE TITLE
Sample.cfg format mistmach

### ISSUE THREAD

**Issue by murillo128** [OpenVisualCloud/SVT-AV1#237]
This https://github.com/OpenVisualCloud/SVT-AV1/commit/33b0e1c7da2d2af7cf242daada1a44330c5966ec#r33323674 changed the config file params from CamelCase to snake_case, but the https://github.com/OpenVisualCloud/SVT-AV1/blob/master/Config/Sample.cfg has not been updated.

So either the change was not intended to affect the config attribute names or the sample config has not been updated accordingly.

**Comment by hassount** [comment]
@murillo128 Thank you for flagging this. 
This was not intentional and is now addressed in #235

**Comment by murillo128** [comment]
fixed

**Comment by adaria** [comment]
Sample.cfg drifted away from config parameters format again

**Comment by adaria** [comment]
addressed by #1135
