### ISSUE TITLE
[SVT-AV1]SvtAv1EncApp is killed when encoding to 320+ frames if run 2 channels at the same time.

### ISSUE THREAD

**Issue by GuCaixuan** [OpenVisualCloud/SVT-AV1#240]
Dear,
When we use the SVT-AV1 App with commitID bef6750 which is from Github Master to do encoding with below command, SvtAv1EncApp is killed when encoding to 320+ frames.
SvtAv1EncApp -nch 2 -i Netflix_FoodMarket2_4096x2160_10bit_60Hz_P420.yuv Cactus_10bit_1920x1080_50Hz_P420.yuv -b multichannel_test_M4_Netflix_FoodMarket2_4096x2160_10bit_60Hz_P420_Q31_1.bin multichannel_test_M4_Cactus_10bit_1920x1080_50Hz_P420_Q31.bin -errlog MultiChannel_M4_Netflix_FoodMarket2_4096x2160_10bit_60Hz_P420_Q31.errlog MultiChannel_M4_Cactus_10bit_1920x1080_50Hz_P420_Q31.errlog -w 4096 1920  -h 2160 1080 -bit-depth 10 10 -fps 60 50 -intra-period 55 55  -n 200 200  -enc-mode 4 4 -compressed-ten-bit-format 0 0  -q 31 31 -rc 0 0
`-------------------------------------------`
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.4.0
SVT [build]  :  GCC 7.3.0        64 bit
LIB Build date: Apr 30 2019 16:28:14
`-------------------------------------------`
Number of logical cores available: 112
Number of PPCS 99
`-------------------------------------------`
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 4
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 10 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 4096 / 2160
SVT [config]: FrameRate / Gop Size                                              : 60 / 56
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 31 / 33 / 0
`-------------------------------------------`
SVT [version]:  SVT-AV1 Encoder Lib v0.4.0
SVT [build]  :  GCC 7.3.0        64 bit
LIB Build date: Apr 30 2019 16:28:14
`-------------------------------------------`
Number of logical cores available: 112
Number of PPCS 139
`-------------------------------------------`
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 4
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 10 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1920 / 1080
SVT [config]: FrameRate / Gop Size                                              : 50 / 56
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 31 / 33 / 0
`-------------------------------------------`
**Encoding       326Killed**

**_demsg log:_**
[5530596.369421] [15343]  1000 15343 54848804 31972715 316190720   234708             0 SvtAv1EncApp
[5530596.369422] Out of memory: Kill process 15343 (SvtAv1EncApp) score 965 or sacrifice child
[5530596.371655] Killed process 15343 (SvtAv1EncApp) total-vm:219395216kB, anon-rss:127890860kB, file-rss:0kB, shmem-rss:0kB
[5530599.823619] oom_reaper: reaped process 15343 (SvtAv1EncApp), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

**Comment by hassount** [comment]
The muti-instance support should be turned off at this point. I can already see many issues.

**Comment by hassount** [comment]
This should be addressed by #435 could you check if such is the case ?

**Comment by JacksonDagger** [comment]
I couldn't recreate this. When I tried with the command line `SvtAv1EncApp -nch 2 -i ~/Desktop/stream/speed_4096x2160_60fps_10bit_420_840f.yuv ~/Desktop/stream/speed_1080p.yuv -b 2160p.bin 1080p.bin -w 4096 1920 -h 2160 1080 -enc-mode 4 4 -compressed-ten-bit-format 0 0 -q 31 31 -rc 0 0 -fps 50 60` the encoding remained at 1335 frames indefinitely. When this happened, SvtAv1EncApp dropped from using all 44 threads to just 1. This behaviour was observed in both commit bef6750 and commit d0f64ff (current HEAD). Anybody have any thoughts on this?

**Comment by JacksonDagger** [comment]
When I append `-n 200 200` bef6750 and d0f64ff encodes to 400 frames successfully.

**Comment by JacksonDagger** [comment]
I can no longer recreate the deadlock mentioned above

**Comment by hassount** [comment]
closing this
