### ISSUE TITLE
[SVT-AV1]segment fault when set width*height as 952*512 or 952*704.

### ISSUE THREAD

**Issue by GuCaixuan** [OpenVisualCloud/SVT-AV1#241]
Dear,
When we use the SVT-AV1 App with commitID bef6750 which is from Github Master to do encoding, we found that segment fault when set `width*height as 952*512 or 952*704.`

SvtAv1EncApp -i Netflix_TunnelFlag_4096x2160_8bit_60Hz_P420.yuv  -b width_height_test_M8_Netflix_TunnelFlag_4096x2160_8bit_60Hz_P420_Q37_952_512.av1  -errlog width_height_test_M8_Netflix_TunnelFlag_4096x2160_8bit_60Hz_P420_Q37_952_512.errlog  **`-w 952  -h 512`**  -bit-depth 8  -fps 60  -intra-period 55  -n 100  -compressed-ten-bit-format 0  -enc-mode 8  -q 37  -rc 0
`-------------------------------------------`
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.4.0
SVT [build]  :  GCC 7.3.0        64 bit
LIB Build date: Apr 30 2019 16:28:14
`-------------------------------------------`
Number of logical cores available: 112
Number of PPCS 159
`-------------------------------------------`
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 8
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 952 / 512
SVT [config]: FrameRate / Gop Size                                              : 60 / 56
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 37 / 33 / 0
`-------------------------------------------`
Encoding          Segmentation fault (core dumped)

_Thanks and waiting for your feedback._

**Comment by hassount** [comment]
Can't reproduce this anymore, please re-open if need be
