### ISSUE TITLE
Read access Violation thrown when running debug in Visual Studio 2015

### ISSUE THREAD

**Issue by deeptiag1** [OpenVisualCloud/SVT-AV1#244]
Command Line: ` -w 1280  -h 720  -i D:/work/yuvs.AV1/1280x720_8bit_50Hz_P420.yuv  -q 30  -fps 50  -b  /SVT_AV1/SVT-AV1/Bin/Release/bitstreams_aom/1280x720_8bit_50Hz_P420_Q30.ivf   -n 96  -intra-period 47  -bit-depth 8  -c  \SVT-AV1\Config\Sample.cfg   -lad 47  -hdr 0   -compressed-ten-bit-format 0`
VS config is Debug.( All other config works fine)
```
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.4.0
SVT [build]  :  Visual Studio 2017 64 bit
LIB Build date: May  9 2019 13:52:32
-------------------------------------------
Number of logical cores available: 56
Number of PPCS 139
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 7
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1280 / 720
SVT [config]: FrameRate / Gop Size                                              : 50 / 48
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 30 / 33 / 0
-------------------------------------------
Encoding         2
```

The exception is thrown 
![image](https://user-images.githubusercontent.com/44649298/57490298-a2cf3100-726d-11e9-8e6f-fa621439881b.png)

Platform tool kit: Visual Studio 2017 (v141); Debug info
Windows

**Comment by hassount** [comment]
@deeptiag1 
we were not able to reproduce the issue on our side. we would need access to the configuration file used specifically and the input yuv.

**Comment by deeptiag1** [comment]
-w 1280  -h 720  -i InToTree_1280x720_8bit_50Hz_P420.yuv  -q 30  -fps 50  -b  _InToTree_1280x720_8bit_50Hz_P420_Q30.ivf   -n 96  -intra-period 47  -bit-depth 8  -c   -lad 47  -hdr 0   -compressed-ten-bit-format 0

[Sample.txt](https://github.com/OpenVisualCloud/SVT-AV1/files/3192282/Sample.txt)

**Comment by JacksonDagger** [comment]
Was this in VS 2015 or 2017? What commit was this?

**Comment by hassount** [comment]
reopen if it's still needed
