### ISSUE TITLE
The definition value of MAX_TILE_ROWS and MAX_TILE_COLS not match with AV1 Spec

### ISSUE THREAD

**Issue by liweki** [OpenVisualCloud/SVT-AV1#245]
The definition value of MAX_TILE_ROWS and MAX_TILE_COLS in file https://github.com/OpenVisualCloud/SVT-AV1/blob/master/Source/Lib/Common/Codec/EbDefinitions.h doesn't match with the AV1 spec.

In SVT-AV1 code is defined as:
#define MAX_TILE_ROWS 1024
#define MAX_TILE_COLS 1024

In AV1 Spec is defined as:
MAX_TILE_ROWS 64 
MAX_TILE_COLS 64

**Comment by hassount** [comment]
@chkngit 
any specific reason why it was set to 1024 or can we just change it to 64?

**Comment by chkngit** [comment]
ported from Libaom as 1024, they might have changed lately.
