### ISSUE TITLE
[SVT AV1] Core dumped occurred when using latest Code to do encode with input clip "speed_1080p.yuv" in enc-mode 3

### ISSUE THREAD

**Issue by liweki** [OpenVisualCloud/SVT-AV1#249]
The clip "speed_1080p.yuv" has 5657 frames, while using this clip as input plus the latest Master code (commit id is 430c2a6) to do AV1 encoding in enc-mode 3, core dump or segment fault will occur when encoding to 2000+ frames.

The command line we used is:  
 encoders/SvtAv1EncApp -enc-mode 3  -w 1920  -h 1080  -i speed_1080p.yuv  -q 55  -fps 60  -b bitstreams/svt-av1_M3_speed_1080p_Q55.bin   -n 5657  -intra-period 64  -bit-depth 8  **-nb 5657**
**(NOTE: -nb must to be used, and the value should be lager than 2000)**

Log and error:
`-------------------------------------------`
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.4.0
SVT [build]  :  GCC 7.3.0        64 bit
LIB Build date: May 15 2019 10:19:49
`-------------------------------------------`
Number of logical cores available: 112
Number of PPCS 159
`-------------------------------------------`
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 3
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1920 / 1080
SVT [config]: FrameRate / Gop Size                                              : 60 / 65
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 55 / 33 / 0
`-------------------------------------------`
Encoding      2000
Average System Encoding Speed:        6.89                                                                                                                2773SvtAv1EncApp: /home/media/svt-av1-430c2a6/SVT-**AV1/Source/Lib/Common/Codec/EbCodingLoop.c:2771: av1_encode_pass: Assertion `(dv_ref.as_mv.col & 7) == 0' failed.
Aborted (core dumped)**

Dmesg log:
[6206112.094391] SvtAv1EncApp[38309]: segfault at 0 ip 00007f0a82fc83a8 sp 00007f03dc7cf7a0 error 4 in libSvtAv1Enc.so[7f0a82e92000+30b000]
[6206112.094407] Code: d0 e8 83 e0 03 41 88 87 cc 00 00 00 41 8b 45 41 41 89 87 c4 00 00 00 41 8b 45 45 41 89 87 c8 00 00 00 48 8b 47 38 48 8b 40 10 <4c> 8b 00 80 bc 24 d8 00 00 00 00 49 8d 87 c4 00 00 00 0f 84 58 02

**Comment by hassount** [comment]
@liweki 
Can you please confirm if this is still happening, could not rep on our side

**Comment by hassount** [comment]
Can not reproduce this issue, please re-open if it's still the case.
