### ISSUE TITLE
Tag commit 3009e99 as version 0.5.0 on Git

### ISSUE THREAD

**Issue by EwoutH** [OpenVisualCloud/SVT-AV1#255]
Since commit 3009e99 is marked as version 0.5.0 in the API, it should also be tagged on Git as such (or on [GitHub](https://github.com/OpenVisualCloud/SVT-AV1/releases) as (pre)release).

@hassount @kylophone

**Comment by hassount** [comment]
Done :)  https://github.com/OpenVisualCloud/SVT-AV1/releases

**Comment by hassount** [comment]
I am hoping now we can do a issues sweep to cleanup the list and target issues for upcoming pre-releases

**Comment by EwoutH** [comment]
In the exact same minute! :)

> I am hoping now we can do a issues sweep to cleanup the list and target issues for upcoming pre-releases

Sounds like a plan! Maybe create a [milestone](https://github.com/OpenVisualCloud/SVT-AV1/milestones) for 0.6.0 to which issues and PRs can be added?

Also the AppVeyor upload to GitHub working as expected!
