### ISSUE TITLE
[SVT AV1]The output streams are different with "BufferedInput" enable (-nb 20) and disable (-nb -1) for encmode[0-2].

### ISSUE THREAD

**Issue by GuCaixuan** [OpenVisualCloud/SVT-AV1#258]
Dear,
When we use the SVT-AV1 App with commitID 3f1b59c which is from Github Master to do encoding, we found that the output streams are different with "BufferedInput" enable (-nb 20) and disable (-nb -1) for encmode[0-2]. We also found that the size of output streams are different each execution.

encoders/SvtAv1EncApp -i Fallout4_1920x1080_8bit_60Hz_P420.yuv  -b buffered_test_M1_Fallout4_1920x1080_8bit_60Hz_P420_Q32_20.bin  -errlog buffered_test_M1_Fallout4_1920x1080_8bit_60Hz_P420_Q32_20.errlog  -w 1920  -h 1080  -bit-depth 8  -fps 60  -intra-period 55  -n 20  -enc-mode 1  -compressed-ten-bit-format 0  -q 32  -rc 0  **_-nb 20_** 
encoders/SvtAv1EncApp -i Fallout4_1920x1080_8bit_60Hz_P420.yuv  -b buffered_test_M1_Fallout4_1920x1080_8bit_60Hz_P420_Q32_-1.bin  -errlog buffered_test_M1_Fallout4_1920x1080_8bit_60Hz_P420_Q32_-1.errlog  -w 1920  -h 1080  -bit-depth 8  -fps 60  -intra-period 55  -n 20  -enc-mode 1  -compressed-ten-bit-format 0  -q 32  -rc 0  **_-nb -1_** 

First time run result:
-rw-rw-r-- 1 media media **_915481_** 5月  20 22:48 bitstreams/buffered_test_M1_Fallout4_1920x1080_8bit_60Hz_P420_Q32_-1.bin
-rw-rw-r-- 1 media media **_915841_** 5月  20 22:46 bitstreams/buffered_test_M1_Fallout4_1920x1080_8bit_60Hz_P420_Q32_20.bin

Second time run result:
-rw-rw-r-- 1 media media **_915841_** 5月  20 23:12 bitstreams/buffered_test_M1_Fallout4_1920x1080_8bit_60Hz_P420_Q32_-1.bin
-rw-rw-r-- 1 media media **_915686_** 5月  20 23:15 bitstreams/buffered_test_M1_Fallout4_1920x1080_8bit_60Hz_P420_Q32_20.bin

Third time run result:
-rw-rw-r-- 1 media media **_915482_** 5月  20 23:17 bitstreams/buffered_test_M1_Fallout4_1920x1080_8bit_60Hz_P420_Q32_-1.bin
-rw-rw-r-- 1 media media **_915841_** 5月  20 23:18 bitstreams/buffered_test_M1_Fallout4_1920x1080_8bit_60Hz_P420_Q32_20.bin

**Comment by hassount** [comment]
@GuCaixuan 
Can we check if this is still the case in the current master ?

**Comment by GuCaixuan** [comment]
@hassount 
I checked this issue on Commit ID fbad3ac and can reproduce it.
Reproduced command line:
SvtAv1EncApp -i Netflix_FoodMarket2_4096x2160_10bit_60Hz_P420.yuv  -b buffered_test_M0_Netflix_FoodMarket2_4096x2160_10bit_60Hz_P420_Q30_20.bin  -w 4096  -h 2160  -bit-depth 10  -fps 60  -intra-period 55  -n 20  -enc-mode 0  -compressed-ten-bit-format 0  -q 30  -rc 0  -nb 20
SvtAv1EncApp -i Netflix_FoodMarket2_4096x2160_10bit_60Hz_P420.yuv  -b buffered_test_M0_Netflix_FoodMarket2_4096x2160_10bit_60Hz_P420_Q30_-1.bin  -w 4096  -h 2160  -bit-depth 10  -fps 60  -intra-period 55  -n 20  -enc-mode 0  -compressed-ten-bit-format 0  -q 30  -rc 0  -nb -1

Thanks

**Comment by hassount** [comment]
@GuCaixuan 
Several R2R bug fixes have been merged to master, can you please check if this is addressed?

**Comment by hassount** [comment]
> @GuCaixuan
> Several R2R bug fixes have been merged to master, can you please check if this is addressed?

@GuCaixuan
Several R2R bug fixes have been merged to master, can you please check if this is addressed?

**Comment by GuCaixuan** [comment]
@hassount 
OK, I will check it.

**Comment by GuCaixuan** [comment]
@hassount 
I checked this issue on Commit ID 3cbd768 and can reproduce it.
Reproduced command line:
SvtAv1EncApp -i Netflix_FoodMarket2_4096x2160_10bit_60Hz_P420.yuv  -b buffered_test_M0_Netflix_FoodMarket2_4096x2160_10bit_60Hz_P420_Q32_-1.bin   -w 4096  -h 2160  --input-depth 10  --fps 60  --keyint 55  -n 20  --preset 0  --compressed-ten-bit-format 0  -q 32  --rc 0  --nb -1

SvtAv1EncApp -i Netflix_FoodMarket2_4096x2160_10bit_60Hz_P420.yuv  -b buffered_test_M0_Netflix_FoodMarket2_4096x2160_10bit_60Hz_P420_Q32_20.bin   -w 4096  -h 2160  --input-depth 10  --fps 60  --keyint 55  -n 20  --preset 0  --compressed-ten-bit-format 0  -q 32  --rc 0  --nb 20
![sss](https://user-images.githubusercontent.com/45022980/79844357-238b2c80-83ee-11ea-987b-3d88ed85a0e0.PNG)

Thanks

**Comment by hassount** [comment]
@GuCaixuan 
thank you for the test. 
@OmranAbdelkafi can we add this to the list of items to be checked ?

**Comment by hassount** [comment]
would this be finally addressed ? @OmranAbdelkafi @GuCaixuan ?

**Comment by hassount** [comment]
Closing this, please re-open if you can still reproduce it
