### ISSUE TITLE
Integrate SVT-AV1 in FFmpeg

### ISSUE THREAD

**Issue by EwoutH** [OpenVisualCloud/SVT-AV1#259]
It would be nice if the SVT encoders could be integrated into mainline FFmpeg (and be build with `--enable-svt` for example). 

- https://trac.ffmpeg.org/ticket/7914

**Comment by kylophone** [comment]
Would be nice, but I don't think the current state is considered to be stable. (i.e. API could potentially change).

**Comment by BlauerHunger** [comment]
I guess before this happens, the ffmpeg_plugin in this repository needs to work for mp4 and mkv/webm

**Comment by xuguangxin** [comment]
> I guess before this happens, the ffmpeg_plugin in this repository needs to work for mp4 and mkv/webm

@kylophone , anyone working on this?  If not,  I can work on it.

**Comment by EwoutH** [comment]
@xuguangxin I don't think anyone is working on this, that would be great!

**Comment by xuguangxin** [comment]
@EwoutH , sure I will start working on it today.

**Comment by hassount** [comment]
@jsunintel just making sure no duplicate work is being done here

**Comment by jsunintel** [comment]
> 
> 
> > I guess before this happens, the ffmpeg_plugin in this repository needs to work for mp4 and mkv/webm
> 
> @kylophone , anyone working on this? If not, I can work on it.

This is already done. “Tang, Zhizhen” is submitting it any time soon.

**Comment by xuguangxin** [comment]
@jsunintel ,   @hassount, thanks for checking, but it's little later. I already got my prototype running.  mp4 and webm are working well.  :)
Never minder, the work will not be wasted. I can help review @TangZhiZhen 's patch.

Also please assign https://github.com/OpenVisualCloud/SVT-AV1/issues/72 to TangZhiZhen. 
It's a good practice to assign an issue to the owner before she/he started the work. It will make the development process more transparent and avoid duplicate work.

thanks

**Comment by TangZhiZhen** [comment]
I have submitted the PR https://github.com/OpenVisualCloud/CDN-Transcode-Sample.

**Comment by xuguangxin** [comment]
@TangZhiZhen , thanks for the patch, commented in the PR

**Comment by EwoutH** [comment]
Now that #286 is merged, is FFmpeg ready to be integrated into mainline FFmpeg?

**Comment by EwoutH** [comment]
> Now that #286 is merged, is FFmpeg ready to be integrated into mainline FFmpeg?

@hassount ? If so, could youbassign someone to it? Shouldn't be a large efford but could hugely with community participation.

**Comment by hassount** [comment]
@EwoutH the API is still not stable for SVT-AV1 to be up streamed don't you think it's best to wait until it stabilizes further ?

**Comment by EwoutH** [comment]
I think we should reconsider sending the patch in with the 0.7.0 release. A big advantage from being integrated in mainline FFmpeg is the wider user base, which will be able to find bugs more quickly.

**Comment by xuguangxin** [comment]
totally agree with this.  
@hassount & @jsunintel , what do you think?

**Comment by hassount** [comment]
> I think we should reconsider sending the patch in with the 0.7.0 release. A big advantage from being integrated in mainline FFmpeg is the wider user base, which will be able to find bugs more quickly.

> totally agree with this.
> @hassount & @jsunintel , what do you think?

I agree that this will provide more exposure to testing in the wider community. however, we plan to perform a lot of API changes over the next couple of months after which we could do the upstream so 0.8.0 / 0.8.5 would be a good time

**Comment by lizhong1008** [comment]
@hassount , agree that would be good to upstream if the API is statable. Another input from is compatibility:  the plugin in ffmpg mainline should be compatible with diffrent SVT API and libary version, so if you have any update about the API/libary, would be good to bump a new API/libary version then can be checked in FFmpeg to make sure wouldn't break with legacy versions.

**Comment by hassount** [comment]
@jbkempf tagging for future tracking

**Comment by jbkempf** [comment]
@hassount https://ffmpeg.org/pipermail/ffmpeg-devel/2020-June/265327.html

**Comment by 1480c1** [comment]
Believe this has been done, so it can be closed
