### ISSUE TITLE
[ffmpeg_plugin] PSNR(Y:24.64757) of ffmpeg SVT AV1 encoding bitstream is lower

### ISSUE THREAD

**Issue by waterflag0614** [OpenVisualCloud/SVT-AV1#268]
- ffmpeg

1. cp DucksTakeOff_1280x720_8bit_50Hz_P420.yuv 0003.prep.yuv

2. ffmpeg -r 50 -video_size 1280x720 -pixel_format yuv420p -f rawvideo -i  0003.prep.yuv -c:v libsvt_av1 -qp 41 -i_qfactor 40/41 -b_qfactor 42/41 -preset 7 -r 50 -aspect 1 -chroma_sample_location 1 -vframes 250  0003_qp40.ivf -y 2>&1
`SVT [config]: Main Profile      Tier (auto)     Level (auto)`
`SVT [config]: EncoderMode                                                       : 7`
`SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0`
`SVT [config]: SourceWidth / SourceHeight                                        : 1280 / 720`
`SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType   : 50 / 1 / 48 / 1`
`SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2`
`SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                 : CQP / 41 / 33 / 0`

3. ffmpeg -i  0003_qp40.ivf -pix_fmt  yuv420p -f rawvideo -vframes 250  0003_qp40.ivf.yuv -y 2>&1

4. metrics_calc_lite  -i1  0003_qp40.ivf.yuv -i2  0003.prep.yuv -w 1280 -h 720 -st  i420p i420p psnr all
`<avg_metric=Y-PSNR> 24.64757</avg_metric>`
`<avg_metric=U-PSNR> 33.27738</avg_metric>`
`<avg_metric=V-PSNR> 39.12151</avg_metric>`
`<avg_metric=PSNR> 26.22482</avg_metric>` 

- SvtAv1EncApp

1. SvtAv1EncApp -i  0003.prep.yuv -w 1280 -h 720 -fps-num 50 -fps-denom 1 -enc-mode 7 -latency-mode 0 -irefresh-type 1 -n 250  -q 41 -b  0003_qp40.ivf.svtapp
`SVT [config]: Main Profile      Tier (auto)     Level (auto)`
`SVT [config]: EncoderMode                                                       : 7`
`SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0`
`SVT [config]: SourceWidth / SourceHeight                                        : 1280 / 720`
`SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType  : 50 / 1 / 48 / 1`
`SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2`
`SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange            : CQP / 41 / 33 / 0`

2. ffmpeg -i  0003_qp40.ivf.svtapp -pix_fmt  yuv420p -f rawvideo -vframes 250  0003_qp40.ivf.svtapp.yuv -y 2>&1

3. metrics_calc_lite -i1  0003_qp40.ivf.svtapp.yuv -i2  0003.prep.yuv -w 1280 -h 720 -st  i420p i420p psnr all
`<avg_metric=Y-PSNR> 32.87319</avg_metric>`
`<avg_metric=U-PSNR> 36.13996</avg_metric>`
`<avg_metric=V-PSNR> 40.36058</avg_metric>`
`<avg_metric=PSNR> 33.98048</avg_metric>`

playing the bitstream encoded with ffmpeg by ffplay, subjective visual effect  is not as good as the bitstream encoded with SvtAv1EncApp。

**Comment by hassount** [comment]
@waterflag0614 
Thank you for reporting this. 
@jsunintel 
Could you please look into the differences here ?

**Comment by jsunintel** [comment]
> 
> 
> @waterflag0614
> Thank you for reporting this.
> @jsunintel
> Could you please look into the differences here ?

OK.

**Comment by jsunintel** [comment]
The main issue causing this was the received packets from SVT AV1 Lib having partial IVF header indicators, and when working with the standard IVF muxer, the output bistream was ploblematic. All the packets with EB_BUFFERFLAG_HAS_TD or EB_BUFFERFLAG_SHOW_EXT were written into the bitstream in a wrong way and can't get decoded correctly.

The ffmpeg automatically duplicated the former frame when the current one failed to get decoded. The output seemed correct, but it was not for real. And of course the PSNR was quite low.

**Comment by xuguangxin** [comment]
@waterflag0614 @jsunintel , could you try https://github.com/OpenVisualCloud/SVT-AV1/pull/1053?
thanks

**Comment by xuguangxin** [comment]
@waterflag0614 , @waterflag0614 . #1053 has merged. Could you help try master?
We can close the issue if it's not reproduceable.
thanks

**Comment by hassount** [comment]
closing this
