### ISSUE TITLE
Suspicious code in av1_tu_calc_cost_luma

### ISSUE THREAD

**Issue by joelsole** [OpenVisualCloud/SVT-AV1#272]
In file EbRateDistortionCost.c, function av1_tu_calc_cost_luma has the following code, which seems to set the wrong cost:

    if (1) {
        yZeroCbfCost = 0xFFFFFFFFFFFFFFFFull;
    }
    else {
        yZeroCbfCost = RDCOST(lambda, yZeroCbfRate, yZeroCbfDistortion);
    }

**Comment by hassount** [comment]
@chkngit @hguermaz 
any thoughts on this ?

**Comment by hguermaz** [comment]
This function is used to perform Cbf zero mode (check the cost assuming no coeff). Now this functionality is shut as the cost of assuming no coeff is set to max. This function should be renamed and cleaned-up; keep current cost and has coeff flag derivation only. av1_tu_calc_cost_luma(), but also av1_tu_calc_cost_luma().
