### ISSUE TITLE
[SVT AV1] The values of PSNR and SSIM of SVT_AV1 are worse than the values of AOM_AV1

### ISSUE THREAD

**Issue by GuCaixuan** [OpenVisualCloud/SVT-AV1#274]
Dear,
When we use the SVT-AV1 App with commitID 3f1b59c which is from Github Master to do encoding, 
we found the values of PSNR and SSIM of SVT_AV1 are worse than the values of AOM

AOM-AV1 version: AOM AV1 @ master(837df48423a9ea1535ed34ca1ea5eebb747a752b)
SVT-AV1 version： SVT-AV1 @ hguermaz:m3-build(3f1b59c4babdb844079fee6b07af927a71993341)

![PSNR](https://user-images.githubusercontent.com/45022980/58313320-dd28f880-7e3f-11e9-8cbb-bf5be32a9373.PNG)

Thanks

**Comment by 1480c1** [comment]
Please redo the svt av1 tests as there has been more commits since that commit

**Comment by EwoutH** [comment]
@GuCaixuan Thanks for the tests! Which speed setting did you use? '-enc-mode 8' is default and is fast but delivers bad quality. A lower setting improves quality hugely.

**Comment by GuCaixuan** [comment]
@EwoutH 
The speed which we used is '-enc-mode 0'.

SVT-AV1 Command line as below shown:
SvtAv1EncApp -enc-mode 0  -w 1920  -h 1080  -i aspen_1080p_60f.yuv  -q 20  -fps-num 30000 -fps-denom 1001 -b svt-av1_M0_aspen_1080p_60f_Q20.bin   -n 60  -intra-period 119  -bit-depth 8  -lad 119  -hdr 0

**Comment by hassount** [comment]
@GuCaixuan 
Thank you for the report. This is expected for now as we are still not feature complete yet. that said, you should start seeing improvements on this comparison as we push new features e.g.  build https://github.com/OpenVisualCloud/SVT-AV1/commit/9865f67b93eff99ad3066fd0d45cd6c5eab57e8a
