### ISSUE TITLE
Adding Adaptive Transform Block Size support

### ISSUE THREAD

**Issue by hassount** [OpenVisualCloud/SVT-AV1#278]
A major structural commit in Mode decision and encode pass
Trello reference: https://trello.com/c/OjvsL7t5/48-adaptive-transform-block-size
Current working branch: https://github.com/hguermaz/SVT-AV1/tree/atp_rdoq 

Will be moving branches to this repo after this.

**Comment by kylophone** [comment]
Thanks! This makes it easier for everyone to see what's coming.

**Comment by kylophone** [comment]
Please add a changelog entry to the patch when submitting
