### ISSUE TITLE
Current malloc mechanism  is not thread safe, and it will crash when we have multi instance.

### ISSUE THREAD

**Issue by xuguangxin** [OpenVisualCloud/SVT-AV1#285]
EB_MALLOC directly access global variable without mutex.

https://github.com/OpenVisualCloud/SVT-AV1/blob/6a27563a29503376fd27e5049dd5460f3c431ff2/Source/Lib/Common/Codec/EbDefinitions.h#L2583-L2602
It may corrupt memory in multithread env.

For example, sb_params_init and rate_control_model_init both called EB_MALLOC, They are in the diffrent thread. It may have a problem.
https://github.com/OpenVisualCloud/SVT-AV1/blob/6a27563a29503376fd27e5049dd5460f3c431ff2/Source/Lib/Common/Codec/EbSequenceControlSet.c#L419-L428
https://github.com/OpenVisualCloud/SVT-AV1/blob/6a27563a29503376fd27e5049dd5460f3c431ff2/Source/Lib/Common/Codec/RateControlModel.c#L74-L78

Multiway transcode may bring more problems. Different decoders instance may malloc memory in different threads.

**Comment by kylophone** [comment]
Yeah. We may want to get rid of global state altogether. What happens, for example, when we init and try to use two encoding contexts within the same compilation unit?

**Comment by hassount** [comment]
Sure, contributions are welcome here, we just would like to keep the following ability:
- If a malloc fails half way through init time, we should be able to free everything that got allocated already.

**Comment by xuguangxin** [comment]
@kylophone , @hassount , I can handle this, please assign the issue to me.
Let me echo @hassount 's requirements.
1. We can free memory at the end of object lifetime.
2. If an error returned in the constructor,  the object is partly constructed, we need to free the memory associated with the object.
2. We need to provide memory/mutex/semaphore usage summary 
Any more requirement?

**Comment by kylophone** [comment]
> @kylophone , @hassount , I can handle this, please assign the issue to me.
OK, I've assigned this to you.

> Let me echo @hassount 's requirements.
> 
> 1. We can free memory at the end of object lifetime.
> 2. If an error returned in the constructor,  the object is partly constructed, we need to free the memory associated with the object.
> 3. We need to provide memory/mutex/semaphore usage summary
>    Any more requirements?

Is there anyway to accomplish this without global library state? I have no idea what would happen if more than one encoder context were to be init'd and then used concurrently.

**Comment by xuguangxin** [comment]
> I have no idea what would happen if more than one encoder context were to be init'd and then used concurrently.

I can tell you :)

https://github.com/OpenVisualCloud/SVT-AV1/blob/b009c0fdbb64b486c71d0887233fe29807fa6f95/Source/Lib/Encoder/Codec/EbEncHandle.c#L720-L728

When we create a new encoder, this code will set the global variable to an encoder member variable.
1. All memory associated with encoder1 will leak.
2. If we deinit encoder1 before encoder2, encoder1 will release all memory allocated by encoder2. encoder 2 will crash. 

We can't depend on some centralized module like [eb_deinit_encoder](https://github.com/OpenVisualCloud/SVT-AV1/blob/b009c0fdbb64b486c71d0887233fe29807fa6f95/Source/Lib/Encoder/Codec/EbEncHandle.c#L1962) to free all memory. 
I suppose we will have some global variables to count memory/mutex/semaphore usage. But nothing more.

**Comment by kylophone** [comment]
So, I guess #287 is on hold?

**Comment by xuguangxin** [comment]
No, we still need it.
It fixed the current problem.
It also simplified the code, make global variable access limited in one place.
It's much better than change it in 10+ places.

thanks

**Comment by xuguangxin** [comment]
This fixed by #314. thanks, kylophyon and hassount  help on this
