### ISSUE TITLE
 Estamine predictable (pre-)release schedule

### ISSUE THREAD

**Issue by EwoutH** [OpenVisualCloud/SVT-AV1#29]
A predictable release schedule would be very useful for package managers and other tools that depend on tagged releases. We could do weekly (pre-)releases (like 20190206, 20190213, etc.) or releases following semantic versioning on major changes (but at least twice a month).

**Comment by andrey-norkin** [comment]
It might be too early to have releases. This is still work in progress.

**Comment by EwoutH** [comment]
They can be marked as pre-releases, which can be supported with a 0.x.x tag. Many package managers, but also tools that rely on libraries, require at least one tagged release.

Getting SVT-AV1 in package managers and programs like FFmpeg can help drive adoption, which in return drives community engagement (bug reporting in particular).

**Comment by EwoutH** [comment]
The CLI states the current version is `v0.4.0`, maybe we can tag the current commit as `v0.4.1`?

**Comment by eclipseo** [comment]
I'll be interested to package it for Fedora once a minor release is made.

**Comment by EwoutH** [comment]
@kylophone @hassount What do you think?

**Comment by hassount** [comment]
Setting up a release schedule at this point is quite early as we still have a lot of features / optimizations to add.  We will try to reach a stable version to tag by early march would that work for everyone ?

**Comment by jbeich** [comment]
[![Packaging status](https://repology.org/badge/vertical-allrepos/svt-av1.svg)](https://repology.org/metapackage/svt-av1/versions)

**Comment by EwoutH** [comment]
From an [Intel press release](https://itpeernetwork.intel.com/open-source-visual-cloud-innovation/)
> Through close collaboration with Netflix, we are proud to release the SVT-AV1 1.0 encoder implementation

@hassount @kylophone Do you know any more about this?

**Comment by hassount** [comment]
@EwoutH 
we're planning a stable tag by the early May.

**Comment by singhkays** [comment]
@hassount @kylophone For the stable release in May, are there VMAF/PSNR/SSIM KPIs for comparison to libaom?

**Comment by hassount** [comment]
@singhkays 
Quality metrics are being published on are we compressed yet. 
https://beta.arewecompressedyet.com/?job=svt-av1%402019-03-15T01%3A14%3A29.113Z&job=svt-av1-1&job=%402019-04-15T18%3A23%3A11.898Z

We usually run some periodically on the master, the tag will come out of the master.

**Comment by EwoutH** [comment]
> I'll be interested to package it for Fedora once a minor release is made.

@eclipseo [v0.5.0](https://github.com/OpenVisualCloud/SVT-AV1/releases/tag/v0.5.0) just got tagged

**Comment by 1480c1** [comment]
@eclipseo, if you are still interested in packaging 0.5.0, here is a patch to remove mavx and apply the correct cflags for the rest of the cmakelists.

https://gist.githubusercontent.com/1480c1/19d703727adceb91c09dd0d55a853ff8/raw/0001-CMakeLists-Remove-mavx-and-apply-correct-cflags.patch

**Comment by 1480c1** [comment]
@eclipseo, alternatively, you can do something like what @jbeich does and add a small patch increment to match master branch

**Comment by EwoutH** [comment]
@hassount Could we do another minor pre-release sometime soon? Maybe create a [milestone](https://github.com/OpenVisualCloud/SVT-AV1/milestones) for 0.7 and assign issues that should be fixed before the next release to it.

**Comment by hassount** [comment]
@EwoutH 
working hard on getting the major features synced to master to get a 0.7.0

**Comment by EwoutH** [comment]
@hassount Let's try to get back to a monthly pre-release schedule. Would tagging 0.7 this week be realistic?

**Comment by EwoutH** [comment]
It has been almost 2 months since the last pre-release, can we tag a new pre-release this week?

Since API changes are introduced I would suggest moving to 0.8.0

**Comment by EwoutH** [comment]
@hassount I would suggest a big bug bash session somewhere before the 0.8.0 tag. There are currently [25 open issues](https://github.com/OpenVisualCloud/SVT-AV1/issues?q=is%3Aissue+is%3Aopen+label%3Abug) on GitHub tagged as bug.

**Comment by hassount** [comment]
@EwoutH 
First off, I apologize but I seem to have missed your comment of 15days ago. we had to wait for a few bug fixes to come in to be able to make the code a little more stable. The previous changes did not add much when it comes to API as the params added would not break previous builds, thus the option of having the increment 0.7.5. 

> @hassount I would suggest a big bug bash session somewhere before the 0.8.0 tag. There are currently [25 open issues](https://github.com/OpenVisualCloud/SVT-AV1/issues?q=is%3Aissue+is%3Aopen+label%3Abug) on GitHub tagged as bug.


Thank you for the suggestions, we are actively working on bugs as a high priority. I hope you could notice that several major bugs have been closed already in 0.7.5

**Comment by EwoutH** [comment]
@kylophone @hassount Do you think it would be possible to tag another release before Christmas? I suspect a large portion of the AV1 community would like to experiment a bit around the holidays.

**Comment by hassount** [comment]
> @kylophone @hassount Do you think it would be possible to tag another release before Christmas? I suspect a large portion of the AV1 community would like to experiment a bit around the holidays.

@EwoutH 
sure, let's plan one before the cleanup phase and as soon as we reach the code freeze point,, hopefully mid next week

**Comment by hassount** [comment]
can we close this discussion as we've been tagging on a 6-8 week cadence?

**Comment by EwoutH** [comment]
@hassount Yes, I will close it
