### ISSUE TITLE
Content Adaptive QP Scaling

### ISSUE THREAD

**Issue by hassount** [OpenVisualCloud/SVT-AV1#294]
Description: add content adaptive QP Scaling assignment to non-key frames 
Trello reference: https://trello.com/c/IOQiZ1Jy/58-content-adaptive-qp-scaling
Current working branch: https://github.com/hguermaz/SVT-AV1/tree/QP_SCALING

**Comment by anaghdin** [comment]
Created a PR for the issue. PR #310

**Comment by 1480c1** [comment]
Rather than outright closing this issue, I think it would be best to add somewhere in the pr text
`Closes #294`, maybe after your `Associated with Issue #294` so that once that pr is merged, this issue will close

**Comment by 1480c1** [comment]
That way this issue can stay as a temp tracker until the associated code stuff is in master

**Comment by anaghdin** [comment]
Thanks. I have added Associated with Issue #294 in my PR. I will reopen the issue again.

**Comment by 1480c1** [comment]
Main reason why I said `Closes` is because that way, github will automatically close this issue for you.
[Here](https://help.github.com/en/articles/closing-issues-using-keywords) for more information

**Comment by anaghdin** [comment]
Updated the PR. Thanks for the link.
