### ISSUE TITLE
target_link_libraries function in test/CMakeLists.txt fails

### ISSUE THREAD

**Issue by EwoutH** [OpenVisualCloud/SVT-AV1#295]
The target_link_libraries function in [test/CMakeLists.txt:70](https://github.com/OpenVisualCloud/SVT-AV1/blob/master/test/CMakeLists.txt#L70) fails currently on my system.

**Build commands**
```
git clone https://github.com/OpenVisualCloud/SVT-AV1.git;
cd SVT-AV1;
./Build/linux/build.sh release;
cd ..;
/home/ewouth/SVT-AV1/Bin/Release/SvtAv1EncDec -help;
```
**Error message**
```
CMake Error at test/CMakeLists.txt:70 (target_link_libraries):
  Target "COMMON_CODEC" of type OBJECT_LIBRARY may not be linked into another
  target.  One may link only to STATIC or SHARED libraries, or to executables
  with the ENABLE_EXPORTS property set.


CMake Error at test/CMakeLists.txt:70 (target_link_libraries):
  Target "COMMON_C_DEFAULT" of type OBJECT_LIBRARY may not be linked into
  another target.  One may link only to STATIC or SHARED libraries, or to
  executables with the ENABLE_EXPORTS property set.


CMake Error at test/CMakeLists.txt:70 (target_link_libraries):
  Target "COMMON_ASM_SSE2" of type OBJECT_LIBRARY may not be linked into
  another target.  One may link only to STATIC or SHARED libraries, or to
  executables with the ENABLE_EXPORTS property set.


CMake Error at test/CMakeLists.txt:70 (target_link_libraries):
  Target "COMMON_ASM_SSSE3" of type OBJECT_LIBRARY may not be linked into
  another target.  One may link only to STATIC or SHARED libraries, or to
  executables with the ENABLE_EXPORTS property set.


CMake Error at test/CMakeLists.txt:70 (target_link_libraries):
  Target "COMMON_ASM_SSE4_1" of type OBJECT_LIBRARY may not be linked into
  another target.  One may link only to STATIC or SHARED libraries, or to
  executables with the ENABLE_EXPORTS property set.


CMake Error at test/CMakeLists.txt:70 (target_link_libraries):
  Target "COMMON_ASM_AVX2" of type OBJECT_LIBRARY may not be linked into
  another target.  One may link only to STATIC or SHARED libraries, or to
  executables with the ENABLE_EXPORTS property set.
```

**Comment by hassount** [comment]
seems to have been broken here:
https://travis-ci.org/OpenVisualCloud/SVT-AV1/jobs/537020125
Commit: https://github.com/OpenVisualCloud/SVT-AV1/commit/c7b108ad518b2f223fa7d56c3fdbd482086bc261

**Comment by EwoutH** [comment]
@hassount Decoder isn't critical. Let's reverse that commit.

**Comment by EwoutH** [comment]
The CMakeLists.txt starts to fail between 43839ea and 1ac1ecc.

**Comment by EwoutH** [comment]
@jstebbins Did you encounter similar errors somewhere in the process?

**Comment by kylophone** [comment]
Do we need to revert that merge?

**Comment by jstebbins** [comment]
@EwoutH I've not seen errors like that before.  ```build.sh all test``` was working fine for me until recent decoder changes.  One of the decoder commits causes errors while building tests for me now in git head.
> test/BitstreamReaderMock.cc:146:28: error: ‘OD_EC_WINDOW_SIZE’ was not declared in this scope
     dec->tell_offs = 10 - (OD_EC_WINDOW_SIZE - 8);

**Comment by 1480c1** [comment]
> @EwoutH I've not seen errors like that before. `build.sh all test` was working fine for me until recent decoder changes. One of the decoder commits causes errors while building tests for me now in git head.
> 
> > test/BitstreamReaderMock.cc:146:28: error: ‘OD_EC_WINDOW_SIZE’ was not declared in this scope
> > dec->tell_offs = 10 - (OD_EC_WINDOW_SIZE - 8);

Ditto with me

**Comment by EwoutH** [comment]
AreWeCompressedYet? is facing the [same CMake build errors](https://beta.arewecompressedyet.com/?job=SVT-AV1-enc-mode-3%402019-05-29&job=SVT-AV1-enc-mode-8%402019-05-29).
