### ISSUE TITLE
Crash in master encoding some 1080p clips

### ISSUE THREAD

**Issue by hassount** [OpenVisualCloud/SVT-AV1#296]
Clips from the test set
- MINECRAFT
- Netflix_SquareAndTimelapse
- Netflix_FoodMarket

**Comment by hassount** [comment]
tracked to commit 4dc83fc
will probably need to turn off the feature for now as this is a blocker to #279

**Comment by EwoutH** [comment]
@hassount Got this from AWCY?

**Comment by hassount** [comment]
@EwoutH we were testing the master and the crashes showed up

**Comment by EwoutH** [comment]
We should have better tests in CI.

**Comment by joelsole** [comment]
@hassount can we close this?

**Comment by hassount** [comment]
we can close it when #649 is merged
