### ISSUE TITLE
Implement library logging function, svt_log()

### ISSUE THREAD

**Issue by kylophone** [OpenVisualCloud/SVT-AV1#302]
We need a proper log function complete with log levels. Also, the lib should log to stderr by default (not stdout!) since we may want to have piped output. All calls to `printf()`and `fprintf()` should be replaced with this logging function. This is a relatively easy task, see `av_log()` in ffmpeg for inspiration.

**Comment by 1480c1** [comment]
I was considering to do this to address #231, at least the log to stderr

**Comment by joelsole** [comment]
That would be great, thanks. 

Harmonization is needed, as there are several definitions with printf: SVT_LOG, H0, PRINT
