### ISSUE TITLE
Add github teams?

### ISSUE THREAD

**Issue by 1480c1** [OpenVisualCloud/SVT-AV1#321]
Would it be possible to organize the people who work on SVT-AV1 into teams and sub-teams?
<https://help.github.com/en/articles/about-teams>
It would make it easier to know who works on what in the repo and their speciality within the repo.

For example, Idk who to ping other than maybe @hassount for general OpenVisualCloud stuff since <https://github.com/orgs/OpenVisualCloud/people> is completely empty

**Comment by EwoutH** [comment]
I like this.

**Comment by jbeich** [comment]
AFAIK, GitHub **teams** cannot be made public unlike organization **membership**.

**Comment by JackZhouVCD** [comment]
Thanks for the suggestion, we now have teams for SVT-AV1 organized as seen [here](https://github.com/orgs/OpenVisualCloud/teams?query=av1)

**Comment by 1480c1** [comment]
@JackZhouVCD, I think the teams are private so we are unable to see them

**Comment by EwoutH** [comment]
Can confirm, unable to see them.
