### ISSUE TITLE
Run-to-run mismatch in master

### ISSUE THREAD

**Issue by mafonsoN** [OpenVisualCloud/SVT-AV1#323]
Run-to-run mismatch detected in the current master **enc-mode 0**, tested in Linux (Ubuntu). Example below, for sequence blue_sky.

The problem still persists with -enable-altrefs 0 and before the clean-up commits of May 30, 2019.

More tests are needed to understand when this issue started and what is the cause.

**sequence                 | codec | QP | Kbps      | PSNR-Y**
blue_sky_360p_60f | svtav1 | 20  | 1564.38 | 44.088
blue_sky_360p_60f | svtav1 | 20  | 1565.14 | 44.090
blue_sky_360p_60f | svtav1 | 20  | 1564.83 | 44.093
blue_sky_360p_60f | svtav1 | 20  | 1564.83 | 44.093
blue_sky_360p_60f | svtav1 | 20  | 1564.87 | 44.091
blue_sky_360p_60f | svtav1 | 20  | 1565.08 | 44.094
blue_sky_360p_60f | svtav1 | 20  | 1564.88 | 44.091
blue_sky_360p_60f | svtav1 | 20  | 1565.28 | 44.092
blue_sky_360p_60f | svtav1 | 20  | 1564.87 | 44.091
blue_sky_360p_60f | svtav1 | 20  | 1565.27 | 44.092
blue_sky_360p_60f | svtav1 | 20  | 1565.02 | 44.090
blue_sky_360p_60f | svtav1 | 20  | 1564.83 | 44.093
blue_sky_360p_60f | svtav1 | 20  | 1564.99 | 44.091
blue_sky_360p_60f | svtav1 | 20  | 1565.27 | 44.092
blue_sky_360p_60f | svtav1 | 20  | 1564.88 | 44.091
blue_sky_360p_60f | svtav1 | 20  | 1565.00 | 44.091
blue_sky_360p_60f | svtav1 | 20  | 1565.00 | 44.091
blue_sky_360p_60f | svtav1 | 20  | 1565.16 | 44.090
blue_sky_360p_60f | svtav1 | 20  | 1564.37 | 44.088
blue_sky_360p_60f | svtav1 | 20  | 1564.76 | 44.094

Command line used:
./SvtAv1EncApp -i blue_sky_360p_60f.yuv -w 640 -h 360 -fps-num 25000 -fps-denom 1000 -q 20 -b blue_sky_640x360_60f_svtav1_cq20.ivf -o blue_sky_640x360_60f_svtav1_cq20.yuv -intra-period 119 -bit-depth 8 -enc-mode 0 -n 60

**Comment by hassount** [comment]
This seems to be related to #258

**Comment by AlexBoswellVCD** [comment]
I ran this test case 15 times and didn't see a r2r issue.

@JackZhouVCD  also crawled through the entire objective-1-fast test set with all encode modes and only saw the r2r issue in M1 and M3.

**Comment by hassount** [comment]
Closing this, please reopen if there's still a r2r
