### ISSUE TITLE
Docs for developers

### ISSUE THREAD

**Issue by BlauerHunger** [OpenVisualCloud/SVT-AV1#369]
I'm currently missing a guide that helps devs getting started with working with this project, such as a data flow diagram/explanation of the encoder and extensive documentation for the functions used. This would most likely massively reduce the time needed to get started contributing to this great project.

**Comment by hassount** [comment]
This is now available:
https://github.com/OpenVisualCloud/SVT-AV1/blob/master/Docs/README.md
we can now open issues specific to pieces where help is needed
