### ISSUE TITLE
Preset Tuning [M1-M8]

### ISSUE THREAD

**Issue by hassount** [OpenVisualCloud/SVT-AV1#379]
Working on tuning the M1-M8 presets: 
Working branches: 
https://github.com/OpenVisualCloud/SVT-AV1/tree/mx_tune
https://github.com/OpenVisualCloud/SVT-AV1/tree/mx_tune_m0_test

**Comment by EwoutH** [comment]
@hassount Would it be possible to rebase the branches?

**Comment by hassount** [comment]
@EwoutH yes, we'll work on rebasing the branches over the next coupld of weeks until all the feature PRs get in
