### ISSUE TITLE
Encoding will erratically abort: interlace type not supported

### ISSUE THREAD

**Issue by rbultje** [OpenVisualCloud/SVT-AV1#385]
I'm seeing erratic (not reliably reproduceable) encoding problems:

```
$ cat input.y4m | SvtAv1EncApp -i stdin -b output.ivf -n 151 -rc 0 -q 36 -intra-period 120 -lp 4 -tile-rows 0 -tile-columns 0 -enc-mode 5
SVT-AV1 Encoder
Error found when reading the y4m file parameters.
Error in configuration, could not begin encoding! ...
Run SvtAv1EncApp -help for a list of options
Encoder finished
interlace type not supported
```

`-n 151` is a workaround for #382. This problem happens in maybe 2% of the cases or so (rough estimate). Typically, if I restart it, it will run fine. The input file is not interlaced.

**Comment by hassount** [comment]
@rbultje 
Thank you for signalling the issue, do you see this with any y4m or with a specific .y4m ?

**Comment by rbultje** [comment]
Any.

**Comment by JacksonDagger** [comment]
I could not reproduce this running `cat mother_daughter_qcif.y4m  | ./SvtAv1EncApp -i stdin -b mdtest.ivf -n 300 -intra-period 120 -lp 4 -tile-rows 0 -tile-columns 0 -enc-mode 6 -q 36` 100 times

**Comment by hassount** [comment]
closing this for now, @rbultje please feel free to re-open if you continue to see this behavior
