### ISSUE TITLE
ffmpeg  Conversion failed

### ISSUE THREAD

**Issue by RR2301** [OpenVisualCloud/SVT-AV1#398]
HI
I am getting the following error. Can some one suggest why the conversion is failing..

Command
`
pi@raspberrypi:~ $ ffmpeg -thread_queue_size 512 -rtsp_transport tcp -i "rtsp://home:HomeXXXX@192.168.1.XX:554/cam/realmonitor?channel=4&subtype=0" -f lavfi -i aevalsrc=0 -c:a libmp3lame http://127.0.0.1:8090/video.ffm
'
Result

`
'ffmpeg version 3.2.14-1deb9u1+rpt1 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
configuration: --prefix=/usr --extra-version='1deb9u1+rpt1' --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-omx-rpi --enable-mmal --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --arch=armhf --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
libavutil 55. 34.101 / 55. 34.101
libavcodec 57. 64.101 / 57. 64.101
libavformat 57. 56.101 / 57. 56.101
libavdevice 57. 1.100 / 57. 1.100
libavfilter 6. 65.100 / 6. 65.100
libavresample 3. 1. 0 / 3. 1. 0
libswscale 4. 2.100 / 4. 2.100
libswresample 2. 3.100 / 2. 3.100
libpostproc 54. 1.100 / 54. 1.100
Input #0, rtsp, from 'rtsp://home:HoXXXXX@192.168.1.XX:554/cam/realmonitor?channel=4&subtype=0':
Metadata:
title : Media Server
Duration: N/A, start: 0.298000, bitrate: N/A
Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 2304x1296 [SAR 1:1 DAR 16:9], 20 fps, 20 tbr, 90k tbn, 40 tbc
Input #1, lavfi, from 'aevalsrc=0':
Duration: N/A, start: 0.000000, bitrate: 2822 kb/s
Stream #1:0: Audio: pcm_f64le, 44100 Hz, mono, dbl, 2822 kb/s
[swscaler @ 0x73c440] deprecated pixel format used, make sure you did set range correctly
[libvpx @ 0x732df0] v1.6.1
Output #0, ffm, to 'http://127.0.0.1:8090/video.ffm':
Metadata:
title : Media Server
creation_time : now
encoder : Lavf57.56.101
Stream #0:0: Audio: vorbis (libvorbis), 22050 Hz, mono, fltp, 64 kb/s
Metadata:
encoder : Lavc57.64.101 libvorbis
Stream #0:1: Video: vp8 (libvpx), yuv420p, 720x486 [SAR 6:5 DAR 16:9], q=10-42, 400 kb/s, 20 fps, 1000k tbn, 30 tbc
Metadata:
encoder : Lavc57.64.101 libvpx
Side data:
cpb: bitrate max/min/avg: 0/0/0 buffer size: 800000 vbv_delay: -1
Stream mapping:
Stream #1:0 -> #0:0 (pcm_f64le (native) -> vorbis (libvorbis))
Stream #0:0 -> #0:1 (h264 (native) -> vp8 (libvpx))
Press [q] to stop, [?] for help
av_interleaved_write_frame(): Connection reset by peer0.03 bitrate=1966.0kbits/s dup=1 drop=0 speed=0.0211x

**Error writing trailer of http://127.0.0.1:8090/video.ffm: Connection reset by peerframe= 2 fps=1.2 q=0.0 Lsize= 32kB time=00:00:00.03 bitrate=7864.2kbits/s dup=1 drop=0 speed=0.02x video:21kB audio:0kB subtitle:0kB other streams:0kB global headers:4kB muxing overhead: 53.243229%** Conversion failed!

**Comment by 1480c1** [comment]
Not the place for general ffmpeg

**Comment by hassount** [comment]
@RR2301  Please refer to https://ffmpeg.org/bugreports.html to report ffmpeg issues.
