### ISSUE TITLE
Issue with building with -mavx

### ISSUE THREAD

**Issue by eclipseo** [OpenVisualCloud/SVT-AV1#399]
While packaging for Fedora, the build flag -mavx is causing problem because it is not in the default allowed build flags for Fedora. I have asked an exception due to the nature of the encoder but the packaging committee is asking that you consider other options:

* gcc and glibc provides for alternate functions which automatically get used on the relevant CPU types. For example, see https://lwn.net/Articles/691932/. That is what I would expect an upstream to do. It may be possible to just patch in a few __attribute__((target_clones("avx", "default"))) lines in front of the critical functions.

* Alternatively do a local patch to check __cpuid in main to print a usable message (akin to "sorry, you've installed this on hardware where it won't run"), so that the process don't just get SIGILL and die.

**Comment by 1480c1** [comment]
May I ask for something like a documentation on what is allowed and not for packaging for fedora?

Do you mean using mavx as a GCC flag?

**Comment by 1480c1** [comment]
Is it used?

**Comment by 1480c1** [comment]
I remember removing it from the cmakelists and adding an option to remove March=native

**Comment by eclipseo** [comment]
> Do you mean using mavx as a GCC flag?

Yes, it is passed in v0.5.0 CMakeLists https://github.com/OpenVisualCloud/SVT-AV1/blob/3009e99f32e3476e028aadd17a265630f80a8e36/CMakeLists.txt#L33

I now realize this has moved to march=native

Fedora is conservative with its build flags to support old CPU.

Would not using march=native impacts the performance greatly?

**Comment by 1480c1** [comment]
Although I'm not near a computer to test, I would not think so ( depending on hardware), although for packaging, `-march=native` should definitely not be allowed

**Comment by eclipseo** [comment]
Ok thank you for your time.

**Comment by 1480c1** [comment]
Unless @hassount decides to release a 0.6.0 or 0.5.1 with the current cmakelists, it's probably best to generate a patch for 0.5.0 to remove mavx and march and insert the proper flags for the other cmakelists

**Comment by eclipseo** [comment]
I'm packaging GIT master because I had issue with building the decoder on 0.5.0. But I checked the CMakeLists on 0.5.0 initially that's why I thought it needed -mavx.

**Comment by hassount** [comment]
we're working on cleaning up the code, fixing the warnings and update the new presets to get a 0.6.0
