### ISSUE TITLE
Abnormality of Chroma in a video with intense movement.

### ISSUE THREAD

**Issue by f11894** [OpenVisualCloud/SVT-AV1#400]
SVT-AV1 ac75c3e

Commandline
``ffmpeg -i park_joy_1080p50_2s.y4m  -an -nostdin -pix_fmt yuv420p -f yuv4mpegpipe - | SvtAv1EncApp -i stdin -n 100 -enc-mode 8 -intra-period 63 -q 44 -b park_joy_1080p50_2s_svt-av1_q44.ivf``

input video
https://people.xiph.org/~tdaede/sets/video-hd-1/
park_joy_1080p50_2s.y4m

output video
https://drive.google.com/open?id=1XRxUqw-nuiX4KjyHwkg0JUHMneihqI4C
![名称未定-2](https://user-images.githubusercontent.com/16046279/59915217-152f5580-9457-11e9-84ba-347668e79a8f.png)

**Comment by colleenkhenry** [comment]
I see this too :)
