### ISSUE TITLE
Crash on Big Buck Bunny video

### ISSUE THREAD

**Issue by baerbock** [OpenVisualCloud/SVT-AV1#407]
I've tried to run

`ffmpeg -i BigBuckBunny.mp4 -c:v libsvt_av1 -g 30 -vframes 1000 -y test.ivf`

on http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4

→ crash

**Comment by jbeich** [comment]
I can't reproduce. Can you include ffmpeg's console output and gdb/lldb backtrace?

**Comment by baerbock** [comment]
@jbeich My ffmpeg had conflicting libaom and libsvt-av1 (despite being compiled just a few days ago from git-master).
