### ISSUE TITLE
Make Travis fail on warnings

### ISSUE THREAD

**Issue by hassount** [OpenVisualCloud/SVT-AV1#419]
After fixing #417 we would like to impose that checks do not pass if there are warnings in the build.

We need to add such to travis only where the build fails on any warning and rebase all PRs to make sure we don't introduce any warnings in the master anymore.

**Comment by hassount** [comment]
@kylophone @EwoutH @1480c1 
Could one of you help with a PR to force Travis to fail if there are warnings in the build ?

**Comment by 1480c1** [comment]
Possible to add werror to CFLAGS before running cmake

**Comment by 1480c1** [comment]
I can try once I wake up

**Comment by hassount** [comment]
Thank you @1480c1 👍
