### ISSUE TITLE
Mux error

### ISSUE THREAD

**Issue by tnti** [OpenVisualCloud/SVT-AV1#42]
The following prompt appears with ffmpeg mux:
https://drive.google.com/open?id=14tZp6iQ4woHthNIMrPG94jZujtLSNzfE

**Comment by jsunintel** [comment]
I tried to derive the reproducing steps from the picture attached, but failed. I can't reproduce this issue. Could you please attach here the full reproducing steps?

**Comment by jsunintel** [comment]
./ffmpeg_g  -video_size 1920x1080 -pixel_format yuv420p -f rawvideo -i /work/clips/matrix_1920x1080_250i.yuv -c:v libsvt_av1 -vframes 5 test.ivf -y
./ffmpeg_g  -video_size 1920x1080 -pixel_format yuv420p -f rawvideo -i /work/clips/matrix_1920x1080_250i.yuv -c:v libsvt_av1 -vframes 5 test.mp4 -y

./ffmpeg -i /work/test.ivf -pix_fmt yuv420p -y ivf.yuv
./ffmpeg -i /work/test.mp4 -pix_fmt yuv420p -y mp4.yuv

No error or warning observed.

I need your steps.

**Comment by tnti** [comment]
Example command line:
"D:\Encoder\FFMPEG\ffmpeg.exe" -loglevel level+error -i "%~dpn1.avs" -strict -1 -f rawvideo -nostdin - | "D:\Encoder\SVT-AV1\SvtAv1EncApp" -i stdin -enc-mode 3 -w 1280 -h 720 -bit-depth 8 -fps-num 24000 -fps-denom 1001 -q 3. -rc 0 -max-qp 63 -min-qp 0 -lad 50 -n 200 -b "%~dpn1_SVT-AV1.ivf"

"D:\Encoder\FFMPEG\ffmpeg.exe" -i "%~dpn1.ivf" -c:v copy -strict -2 -y "%~dpn1_muxed.mp4"

**Comment by tnti** [comment]
https://github.com/OpenVisualCloud/SVT-AV1/issues/33

**Comment by jsunintel** [comment]
According to your steps, the SvtAv1EncApp binay tool is used to encode AV1 with ivf container, but not the SVT AV1 plugin for ffmpeg. I am in charge of debugging ffmpeg plugin issues only. Please find the right owner for this.
