### ISSUE TITLE
Provide reference decoder output

### ISSUE THREAD

**Issue by rxuniverse** [OpenVisualCloud/SVT-AV1#422]
It would be helpful for testing decoder compatiblity for this encoder.

**Comment by hassount** [comment]
@rxuniverse 
Can you elaborate a little more here, is this for the svt-av1 decoder / encoder ? you need logs / yuvs ? add it in the ci?

**Comment by rxuniverse** [comment]
My team is developikng a decoder, and we want to verify that it works with
streams encoded by svt-av1. I am looking for a reference decoder output for
encoding, that would be in yuv format.

I think I overlooked the fact that there is a decoder included as well, so
if the encoder does not provide such reference decoder output directly, I
can use your decoder to decode the stream and use it as the reference.

**Comment by digitalTrilunaire** [comment]
Maybe what you are looking for is just the `-o` argument that is listed here https://github.com/OpenVisualCloud/SVT-AV1/blob/master/Docs/svt-av1_encoder_user_guide.md ?

**Comment by rxuniverse** [comment]
Youare right, this is what I am looking for. ThANks!
