### ISSUE TITLE
Rainbow color artifacts

### ISSUE THREAD

**Issue by maikmerten** [OpenVisualCloud/SVT-AV1#424]
version: git master 9e67b31961c59166cbeca85b9838061607c9ad09 
os: Ubuntu 19.04, 64 bit, x86-64

My test encodes with SVT-AV1 have some very nice rainbow-colored artifacts.

Input file: https://media.xiph.org/video/derf/y4m/park_joy_420_720p50.y4m

Encoded file: https://people.xiph.org/~maikmerten/av1/svt/parkjoy-720p-svt-rainbow.av1

Transcoded to what I'm seeing: https://people.xiph.org/~maikmerten/av1/svt/parkjoy-720p-svt-rainbow.av1.transcode.webm

Encoder parameters and output:  https://people.xiph.org/~maikmerten/av1/svt/parkjoy-720p-svt-rainbow.av1.txt

I'm using ffmpeg to what the file. Ubuntu's ffmpeg is configured to decode AV1 using libaom and appears to produce nominal results with test files created with other encoders.

edit: Appears to be a duplicate of https://github.com/OpenVisualCloud/SVT-AV1/issues/400 - which I missed. Sorry for the noise.

**Comment by kylophone** [comment]
Closing this for now to avoid duplication. This is being tracked in #400.
