### ISSUE TITLE
Appveyor artifcts

### ISSUE THREAD

**Issue by hassount** [OpenVisualCloud/SVT-AV1#425]
@1480c1 
starting from this commit / PR #276, Appveyor does not upload any artifacts after the build, any thoughts ?

_Originally posted by @hassount in https://github.com/OpenVisualCloud/SVT-AV1/pull/276#issuecomment-507819775_

**Comment by 1480c1** [comment]
Due to ide CMAKE_BUILD_TYPE being set to 'Release;Debug', the binaries are located in 'bin/Release/Debug' probably

**Comment by 1480c1** [comment]
Not anywhere nearby a computer with vs setup to test, will investigate more later

**Comment by hassount** [comment]
@1480c1 yes, it seems that it is the case. It also seems that this commit is causing a speed regression in M8 (will open another issue to track this).
Would you be able to address the folder structure of the binaries destination as it makes more sense to have Debug / Release under /Bin rather than /Bin/Release/Debug ...

**Comment by 1480c1** [comment]
Unsure how to properly override the cmake_build_type with only one without it being reset, might need some cmake trickery

**Comment by EwoutH** [comment]
@1480c1 Would you suggest fixing this in CMake or in AppVeyor? `bin/Release/Debug` is not a logical location to put builds.

**Comment by 1480c1** [comment]
I would say CMake would be the ideal place, but for a fix, appveyor would be easiest

**Comment by 1480c1** [comment]
I have a fix for appveyor side, however, I still am unable to force  CMake to use only `bin/Release` even when using the `CMAKE_CONFIGURATION_TYPES`
