### ISSUE TITLE
If scene change detection is enabled, it can not encode normally.

### ISSUE THREAD

**Issue by f11894** [OpenVisualCloud/SVT-AV1#441]
SVT-AV1 8977f44

input video
https://drive.google.com/open?id=17lh4I8wZ1rELRY04ysOz7kxDWF-hIfvh

output video
https://drive.google.com/open?id=12eWol2s-yyxIQxeDYlE8BgzyrTFw5WBw

Commandline
``SvtAv1EncApp.exe -i Big_Buck_Bunny_scd1.y4m -enc-mode 8 -intra-period 23 -scd 1 -q 30 -n 240 -b Big_Buck_Bunny_scd1.ivf``

（c）copyright 2008、Blender Foundation / www.bigbuckbunny.org

**Comment by AlexBoswellVCD** [comment]
Could you please provide more detail on what you mean it not encoding normally?

I tried encoding using your command at that commit, and then when I tried to decode using the aom decoder I get the following:
Warning: Failed to decode frame 22: Corrupt frame detected
Warning: Additional information: Failed to decode tile data

**Comment by JacksonDagger** [comment]
I ran this. The issue is that inter frames after the scene change seem to reference frames before the scene change. This results in artifacts in the scene that are clearly from the previous scene

**Comment by hassount** [comment]
@OmranAbdelkafi can we close the scene change detection flag for now?
