### ISSUE TITLE
AWCY runs are failling since 2bebd2d

### ISSUE THREAD

**Issue by EwoutH** [OpenVisualCloud/SVT-AV1#466]
Somewhere between 9e67b31 and 2bebd2d the [AWCY](https://beta.arewecompressedyet.com/?) started to fail. It's not on the AWCY side, since older commits (before 9e67b31 run fine). [Examples](https://beta.arewecompressedyet.com/?job=SVT-AV1-enc-mode-3%402019-06-29&job=SVT-AV1-enc-mode-8%402019-07-02-0.6.0&job=SVT-AV1-enc-mode-8%402019-06-29-2).

**Comment by hassount** [comment]
@EwoutH 
I am not able to see the issue on AWCY keeps loading for ever. Can you help describing the fail ? a segfault, a dead-lock .. 
we have fixed a segfault and a chroma corruption after 0.6.0, did you test the head?

**Comment by kylophone** [comment]
This has been addressed. soname mismatch was causing the problem.
