### ISSUE TITLE
[SVT AV1]The output stream playback screen is green screen with setting "-tile-rows" and "-tile-columns" to encode in encMode[0] for 1920x1080 and 1280x720 resolution.

### ISSUE THREAD

**Issue by GuCaixuan** [OpenVisualCloud/SVT-AV1#473]
[Test environment]
 OS： Ubuntu 18.04.2 LTS
 SVT CommitID: d2e95a3
 
[Issue Description]
When we use SvtAv1EncApp to do encoding with setting "-tile-rows" and "-tile-columns" in encMode[0] for 1920x1080 and 1280x720 resolution, we found that the output streams playback failed, the playback screen is a green screen.

This issue does not occur in below situations:
1. encMode[1-8] for 1920x1080 and 1280x720 resolution
2. encMode[0-8] for 4096x2160 and 720x480 resolution

The command line we used is:
SvtAv1EncApp -i Fallout4_1920x1080_8bit_60Hz_P420.yuv  -b tile_test_M0_Fallout4_1920x1080_8bit_60Hz_P420_Q45_0_1.bin  -w 1920  -h 1080  -bit-depth 8  -fps 60  -intra-period 55  -n 20  -enc-mode 0  -compressed-ten-bit-format 0  -q 45  -tile-columns 1  -rc 0  -tile-rows 0

SvtAv1EncApp -i DucksTakeOff_1280x720_8bit_50Hz_P420.yuv  -b tile_test_M0_DucksTakeOff_1280x720_8bit_50Hz_P420_RC3_1126173bps_4_6.bin  -w 1280  -h 720  -bit-depth 8  -fps 50  -intra-period 47  -n 20  -enc-mode 0  -tbr 1126173  -compressed-ten-bit-format 0  -tile-columns 6  -rc 3  -tile-rows 4

**Comment by lijing0010** [comment]
sb_sz/sb_size_pix/sb_tot_cnt/sb_total_count is a mess across PCS and SCS.
Max super_block is 128 for M0 and 64 for others, that's the reason why M0 crashed.
Will clean up those SB size/count related later

**Comment by chkngit** [comment]
issue has been addressed in Branch R2R_Debug  via #define  TILE_ATB_FIX   1
