### ISSUE TITLE
ffmpeg plugin missing tile-colums/rows and threads options, broken -rc vbr

### ISSUE THREAD

**Issue by brion** [OpenVisualCloud/SVT-AV1#482]
Currently in the ffmpeg plugin patch, `-tile-columns` and `-tile-threads` options are not made available, `-threads` is ignored, and `-rc vbr` fails due to use of deprecated type 1 instead of 2.

https://github.com/brion/FFmpeg/commit/272f3377aec5576ba2a2c681788f112ad35797cc attempts to fix these (patch against the patched version), and seems to work in local testing.

Is there a primary repo with the ffmpeg source I can submit a PR against, or should I PR against a copy of the patch in this repo?

Thanks!

**Comment by 1480c1** [comment]
probably @jsunintel can comment more, but probably a pr against the patch in this repo

**Comment by jsunintel** [comment]
-threads is not supposed to get supported, for that parameter defined in FFmpeg is with the max of 16. And SVT-HEVC usually works with hundreds of threads. We added a new parameter "-thread-count" and please have a try: https://github.com/OpenVisualCloud/SVT-HEVC/pull/330/.

-rc issue is already fixed.

I will be checking the tile parameters.

FFmpeg communication is mainly through emails. Nowhere to submit PR request. The mail list is ffmpeg-devel@ffmpeg.org.

**Comment by xuguangxin** [comment]
@brion , rc issue addressed by https://github.com/OpenVisualCloud/SVT-AV1/pull/1352
tile support added by https://github.com/OpenVisualCloud/SVT-AV1/pull/1356
Any more params we need to expose?

thanks

**Comment by xuguangxin** [comment]
@brion, please create another issue if something still missed.
thanks
