### ISSUE TITLE
Issue encoding 10-bit input video with -hbd-md 0

### ISSUE THREAD

**Issue by mafonsoN** [OpenVisualCloud/SVT-AV1#510]
Current svt-av1 produces an error and serious artifacts on the top left corner, which indicate a bug. In addition, there is a mismatch between the reconstructed output from svt-av1 encoder and aomdec. 

Command line:
`./SvtAv1EncApp -i Campfire_1920x1080_30fps_10bit_420.yuv -o Campfire_3840x2160_30fps_10bit_1920x1080_QP30_svtav1.yuv -w 1920 -h 1080 -q 30 -fps-num 30000 -fps-denom 1000 -n 1 -b Campfire_3840x2160_30fps_10bit_1920x1080_QP30_svtav1.ivf -intra-period 63 -bit-depth 10 -scd 0 -enc-mode 0 -n 1 -hbd-md 0`

Output:
```
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:	SVT-AV1 Encoder Lib v0.6.0
SVT [build]  :	GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)	 64 bit
LIB Build date: Jul 31 2019 10:36:27
-------------------------------------------
Number of logical cores available: 8
Number of PPCS 72
-------------------------------------------
SVT [config]: Main Profile	Tier (auto)	Level (auto)
SVT [config]: EncoderMode 							: 0
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat	: 10 / 1 / 0
SVT [config]: SourceWidth / SourceHeight					: 1920 / 1080
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType 	: 30000 / 1000 / 64 / 1
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure		: 4 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange			: CQP / 30 / 33 / 0
-------------------------------------------
Encoding         1
SUMMARY --------------------------------- Channel 1  --------------------------------
Total Frames		Frame Rate		Byte Count		Bitrate
           1		30.00 fps		    294982		70795.68 kbps


Channel 1
Average Speed:		0.009 fps
Total Encoding Time:	108956 ms
Total Execution Time:	110939 ms
Average Latency:	108947 ms
Max Latency:		108947 ms
SvtAv1EncApp(64022,0x7fff895eb380) malloc: *** error for object 0x1b5c35140: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

```

--------

Reconstructed frame
![Campfire-8-bit-decisions](https://user-images.githubusercontent.com/44611410/62331984-988a9080-b472-11e9-8975-720d68d60059.png)

- encoding a single frame 
- high-bitdepth mode decision disabled (default)
- found in enc-mode 0 only

When using the 10 bit path (-hbd-md 1) this error doesn't happen.

Tests with more settings and sequences planned.

**Comment by Cidana-Developers** [comment]
Crash issue occurs with 10-bit encoding, commit id: 97d9dc625236c1cf83ea20315dfa985001837698:
Cmd line:
```
$: SvtAv1EncApp -i Netflix_Aerial_1920x1080_60fps_10bit_420_60f.y4m -enc-mode 8 -o recon.yuv -stat-report 1 -b output.ivf
```
Platform: Linux

output:
```
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:	SVT-AV1 Encoder Lib v0.6.0
SVT [build]  :	GCC 5.4.0	 64 bit
LIB Build date: Aug  6 2019 19:13:42
-------------------------------------------
Number of logical cores available: 12
Number of PPCS 72
-------------------------------------------
SVT [config]: Main Profile	Tier (auto)	Level (auto)
SVT [config]: EncoderMode 							: 8
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat	: 10 / 1 / 0
SVT [config]: SourceWidth / SourceHeight					: 1920 / 1080
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType 	: 60 / 1 / 64 / 1
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure		: 4 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange			: CQP / 50 / 33 / 0
-------------------------------------------
Encoding        60
SUMMARY --------------------------------- Channel 1  --------------------------------
Total Frames		Frame Rate		Byte Count		Bitrate
          60		60.00 fps		    645806		5166.45 kbps

Average QP		Y-PSNR			U-PSNR			V-PSNR
      45.72		36.73 dB		   42.17dB		42.94dB


Channel 1
Average Speed:		18.490 fps
Total Encoding Time:	3245 ms
Total Execution Time:	4040 ms
Average Latency:	2520 ms
Max Latency:		3157 ms
Segmentation fault (core dumped)
```

**Comment by joelsole** [comment]
@mafonsoN  This seems related to RDOQ for 10-bit content, for AVX2. For a couple of tests, there was no problem when I disable it: https://github.com/joelsole/SVT-AV1/tree/fix_bug_510 

Some tests for ASM quant (QuantAsmTest.cc) are failing.

@hassount  @ttrigui  Would you be able to fix this fast? If not, in the meantime, we could just disable RDOQ for 10-bit content, as above?

**Comment by hassount** [comment]
@joelsole, we can just disable RDOQ for 10bit for now while we work on addressing this issue

**Comment by hassount** [comment]
Is this now addressed bug merging #797 ? @mafonsoN can we validate such ?

**Comment by mafonsoN** [comment]
@hassount No artifacts but still getting the same malloc message using the latest master:
`SvtAv1EncApp(6208,0x7fff8a43d380) malloc: *** error for object 0x7fea1fff7000: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6`

**Comment by intelmark** [comment]
Unable to duplicate exact same artifact mentioned in the original command line, however upper left artifact is visible.


![campfire](https://user-images.githubusercontent.com/50715202/74173396-467bb200-4bef-11ea-85f9-beb1df4f8439.png)
SvtAv1EncApp -i C:/testfiles/Campfire_1280x720_30fps_8bit_bt709_420_videoRange_60f_10b.yuv -o c:/testfiles/Campfire_1280x720_30fps_10bit_1280x720_QP30_svtav1.yuv -w 1280 -h 720 -q 30 -fps-num 30000 -fps-denom 1000 -n 1 -b C:/testfiles/Campfire_1280x720_30fps_10bit_1280x720_QP30_svtav1.ivf -intra-period 63 -bit-depth 10 -scd 0 -enc-mode 0 -n 1 -hbd-md 0

**Comment by hassount** [comment]
@mafonsoN 
can you validate that this issue is now resolved ?

**Comment by mafonsoN** [comment]
@hassount the original command line works fine now. No artifacts.
