### ISSUE TITLE
[SIMD] Optimization tasks

### ISSUE THREAD

**Issue by ttrigui** [OpenVisualCloud/SVT-AV1#512]
**BUG FIXES**
- [x] Fix a crash associated with multi-channel: https://github.com/spawlows/SVT-AV1/commit/bd31221c27ae9935d553eb5e0a0a5bd78a5c5721 ( Not applicable anymore to master due to different ways of memory allocation)
- [x] Fix a crash in M4: https://github.com/spawlows/SVT-AV1/commit/f6e149b3a9ccedf7196557c2cf7a0297531af7e4  ( Not applicable anymore to master due to different ways of memory allocation)
- [x] Fix a r-2-r : https://github.com/spawlows/SVT-AV1/commit/99c64934283f8968d29daeb69efb57488d278752 : To check if fix exists in master and if applicable
- [x] Fix a mismatch between windows and linux (debug) :https://github.com/OpenVisualCloud/SVT-AV1/pull/452 : merged to master
- [x] Fix UT mismatch/fails.

**AVX2**
- [x] av1_get_gradient_hist_avx2 : Merget to master (Commit: https://github.com/OpenVisualCloud/SVT-AV1/commit/84e6eac9388b50dc75e7e8fbed2e0acf55d1dcb4 )
- [x] Bring from AOM or write optimized version for  variance_highbd_c
- [x] Check SATD code in AOM

***C***
- [x] construct_best_sorted_arrays_md_stage_2:  (Partial merged to master. Left changes in PR https://github.com/OpenVisualCloud/SVT-AV1/pull/592 )
- [x] construct_best_sorted_arrays_md_stage_3:  (Partial merged to master. Left changes in PR https://github.com/OpenVisualCloud/SVT-AV1/pull/592 )
- [x] av1_cost_coeffs_txb: PR https://github.com/OpenVisualCloud/SVT-AV1/pull/515 (Merged to master)
- [x] interp_cubic: (Merged to master. Partial modified during further changes in commit: https://github.com/OpenVisualCloud/SVT-AV1/commit/4f180cce01c74a91e2f5c9f95a31eac5a315c0f2 ) 

- [x] Removed memcpy and conversion from 8 bit to 16 bit in dlf_kernel() PR https://github.com/OpenVisualCloud/SVT-AV1/pull/531 (Merged to master)
- [x] Removed memcpy before call av1_inv_transform_recon() in inv_transform_recon_copy() PR https://github.com/OpenVisualCloud/SVT-AV1/pull/529 (Merged to master)

**Comment by ttrigui** [comment]
@spawlows let's use this issue to track status. Please modify according to progress and add any missing tasks/kernels.

**Comment by hassount** [comment]
@ttrigui 
can we check that all of these are addressed and close the issue if we can

**Comment by spawlows** [comment]
All topics from this issue are done, and it can be closed.

**Comment by ttrigui** [comment]
> @ttrigui
> can we check that all of these are addressed and close the issue if we can

yes.
