### ISSUE TITLE
error: unrecognizable insn in EbHighbdIntraPrediction_AVX512.c

### ISSUE THREAD

**Issue by mafonsoN** [OpenVisualCloud/SVT-AV1#513]
I am getting a build error on the latest master on my linux machine when I build SVT in debug mode `./Build/linux/build.sh debug`.

![Screen Shot 2019-08-02 at 13 19 58](https://user-images.githubusercontent.com/44611410/62396539-4310bb00-b528-11e9-8b98-a9dcf0d8c617.png)

PC details:

```
$ uname -a
Linux lg4kenc104 4.4.0-143-generic #169-Ubuntu SMP Thu Feb 7 07:56:38 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

```processor      Intel(R) Xeon(R) Platinum 8170 CPU @ 2.10GHz```

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
```

@kirithika7 Any ideas about this?

**Comment by Cidana-Developers** [comment]
I encountered the same issue too, work around it by using gcc-7.

**Comment by mafonsoN** [comment]
> I encountered the same issue too, work around it by using gcc-7.

Thanks @Cidana-Developers, using gcc-7 instead works.

**Comment by hassount** [comment]
Closing this, seems to work on all gcc versions now through travis
