### ISSUE TITLE
Some of the intra-prediction intrinsics write to extra memory

### ISSUE THREAD

**Issue by nijilk** [OpenVisualCloud/SVT-AV1#518]
The following intra-prediction intrinsic functions seem to write into extra memory, which can cause memory corruption.

aom_v_predictor_8x8_sse2
aom_h_predictor_8x8_sse2
aom_dc_128_predictor_8x8_sse2
aom_dc_top_predictor_8x8_sse2
aom_dc_left_predictor_8x8_sse2
aom_dc_predictor_8x8_sse2

Note that, this list may not contain all the intrinsic functions with similar issue.

**Comment by ttrigui** [comment]
@spawlows can you please look into this?

**Comment by spawlows** [comment]
I will check this.

**Comment by spawlows** [comment]
@Jayashri @nijilk Do you think that this issue is done in #847 ?

**Comment by nijilk** [comment]
> 
> 
> @jayashri @nijilk Do you think that this issue is done in #847 ?

@spawlows Yes. We have fixed the issues. Please review once and close.
