### ISSUE TITLE
gstreamer: Emit GStreamer error message when returning GST_FLOW_ERROR

### ISSUE THREAD

**Issue by ocrete** [OpenVisualCloud/SVT-AV1#521]
In GStreamer, it's required to push an error GstMessage when returning GST_FLOW_ERROR, it can be accomplished with the GST_ELEMENT_ERROR() macro.

Ref: https://github.com/OpenVisualCloud/SVT-AV1/blob/97d9dc625236c1cf83ea20315dfa985001837698/gstreamer-plugin/gstsvtav1enc.c#L696

**Comment by tianjunwork** [comment]
Hi @ocrete, thank you, we will take a look.

**Comment by hassount** [comment]
@tianjunwork has this been addressed ?

**Comment by tianjunwork** [comment]
Oops, forgot this request. Will do.

**Comment by tianjunwork** [comment]
Hi @ocrete , I didn't find the documented requirement of using GST_ELEMENT_ERROR for GST_FLOW_ERROR. Could you kindly point it to me? Also seems that plugins in gst-plugins-good are not following that requirement. Thank you.

**Comment by ocrete** [comment]
@tianjunwork The documentation is indeed lacking about this. It's somewhat documented with in the GST_FLOW_ERROR entry at  https://gstreamer.freedesktop.org/documentation/gstreamer/gstpad.html?gi-language=c#GstFlowReturn
And even less at https://gstreamer.freedesktop.org/documentation/gstreamer/gstelement.html?gi-language=c#GST_ELEMENT_ERROR
This is definitely an area of our documentation that we should improve.

**Comment by tianjunwork** [comment]
@ocrete thank you for the quick reply. 
`GST_FLOW_ERROR (-5) – Some (fatal) error occurred. Element generating this error should post an error message with more details.`  
Just to make sure, your suggestion is to use `GST_ELEMENT_ERROR()` instead of simply using `GST_ERROR_OBJECT` to print error message.

**Comment by ocrete** [comment]
Yes, GST_ELEMENT_ERROR() is the right way to do this.

**Comment by tianjunwork** [comment]
@ocrete Thank you. I will make a PR to address it.
