### ISSUE TITLE
Named Pipes not working on SVT-AV1

### ISSUE THREAD

**Issue by moisespr123** [OpenVisualCloud/SVT-AV1#523]
It seems that Named Pipes also doesn't work on SVT-AV1. Named pipes are usually invoked by using `\\.\pipe\NameOfThePipe`.

So, as an example, the command line would be:
`-enc-mode 8 -q 50 -tile-rows 6 -tile-columns 6 -hme 1  -hme-l0 1  -hme-l1 1  -hme-l2 1   -i \\.\pipe\in.y4m -b "C:\temp\ivf-video.ivf"`

The pipe would contain the raw `y4m` stream. This is done programmatically using C# to send bytes asynchronously.

This approach works with other encoders like rav1e and also works with ffmpeg. Unfortunately, it seems it does not work with SVT-AV1, as I get the following:

`Error instance 1: Input yuv does not contain enough frames`

I'm trying to rework my GUI so that it can feed raw .y4m video directly rather than having to generate the y4m stream first and sending it to SVT-AV1.

This is via C# programming.

**Comment by kylophone** [comment]
Half-way fixed. #581 could be merged as soon as Windows support is added.

**Comment by kylophone** [comment]
Closing. Fixed (?) by #581.
