### ISSUE TITLE
Mismatch issue in quantize unit test

### ISSUE THREAD

**Issue by Cidana-Developers** [OpenVisualCloud/SVT-AV1#545]
Step to reproduce:
`./SvtAv1UnitTests --gtest_filter="*Quantize*"`

Console output:
```
[ RUN      ] Quant/QuantizeBTest.input_random_all_q_all/0
/Users/yons/work/SVT-AV1/test/QuantAsmTest.cc:200: Failure
Expected equality of these values:
  qcoeff_ref_[j]
    Which is: 2978
  qcoeff_test_[j]
    Which is: 2979
Q mismatch at position: 109, Q: 4 coeff: 32766
/Users/yons/work/SVT-AV1/test/QuantAsmTest.cc:200: Failure
Expected equality of these values:
  qcoeff_ref_[j]
    Which is: 1424
  qcoeff_test_[j]
    Which is: 1425
Q mismatch at position: 24, Q: 16 coeff: 32767
/Users/yons/work/SVT-AV1/test/QuantAsmTest.cc:200: Failure
Expected equality of these values:
  qcoeff_ref_[j]
    Which is: -1424
  qcoeff_test_[j]
    Which is: -1425
Q mismatch at position: 59, Q: 16 coeff: -32767
/Users/yons/work/SVT-AV1/test/QuantAsmTest.cc:200: Failure
Expected equality of these values:
  qcoeff_ref_[j]
    Which is: 1023
  qcoeff_test_[j]
    Which is: 1024
Q mismatch at position: 128, Q: 25 coeff: 32761
/Users/yons/work/SVT-AV1/test/QuantAsmTest.cc:200: Failure
Expected equality of these values:
  qcoeff_ref_[j]
    Which is: 574
  qcoeff_test_[j]
    Which is: 575
Q mismatch at position: 65, Q: 50 coeff: 32765
/Users/yons/work/SVT-AV1/test/QuantAsmTest.cc:200: Failure
```

Target functions:
```
eb_aom_highbd_quantize_b_64x64_avx2
eb_aom_highbd_quantize_b_32x32_avx2
eb_aom_highbd_quantize_b_avx2
```
It happens when the coefficient are big and the difference is always 1.

**Comment by spawlows** [comment]
QuantizeBTest.input_dcac_minmax_q_n*
QuantizeBTest.input_random_all_q_all*

Above tests fail only for 8 bits.

There is no implementation of eb_aom_quantize_b_*_c_II in AVX2.
there is only implementation for 10bits eb_aom_highbd_quantize_b_*_avx2 .

Reference code in C for 8bit, and 10bit have different algorithm.

In code there are also incorrect assign kernel from 10bits to 8 bits:
eb_aom_quantize_b_32x32 = eb_aom_quantize_b_32x32_c_II;
if (flags & HAS_AVX2) eb_aom_quantize_b_32x32 = eb_aom_highbd_quantize_b_32x32_avx2;

1] There should be implemented of kernels for 8 bits in AVX2,
 or 
2] Data ranges should be limited for 8bit tests. 

@hassount : Could you confirm what solution should be correct?

**Comment by ttrigui** [comment]
As @spawlows stated the c version for 8bit and 10bit are slightly different( we have an extra clamp to clip the coefficient values in the 8bit case) However we are using the same avx2 version for both 8bit and 10bit. In most cases this will work fine but it is safer to align the 8bit avx2 version to its c code to guarantee exactness for the output values.
