### ISSUE TITLE
Segfault with screen content test clip

### ISSUE THREAD

**Issue by KyleSiefring** [OpenVisualCloud/SVT-AV1#559]
Download https://people.xiph.org/~tdaede/sets/objective-1-fast/wikipedia_420.y4m
```
./SVT-AV1/Bin/Release/SvtAv1EncApp -i wikipedia_420.y4m -enc-mode 5 -lp 1 -n 2 -o tmp.ivf
```
Succeeds on enc-mode 6.

**Comment by JacksonDagger** [comment]
I got the same error in Windows on VS17 with the following error message and call stack:

'Exception thrown at 0x00007FF8A6D8197C (ucrtbased.dll) in SvtAv1EncApp.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.'


'''
	SvtAv1Enc.dll!eb_aom_free(void * memblk) Line 86	C
 	SvtAv1Enc.dll!hash_table_clear_all(HashTable * p_hash_table) Line 31	C
 	SvtAv1Enc.dll!av1_hash_table_destroy(HashTable * p_hash_table) Line 111	C
 	SvtAv1Enc.dll!picture_control_set_dctor(void * p) Line 131	C
 	SvtAv1Enc.dll!eb_object_wrapper_dctor(void * p) Line 419	C
 	SvtAv1Enc.dll!eb_system_resource_dctor(void * p) Line 446	C
 	SvtAv1Enc.dll!eb_enc_handle_dctor(void * p) Line 703	C
 	SvtAv1Enc.dll!eb_h265_enc_component_de_init(EbComponentType * svt_enc_component) Line 1880	C
 	SvtAv1Enc.dll!eb_deinit_handle(EbComponentType * svt_enc_component) Line 1900	C
 	SvtAv1EncApp.exe!de_init_encoder(EbAppContext * callback_data_ptr, unsigned int instance_index) Line 643	C
 	SvtAv1EncApp.exe!main(int argc, char * * argv) Line 321	C
 	[External Code]	
'''

**Comment by xuguangxin** [comment]
from the stack, it may be same thing as https://github.com/OpenVisualCloud/SVT-AV1/issues/605

please double check it fixed by https://github.com/OpenVisualCloud/SVT-AV1/pull/606 or not

**Comment by KyleSiefring** [comment]
Seems to be resolve to me.
