### ISSUE TITLE
Mismatch issue found in avc style mcp unit test

### ISSUE THREAD

**Issue by Cidana-Developers** [OpenVisualCloud/SVT-AV1#598]
The interpolation result from avc_style_luma_interpolation_filter_vertical_ssse3_intrin is different with the one from avc_style_luma_interpolation_filter_vertical, which makes functions (i.e. avc_style_luma_interpolation_filter_pos{e, f, g, i, j, k, p, q, r}_ssse3) return wrong result.

**Comment by ttrigui** [comment]
I tested this within your branch add_Mcp_test as the PR for MCP test is not in yet. 
This was the output  error: Expected equality of these values:
  0
  fail_pixel_Count
    Which is: 4096
Mcp test failed,  failed count: 4096 at func: [pose]

I'm not sure that I understand the error message. What was the expected output value? Maybe you can add a little more information to help narrowing down the issue (example: width and height values)

**Comment by Cidana-Developers** [comment]
The mismatch issues is caused by the c implementation, the if_offset in avc_style_luma_interpolation_filter_vertical should be int16_t type instead of uint32_t.

I fixed it in #568 , please kindly review it.

**Comment by JackZhouVCD** [comment]
closed by #568
