### ISSUE TITLE
Improve 10-bit support

### ISSUE THREAD

**Issue by joelsole** [OpenVisualCloud/SVT-AV1#622]
Performance vs libaom for 10-bit seems to be lagging behind that of 8-bit. Some tools are being integrated for 8-bit, while not for 10-bit. To be added in the 10-bit (and higher) path:

- [x] Alt-ref
- [x] Intra-inter compound mode
- [x] Inter-inter compound mode
- [x] RDOQ (bug in intrinsics #510)
- [x] Filter intra
- [x] Interpolation filter search
- [x] ATB inter
- [x] MD
- Predict NSQ Shape (speed increasing feature) (not applicable anymore)
- [x]  ATB Intra
- [x]  Intrinsics for full_distortion_kernel16_bits , sad_16b_kernel
- [x] AUTO-MAX-PARTITION
- [x] Palette
- [x] Global motion (implemented, but not bringing gains)

**Comment by grill05** [comment]
@joelsole This is not really directly related, but could you please give a sample command you are using for testing BD-rate change/speed change for 10-bit(in PR's referenced by this one)? And are the tests with a 10-bit yuv or via pipes?
I ask becau I keep getting crashes when I try to verify the numbers you posted :)

**Comment by joelsole** [comment]
I am following the command lines and yuvs in the videocodectracker.dev
<https://videocodectracker.dev/raw_data_files/all_seqs_svtav1_20191116_6f5338a.json>

cl: https://videocodectracker.dev/command_lines/svtav1_cli_changelog.html
sequences:
https://videocodectracker.dev/raw_data_files/all_seqs_svtav1_20191116_6f5338a.json
