### ISSUE TITLE
Divide by zero in initial_rate_control_kernel

### ISSUE THREAD

**Issue by SmilingWolf** [OpenVisualCloud/SVT-AV1#632]
In the file under Source/Lib/Common/Codec/EbInitialRateControlProcess.c:

- at line 1273 picture_control_set_ptr->processed_leaf_count[cu_depth] is initialized with 0

- is it then immediately used in a division at line 1285, resulting in a division by 0

The code responsible of updating this variable has been removed by commit 4f180cce01c74a91e2f5c9f95a31eac5a315c0f2

The bugged code is reached when setting `-sharp 1` in the cmdline.

**Comment by JackZhouVCD** [comment]
Thanks for reporting the issue, the sharpness feature is not supported in SVT-AV1 and we will eventually be removing it.
