### ISSUE TITLE
-hierarchical-levels 4 Generate conflicts with -sharp 1 at the same time.

### ISSUE THREAD

**Issue by tnti** [OpenVisualCloud/SVT-AV1#64]
Example command line:
"D:\Encoder\FFMPEG\ffmpeg.exe" -loglevel level+error -i "%~dpn1.avs" -strict -1 -f rawvideo -nostdin - | "D:\Encoder\SVT-AV1\SvtAv1EncApp" -i stdin -enc-mode 3 -w 1280 -h 720 -bit-depth 8 -fps-num 24000 -fps-denom 1001 -hierarchical-levels 4 -intra-period 240 -irefresh-type 1 -q 22 -rc 0 -sharp 1 -n 200 -b "%~dpn1_SVT-AV1.ivf"

**Comment by hassount** [comment]
the improve sharpness flag is not currently working properly and should not be used for now. We will update the unused APIs this week.

**Comment by tnti** [comment]
Thanks to the answer of @hassount  .
