### ISSUE TITLE
[SVT-AV1]SvtAv1EncApp fail to encode the YUV file of non-multiple of 8 resolutions

### ISSUE THREAD

**Issue by liweki** [OpenVisualCloud/SVT-AV1#645]
Try to encode one YUV file with resolution 852x480 using the latest SVT-AV1 code ab84224, the encode is failed with error "Error Instance 1: Only multiple of 8 resolutions are supported". Seems the code doesn't do align with non-multiple of 8 resolutions while encoding.

**See below as the detail test command and log:**
./SvtAv1EncApp -i video_852x480.yuv -b video_852x480.av1 -w 852 -h 480 -bit-depth 8  -fps 60  -intra-period 55  -n 20  -compressed-ten-bit-format 0  -q 27  -enc-mode 1  -rc 0

> -------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.6.0
SVT [build]  :  GCC 7.3.0        64 bit
LIB Build date: Sep 25 2019 13:44:15
> -------------------------------------------

**Error Instance 1:** Only multiple of 8 resolutions are supported
Encoding
Error encoding at channel 1! Check error log file for more details ...
Encoder finished

**Comment by ultrawide** [comment]
I built #620 and ran the following:
./SvtAv1EncApp.exe -i test.yuv -b test.av1 -w 852 -h 480 -bit-depth 8 -fps 60 -intra-period 55 -n 20 -compressed-ten-bit-format 0 -q 27 -enc-mode 8 -rc 0

Issue is no longer found.

**Comment by kylophone** [comment]
Fixed by #620
