### ISSUE TITLE
Fix GCC 8 compile warning

### ISSUE THREAD

**Issue by EwoutH** [OpenVisualCloud/SVT-AV1#647]
I noticed a build warning when compiling with GCC 8. Here's a [Travis log](https://travis-ci.com/OpenVisualCloud/SVT-AV1/jobs/239323880#L680).
```
[  0%] Building C object Source/Lib/Common/Codec/CMakeFiles/COMMON_CODEC.dir/EbAdaptiveMotionVectorPrediction.c.o
/home/travis/build/OpenVisualCloud/SVT-AV1/Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.c: In function ‘setup_ref_mv_list’:
/home/travis/build/OpenVisualCloud/SVT-AV1/Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.c:1120:59: error: array subscript 2 is above array bounds of ‘IntMv[2]’ {aka ‘union IntMv[2]’} [-Werror=array-bounds]
                     comp_list[comp_idx][idx] = ref_id[idx][list_idx];
                                                ~~~~~~~~~~~^~~~~~~~~~
cc1: all warnings being treated as errors
```
Blocks #646.

**Comment by DesWurstes** [comment]
One way to fix this is to change

```
                int32_t comp_idx = 0;
                for (int32_t list_idx = 0; list_idx < ref_id_count[idx]
                    && comp_idx < 3; ++list_idx, ++comp_idx)

                for (int32_t list_idx = 0; list_idx < ref_diff_count[idx]
                    && comp_idx < 3; ++list_idx, ++comp_idx)
                    comp_list[comp_idx][idx] = ref_diff[idx][list_idx];
```

to

```
                int32_t comp_idx = 0;
                for (int32_t list_idx = 0; list_idx < ref_id_count[idx]
                    && comp_idx < 2; ++list_idx, ++comp_idx)


                for (int32_t list_idx = 0; list_idx < ref_diff_count[idx]
                    && comp_idx < 3 && list_idx < 2; ++list_idx, ++comp_idx)
                    comp_list[comp_idx][idx] = ref_diff[idx][list_idx];
```

[here](https://github.com/OpenVisualCloud/SVT-AV1/blob/master/Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.c#L1118), but this could be a sign of a hiding bug.

**Comment by EwoutH** [comment]
@hassount Could you assign someone to review DesWurstes suggestion, and to asses if there might be an hiding bug?

**Comment by hassount** [comment]
@chkngit 
you have a comment on this section saying:
//CHKN I dont think we need the third

Does the above change fixing a warning look right to you ?

**Comment by chkngit** [comment]
checked aom code and they seemed to have changed this to:
      // Build up the compound mv predictor
      int_mv comp_list[MAX_MV_REF_CANDIDATES][2];

      for (int idx = 0; idx < 2; ++idx) {
        int comp_idx = 0;
        for (int list_idx = 0;
             list_idx < ref_id_count[idx] && comp_idx < MAX_MV_REF_CANDIDATES;
             ++list_idx, ++comp_idx)
          comp_list[comp_idx][idx] = ref_id[idx][list_idx];
        for (int list_idx = 0;
             list_idx < ref_diff_count[idx] && comp_idx < MAX_MV_REF_CANDIDATES;
             ++list_idx, ++comp_idx)
          comp_list[comp_idx][idx] = ref_diff[idx][list_idx];
        for (; comp_idx < MAX_MV_REF_CANDIDATES; ++comp_idx)
          comp_list[comp_idx][idx] = gm_mv_candidates[idx];
      }

**Comment by EwoutH** [comment]
@chkngit Can you open a pull request?

**Comment by chkngit** [comment]
@okhlif  can you please have this PRed?
