### ISSUE TITLE
Error writing trailer of pipe:: Broken pipe

### ISSUE THREAD

**Issue by kalgi13** [OpenVisualCloud/SVT-AV1#651]
Hi, 
I am having this error while processing video with ffmpeg 
![Screenshot from 2019-09-27 10-59-18](https://user-images.githubusercontent.com/51786470/65744405-e095fe80-e115-11e9-9632-a5585bb8c291.png)

**Comment by JackZhouVCD** [comment]
Thanks for the report! Can you provide us with more information on how you got this error?

**Comment by JackZhouVCD** [comment]
@kalgi13 HI, can you please provide more information about how you got this error?

**Comment by hassount** [comment]
Closing, please reopen if the issue exists in v0.8.1
