### ISSUE TITLE
nm, read the error closer and figured out height of the input video wasn't a multiple of 8

### ISSUE THREAD

**Issue by kalgi13** [OpenVisualCloud/SVT-AV1#652]
nm, read the error closer and figured out height of the input video wasn't a multiple of 8
It is still not working, Any other solution ? 

_Originally posted by @singhkays in https://github.com/OpenVisualCloud/SVT-AV1/issues/17#issuecomment-460462627_

**Comment by JackZhouVCD** [comment]
possible duplicate of #645

**Comment by kylophone** [comment]
fixed by #620
