### ISSUE TITLE
SVT-AV1 v.7 Error - ASM 0 not supported when trying to use the encoder with SVT-AV1 FFMPEG plugin

### ISSUE THREAD

**Issue by baxxtor** [OpenVisualCloud/SVT-AV1#658]
With SVT-AV1 v.7 I receive the following error whenever I try to use the encoder through FFMPEG with SVT-AV1 plugin.  Unfortunately, there is no way to set the ASM type through the ffmpeg plugin so the encoder is unusable.

Error Instance 1: Asm 0 is not supported in this build .
[libsvt_av1 @ 000001E3FE1A9900] Error setting encoder parameters

FFMPEG plugin worked with v.6 without issue.  SVT-AV1 v.7 works with with SVTGUI but receives the ASM 0 error with FFMPEG Plugin.

**Comment by JackZhouVCD** [comment]
Hi @baxxtor , I tried to replicate this issue on the latest master using the sample ffmpeg command from [here](https://github.com/OpenVisualCloud/SVT-AV1/blob/master/ffmpeg_plugin/README.md). I was not able to get this error, encoding on ffmpeg using libsvt_av1 went fine for me. Can you share with me how you got this error?

**Comment by JackZhouVCD** [comment]
I think that since `-asm` is overhauled in #785, this is no longer a problem at the side of our encoder. Regardless of how it's configured with ffmpeg. @baxxtor would you be able to try again with the most recent revision of SVT-AV1?

**Comment by baxxtor** [comment]
Yes, I will try this evening.  Thank you.

**Comment by hassount** [comment]
@baxxtor closing this, feel free to open another one if you still see the issue
