### ISSUE TITLE
FFmpeg output in mp4 has VFR, with WebM has frame shift making VMAF low

### ISSUE THREAD

**Issue by bitbytebit-cr** [OpenVisualCloud/SVT-AV1#675]
I am using the newest git master with the FFmpeg patch. I get VFR with varying 2-29.976+ FPS using MP4, with Webm it does an odd shift (think with both actually) seen below in the 3rd frame. Suddenly it isn't the same as the reference and VMAF and PSNR are lower after that (around half values). This seems to possibly todo with the muxing to the formats I suspect. When I remux webm output to mp4 or others it says monotonic timestamps.

n:1 phqm_avg:0.000 phqm_min:0.000 phqm_max:0.000 scd:0.00 mse_avg:0.52 mse_y:0.60 mse_u:0.34 mse_v:0.39 psnr_avg:50.93 psnr_y:50.32 psnr_u:52.85 psnr_v:52.19
n:2 phqm_avg:0.000 phqm_min:0.000 phqm_max:0.000 scd:0.07 mse_avg:1.01 mse_y:1.24 mse_u:0.55 mse_v:0.59 psnr_avg:48.07 psnr_y:47.21 psnr_u:50.77 psnr_v:50.44
n:1 phqm_avg:0.000 phqm_min:0.000 phqm_max:0.000 scd:0.00 mse_avg:0.52 mse_y:0.60 mse_u:0.34 mse_v:0.39 psnr_avg:50.93 psnr_y:50.32 psnr_u:52.85 psnr_v:52.19
n:2 phqm_avg:0.000 phqm_min:0.000 phqm_max:0.000 scd:0.07 mse_avg:1.01 mse_y:1.24 mse_u:0.55 mse_v:0.59 psnr_avg:48.07 psnr_y:47.21 psnr_u:50.77 psnr_v:50.44
n:3 phqm_avg:17.000 phqm_min:0.000 phqm_max:17.000 scd:0.00 mse_avg:351.31 mse_y:524.54 mse_u:6.26 mse_v:3.47 psnr_avg:22.67 psnr_y:20.93 psnr_u:40.17 psnr_v:42.73
n:4 phqm_avg:1.000 phqm_min:0.000 phqm_max:17.000 scd:0.18 mse_avg:187.13 mse_y:279.40 mse_u:3.50 mse_v:1.68 psnr_avg:25.41 psnr_y:23.67 psnr_u:42.70 psnr_v:45.89
n:5 phqm_avg:12.000 phqm_min:0.000 phqm_max:17.000 scd:0.00 mse_avg:1758.37 mse_y:2631.33 mse_u:14.06 mse_v:10.84 psnr_avg:15.68 psnr_y:13.93 psnr_u:36.65 psnr_v:37.78
n:6 phqm_avg:0.000 phqm_min:0.000 phqm_max:17.000 scd:0.53 mse_avg:2.68 mse_y:3.41 mse_u:1.35 mse_v:1.07 psnr_avg:43.86 psnr_y:42.81 psnr_u:46.82 psnr_v:47.86
n:7 phqm_avg:9.000 phqm_min:0.000 phqm_max:17.000 scd:0.00 mse_avg:390.45 mse_y:582.79 mse_u:6.87 mse_v:4.65 psnr_avg:22.22 psnr_y:20.48 psnr_u:39.76 psnr_v:41.46
n:8 phqm_avg:1.000 phqm_min:0.000 phqm_max:17.000 scd:0.10 mse_avg:2.60 mse_y:3.28 mse_u:1.36 mse_v:1.13 psnr_avg:43.98 psnr_y:42.98 psnr_u:46.80 psnr_v:47.61
n:9 phqm_avg:9.000 phqm_min:0.000 phqm_max:17.000 scd:0.00 mse_avg:262.97 mse_y:392.08 mse_u:5.45 mse_v:4.06 psnr_avg:23.93 psnr_y:22.20 psnr_u:40.76 psnr_v:42.04
n:10 phqm_avg:0.000 phqm_min:0.000 phqm_max:17.000 scd:0.07 mse_avg:2.29 mse_y:2.86 mse_u:1.27 mse_v:1.06 psnr_avg:44.53 psnr_y:43.57 psnr_u:47.08 psnr_v:47.89
n:11 phqm_avg:9.000 phqm_min:0.000 phqm_max:17.000 scd:0.00 mse_avg:226.91 mse_y:339.00 mse_u:3.07 mse_v:2.38 psnr_avg:24.57 psnr_y:22.83 psnr_u:43.27 psnr_v:44.36
n:12 phqm_avg:0.000 phqm_min:0.000 phqm_max:17.000 scd:0.06 mse_avg:2.32 mse_y:2.90 mse_u:1.29 mse_v:1.04 psnr_avg:44.48 psnr_y:43.51 psnr_u:47.02 psnr_v:47.96
n:13 phqm_avg:7.000 phqm_min:0.000 phqm_max:17.000 scd:0.00 mse_avg:113.28 mse_y:169.06 mse_u:2.06 mse_v:1.39 psnr_avg:27.59 psnr_y:25.85 psnr_u:44.99 psnr_v:46.70

Thanks!
Christopher Kennedy

**Comment by hassount** [comment]
@bitbytebit-cr thnx for the report, could you add a command line and the encoder output log so that we could repro ?

**Comment by bitbytebit-cr** [comment]
Here is a full ffmpeg -report output of it having the issue. It seems to not be for all content, yet happens with ProRes for certain. I suspect it has todo with the timestamps from the original or something, in the code I see the pts/dts stuff and it feels like something is off but haven't found it in my fiddling around with setting it up.

Thank You!
Christopher Kennedy
[ffmpeg_output.txt](https://github.com/OpenVisualCloud/SVT-AV1/files/3702540/ffmpeg_output.txt)
[ffmpeg-20191008-061310.log](https://github.com/OpenVisualCloud/SVT-AV1/files/3702541/ffmpeg-20191008-061310.log)

**Comment by xuguangxin** [comment]
@bitbytebit-cr , please try https://github.com/OpenVisualCloud/SVT-AV1/pull/1053.
thanks

**Comment by xuguangxin** [comment]
@bitbytebit-cr , the #1053  has merged. could you try master, and se we can reproduce the issue or not?
thanks

**Comment by xuguangxin** [comment]
Hi @bitbytebit-cr 
Got time to check this?
thanks

**Comment by hassount** [comment]
please re-open if this persists
