### ISSUE TITLE
Encoding using pipe input stops in the middle

### ISSUE THREAD

**Issue by f11894** [OpenVisualCloud/SVT-AV1#676]
Windows10

command line
```
ffmpeg.exe -y -i Netflix_SquareAndTimelapse_1920x1080_60fps_8bit_420_60f.y4m -an -nostdin -f rawvideo - | SvtAv1EncApp.exe -i stdin -enc-mode 8 -intra-period 63 -q 50 -n 60 -w 1920 -h 1080 -fps-num 60 -fps-denom 1 -b Netflix_SquareAndTimelapse_1920x1080_60fps_8bit_420_60f_q50.ivf
```

Success. f1be002
Failed. 63771e5 or later

**Comment by 1480c1** [comment]
Mingw build or msvc?

**Comment by f11894** [comment]
> Mingw build or msvc?
Both

**Comment by j-mas** [comment]
The same problem here!!! Please solve it! Thank you!!!

**Comment by kylophone** [comment]
@f11894, How many frames went in and how many frames came out?

**Comment by kylophone** [comment]
@moisespr123, have you had issues with this too?

**Comment by f11894** [comment]
> @ f11894、いくつのフレームが入り、いくつのフレームが出ましたか？

After pipe all 60 frames of the source video, SVT-AV1 encodes only 1 frame.
https://i.imgur.com/3SMfWhL.gif

**Comment by ttrigui** [comment]
@f11894 Can you check if 7981c7d fixes the issue?

**Comment by moisespr123** [comment]
@kylophone sorry, haven't tested SVt-AV1 lately.

**Comment by f11894** [comment]
@ttrigui Thank you so much.
Verified that the issue has been resolved.
