### ISSUE TITLE
Participate in MSU Annual Video Codecs Comparison 2019

### ISSUE THREAD

**Issue by EwoutH** [OpenVisualCloud/SVT-AV1#68]
Moscow State University is soon (deadline March 1) starting with it's yearly codec review, it would be great to have SVT-AV1 (and SVT-VP9 and SVT-HEVC) included in it.
- [MSU Annual Video Codecs Comparison 2019: Call for codecs](http://www.compression.ru/video/codec_comparison/call_for_codecs_19.html)

There are different categories for different applications and performance levels, SVT-AV1 could probably participate in most categories. 

But maybe there's a change for more collaboration. Right now they state a Intel Core i7-8700K (6c/12t, AVX2) cpu will be used. This puts the SVT encoders at a disadvantage, since A) they highly profit from a large number of cores and B) they largely profit from AVX-512 instructions.

This could be resolved by sending them a more powerful Skylake-X processor with AVX-512 support, like the Core i9-9980XE or Xeon W-2195, which gives MSU the ability to test more thorough and gives the SVT encoders harware closer to what they're made for.

The MSU Annual Video Codecs Comparison is the gold standard for codec comparisons and it would be a great way to put SVT-AV1 on the map. So contact them:
- Mail: videocodec-testing@graphics.cs.msu.ru
- Doom9 forum: https://forum.doom9.org/showthread.php?p=1866157

**Comment by mafonsoN** [comment]
I think we can definitely discuss this for next years' comparison! Closing this issue now.
