### ISSUE TITLE
Encoder/decoder harmonization

### ISSUE THREAD

**Issue by joelsole** [OpenVisualCloud/SVT-AV1#683]
There is some misalignment and code duplication between encoder and decoder. Functions, structures, and macros need harmonization. 

A non-comprehensive list of duplications:

- find_warp_samples, has_overlappable_cand, is_motion_mode_allowed, is_comp_ref_allowed, av1_is_interp_needed, filter_intra_allowed_bsize, is_directional_mode, use_angle_delta, get_lower_levels_ctx_eob, ...
- AV1_DEBLOCKING_PARAMETERS, EDGE_DIR, ...
- Pad_pic
- allow_intrabc
- Dec_clamp_mv, derive_blk_pointers, could be part of common

**Comment by hassount** [comment]
@joelsole is this still accurate ?
