### ISSUE TITLE
Experiment using Fast inverse chip z-transform

### ISSUE THREAD

**Issue by LifeIsStrange** [OpenVisualCloud/SVT-AV1#692]
I'm not an expert, but this seems like a major discovery in signal processing!

From the comments I read:
*Sounds like a pretty awesome milestone to me. So, perhaps in the near future, new compression schemes might allow for reduced mp3 and mp4 file sizes, which means that for the same bandwidth we could see increased resolution/ higher frame rates*

And

*It should be a O(n log n) rather than O(n^2), so the speed increase for large n, which can be common n signal processing, is real.*

Comments:
https://news.ycombinator.com/item?id=21230757
Source:
https://m.techxplore.com/news/2019-10-year-old-puzzle.html

**Comment by hassount** [comment]
@LifeIsStrange 
thank you for bringing this up. as this is an implementation for an existing standard, it's a little late in the process to make this kind of change. This would potentially be applicable for future codec standardization efforts and suggested to the standard body.

**Comment by LifeIsStrange** [comment]
@hassount yes I suggested it to opus and they think it is an interesting proposal for an eventual Opus v2.0. But nobody's working on Opus 2.0 ^^
I might suggest it to the MPEG consortium though
