### ISSUE TITLE
Improving the state of the art of lossless and lossy image compression

### ISSUE THREAD

**Issue by LifeIsStrange** [OpenVisualCloud/SVT-AV1#693]
I thought this would be a topic that might interest Intel and Netflix, for economic, altruistic and ecological reasons.

Sorry this issue is not related to SVT-AV1, and if accepted, would lead to the creation of a new SVT decoder.

The codec world is stagnating for many reasons, 
Let's imagine an inventor named Bob which after years of hard work, has found and benchmarked his new codec (image, audio, video, doesn't matter)
Let's say the benchmarks show that wow, this is the new state of the art, the new best in class codec. 
It would allow to massively reduce datacenter costs, to reduce energy consumption (ecological) and for end users to access high quality content even if they have low bandwidth. 
This is more and more needed as resolutions increase (you can already buy a 8K HDR screen!).

Despite all this usefulness, the most used codecs for images are still those antic technologies: PNG and Jpeg. 

So what could stop the adoption of the amazing codec of Bob? 

Firstly, a codec is almost useless if it is not adopted by browsers.
Browsers are not actively researching new codecs it seems, they want Bob to do all the hard work, and once it is done, they would eventually accept the pull request from Bob (like chromium did with apng), then the world could benefit from his codec. 

So the first blocker is:
Bob has not necessarily the time and expertise to do the integration. 
The second blocker is that browsers no longer seems to accept patented codecs, which is debatable, but thankfully Bob codec is patent free. 
The third blocker is that browsers might have double standards. 
For famous codecs that have traction like vp9 or av1, they accept the codec and do the optimizing work for the decoder.
This one is a big blocker, as Bob has not the time (and maybe not the expertise: SSE, AVX, NEON, OpenMP, OpenACC, openCL/SYCL) to optimize the decoder of his codec. 

It happens that Bob exists.
It happens that his codec is the best in class image codec for both lossless and lossy image compression! 
It's named FLIF.

It is the best at lossless and supports many interesting performance features.
Source: https://flif.info

It is also the best at lossy:
Source: https://flif.info/lossy.html
And has this amazing property:
*One of the advantages of using a lossless format in a lossy way (as opposed to using a lossy format), is that generation loss is not an issue. Of course the information that is lost, stays lost, but no matter how many times you save a FLIF file, it will not get any additional loss from a decode-encode cycle. This is not the case for e.g. JPEG, where each decode-encode cycle always introduces additional loss.*

And is the best at animated images:
Source: https://flif.info/animation.html

Intel has a key role to play here:
It is to enable flif and all it's benefits to go mainstream. 
It is to enable browser support. 
Intel has the expertise for optimizing and I believe, has the capability to make the FLIF decoder competitive with e.g PNG decoding speed.
Once this would be done, chromium would happily accept it to the benefit of all end users and even of global warming.

Secondly, if Intel accept to make the world a better place by making this decoder (or optimizing the existing one), it would be pragmatic to develop it with chromium integration in mind, from the start. 
Which means: communicating with chromium engineers and integrating with skia (I believe Intel already has many engineers experimented with skia, e.g fastuidraw). 

https://github.com/FLIF-hub/FLIF
https://bugs.chromium.org/p/chromium/issues/detail?id=793683

**Comment by LifeIsStrange** [comment]
Well after some researchs, I come a little late to the party, and I have very good news!

The flif developper has made a successor of flif named FUIF:
https://github.com/cloudinary/fuif
At the same time, Google has been working on a successor to webp:
https://github.com/google/pik

It happen that since 2016, the JPEG foundation has made a call for making a new standard, the successor of JPEG. 
Both FUIF and PIK developers are working together to create the new standard named: JPEG XL:
https://jpeg.org/jpegxl/index.html

I believe we will soon here about it and that it will be the one image codec to tule them all!
Still, I believe Intel has some of the best engineers on earth and that you could help optimizing the JPEG XL en/decoder.

**Comment by hassount** [comment]
@LifeIsStrange thank you for sharing.

**Comment by LifeIsStrange** [comment]
@hassount so I guess the upper management have much more intelligent spending of money to do like buying [ Nervada ]( https://en.m.wikipedia.org/wiki/Nervana_Systems ) at an estimated $408 million only for deprecating their framework... https://github.com/NervanaSystems/neon

With great powers come great responsibilities and the upper management at Intel is committing crime by mediocrity.

@hassount of course my critic does not apply to you as you're not an executive.

Here's the repo for posterity. 
https://gitlab.com/wg1/jpeg-xl

Indeed Intel is a big player in the open source world, as I claim Intel could have order of magnitude more impact if it spent its money more efficiently but I still thanks Intel for existing and being for example the number one Linux kernel contributor.
