### ISSUE TITLE
newest vesion  debug error

### ISSUE THREAD

**Issue by laxusvip** [OpenVisualCloud/SVT-AV1#695]
run SvtAV1EncApp

in EcTempoalFiltering.c  L2198
assert(height_y * picture_control_set_ptr_central->enhanced_picture_ptr->stride_y == picture_control_set_ptr_central->enhanced_picture_ptr->luma_size);

**Comment by JackZhouVCD** [comment]
Thanks for report this error! Can you share with us:

- the command you used 
- your system environment
- (if possible) the clip that was used

so we can look into this issue?

**Comment by laxusvip** [comment]
-i *.yuv -w 1920 -h 1080-lp 2 -n 1 -b *.ivf -stat-report 1 -enc-mode 0
window10 X64
