### ISSUE TITLE
Add FFmpeg patch to enable all SVT encoders

### ISSUE THREAD

**Issue by EwoutH** [OpenVisualCloud/SVT-AV1#724]
There now are [FFmpeg plugins](https://github.com/OpenVisualCloud/SVT-AV1/tree/master/ffmpeg_plugin) to add SVT-AV1 to FFmpeg and to add both SVT-AV1 and SVT-HEVC to FFmpeg. It would be nice if there was one singluar plugin that enables all SVT encoders (AV1, HEVC and VP9) and potentially in the future, SVT-AVS3, for FFmpeg.

Maybe a separate repository for plugins (FFmpeg, Gstreamer and potentially more) wouldn't be a bad thing.

**Comment by grill05** [comment]
has the problem of conflicting symbols with libaom (which causes segfault when svt tries to encode the first frame  via ffmpeg) been solved ? It would be nice to have --enable-libaom and --enable-libsvt(av1) simultaneously.

**Comment by grill05** [comment]
does the plugin still work with ffmpeg master?
I was getting a segfault a few days ago when svt tried to encode the first frame(through ffmpeg). There may be conflicting symbols with libaom. I was compiling  ffmpeg with --enable-libaom --enable-libdav1d --enable-libsvtav1

**Comment by dsummer** [comment]
These are patches, not plugins, and it's logical to have one patch per encoder. Otherwise the number of combined patches to maintain would be multiplied, because some might like to use 2 of the 3 SVT encoders. Goal should be (and probably is) to get the SVT encoders to the point that their hooks be provided by the mainline FFMPEG.

**Comment by 1480c1** [comment]
afaik, there hasn't been any new messages on the most recent attempt at mainlining SVT-HEVC (https://patchwork.ffmpeg.org/patch/15757/)

**Comment by hassount** [comment]
this should be tracked on the rest of the SVT projects as this one is already merged to ffmpeg
