### ISSUE TITLE
-nostdin  /  stdin

### ISSUE THREAD

**Issue by j-mas** [OpenVisualCloud/SVT-AV1#727]
Until the AppVeyor build 1.0.2930, the following command line works fine: 

ffmpeg.exe -loglevel fatal -hide_banner -i C: \ Movie \ 1.mkv -nostdin -f rawvideo -pix_fmt yuv420p - | SVT-AV1 \ SvtAv1EncApp.exe -i stdin -w 1920 -h 1080 -n 800 -rc 2 -tbr 2000000 -enc-mode 6 -b C: \ Movie \ test_out.mkv
From the AppVeyor build 1.0.2931 it does not work anymore! Why? 

Please check and restore this feature !!

**Comment by 1480c1** [comment]
Could you at least describe what is outputted to console/why it doesn't work? Not all of the developers use/test windows plus not everyone has time to check each feature. If you can provide some information, it would make it easier to figure out what's wrong.

Also, when typing in code or commands, you can mark them off with `` ` `` (backticks, next to 1) so that they do not get formatted ( `ffmpeg.exe -loglevel fatal -hide_banner -i C:\Movie\1.mkv -nostdin -f rawvideo -pix_fmt yuv420p - | SVT-AV1\SvtAv1EncApp.exe -i stdin -w 1920 -h 1080 -n 800 -rc 2 -tbr 2000000 -enc-mode 6 -b C:\Movie\test_out.mkv`). This helps with readability and making sure that commands can be copied if necessary. [For code blocks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks)

**Comment by hassount** [comment]
@j-mas 2931 seems quite old, can you try the latest ?

**Comment by j-mas** [comment]
@hassount @1480c1 
AppVeyor Build 1.0.2930 is about 11 days old. I tried the newest one Build 1.0.3247 but the result is the same. Build 1.0.2930 is the last one which works correctly with the mentioned command.

The encoding works but since Build 1.0.2931 the resulting video is completely color-shifted and doubled and has an additional big margin on the right side. Unfortunately, I can not describe it better.

**Comment by j-mas** [comment]
@hassount @1480c1 
![2019-10-22](https://user-images.githubusercontent.com/43079436/67250419-9c272580-f46b-11e9-853d-359ddf851427.png)

**Comment by f11894** [comment]
Probably also related to #676

@j-mas Isn't the issue occurring from 1.0.2888?
https://ci.appveyor.com/project/OpenVisualCloud/svt-av1/builds/27829803

**Comment by j-mas** [comment]
@f11894 
You are right. But I tested all AppVeyor Builds and the last one who works with this command line is the Build 1.0.2930. 

It is interesting that this applies only to the release SVT-AV1 v.0.7.0. The last AppVeyor build 1.0.3261 of the release SVT-AV1 v.0.5.0 works.

**Comment by ttrigui** [comment]
@j-mas Can you check if [https://github.com/OpenVisualCloud/SVT-AV1/tree/Bug_Fix_Reading_Unnamed_Pipe](url) fixes the issue?

**Comment by j-mas** [comment]
@ttrigui 
AppVeyor Build 1.0.3284 fixed the issue and works!!!!!
but in AppVeyor Build 1.0.3285 it doesn work again!

**Comment by ttrigui** [comment]
> @ttrigui
> AppVeyor Build 1.0.3284 fixed the issue and works!!!!!
> but in AppVeyor Build 1.0.3285 it doesn work again!

Can you please point me to your exes? You can probably share links.
I'm trying to find the builds but I do not seem to find the AppVeyor build versions you are using.

**Comment by j-mas** [comment]
@ttrigui 
I use the builds from the following page:

https://ci.appveyor.com/project/OpenVisualCloud/svt-av1/history

Build 1.03284 works 
Build 1.03285 has the same problems as before. I think that 7981c7d fixes the issue!

**Comment by j-mas** [comment]
@ttrigui 

https://ci.appveyor.com/project/OpenVisualCloud/svt-av1/builds/28304322/artifacts
works
https://ci.appveyor.com/project/OpenVisualCloud/svt-av1/builds/28304516/artifacts
do not

**Comment by ttrigui** [comment]
> @ttrigui
> 
> https://ci.appveyor.com/project/OpenVisualCloud/svt-av1/builds/28304322/artifacts
> works
> https://ci.appveyor.com/project/OpenVisualCloud/svt-av1/builds/28304516/artifacts
> do not

Ok thank you. Yes it makes sense that 1.03284 works and 1.03285 does not.
1.03285 does not have the fix. I only committed the fix to Bug_Fix_Reading_Unnamed_Pipe which correspond to AppVeyor build  1.0.3284

**Comment by j-mas** [comment]
OK. 
Thank you very much for the fix. 
It would be very nice if you could merge him to master for future builds!

**Comment by j-mas** [comment]
@ttrigui 
May I ask why you do not merge the fix to master?

**Comment by ttrigui** [comment]
> @ttrigui
> May I ask why you do not merge the fix to master?

The code needs to be reviewed. a PR will be created and will be merged as soon as approved. In the meantime you can copy the fix in your copy.

**Comment by j-mas** [comment]
@ttrigui 
Thank you for the response. Since I do not know how to copy the fix into my copy I will wait.

**Comment by j-mas** [comment]
Thank you for merging it to the master! It works very good!

**Comment by 1480c1** [comment]
@ttrigui make sure to add `Fixes #727` to your [PR](https://github.com/OpenVisualCloud/SVT-AV1/pull/752) next time, that way the PR can be linked to this issue and it will be easy to know what changes that were merged that fixed the issue in case we need to make similar changes or others, else we just have the issue closed without any mention of how/what fixed it.
