### ISSUE TITLE
Backward timestamp values

### ISSUE THREAD

**Issue by ksuhiyp** [OpenVisualCloud/SVT-AV1#738]
FFmpeg version **master**
SVTAV1 version **master**

Using FFmpeg plugin with the following args:

`ffmpeg -y -i raw.mp4 -c:v libsvt_av1 -c:a libopus -g 50 -f webm raw.webm`

I am getting 

`Non-monotonous DTS in output stream 0:0; previous: 1720, current: 1440; changing to 1720. This may result in incorrect timestamps in the output file.`[log.txt](https://github.com/OpenVisualCloud/SVT-AV1/files/3767649/log.txt)

source sample ffprobe:
```

ffprobe version N-95488-g09581f7923 Copyright (c) 2007-2019 the FFmpeg developers
  built with gcc 9.2.0 (GCC)
  configuration: --prefix=/home/suhayb/ffmpeg_build --pkg-config-flags=--static --extra-cflags='-I /home/suhayb/ffmpeg_build/include' --extra-ldflags='-L /usr/local/lib' --extra-libs='-lpthread -lm' --bindir=/home/suhayb/bin --enable-gpl --enable-libsvtav1 --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
  libavutil      56. 35.101 / 56. 35.101
  libavcodec     58. 59.102 / 58. 59.102
  libavformat    58. 33.100 / 58. 33.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 63.100 /  7. 63.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'raw.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2017-09-05T19:17:04.000000Z
  Duration: 00:00:14.44, start: 0.000000, bitrate: 36869 kb/s
    Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080, 36650 kb/s, 25 fps, 25 tbr, 25k tbn, 50 tbc (default)
    Metadata:
      creation_time   : 2017-09-05T19:17:04.000000Z
      handler_name    : ?Mainconcept Video Media Handler
      encoder         : AVC Coding
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)
    Metadata:
      creation_time   : 2017-09-05T19:17:04.000000Z
      handler_name    : #Mainconcept MP4 Sound Media Handler
```

**Comment by luigi311** [comment]
Try doing the same conversion but with another video codec and see if it is actually being caused by this specific video codec or if its an issue with libopus.

**Comment by ksuhiyp** [comment]
it turned out the the group of picture option was causing that error. i've removed it  but my actual issue is with my malformed produced content, all produced samples shows a negative start value   

`Duration: 00:00:15.02, start: -0.007000, bitrate: 323 kb/s`

**Comment by ksuhiyp** [comment]
Interestingly changing the audio codec to aac shows a good start values,

`  Duration: 00:00:15.04, start: 0.000000, bitrate: 1603 kb/s`

**Comment by luigi311** [comment]
@ksuhiyp 
Is the negative start for the audio only? Apperently opus has delay issues so ffmpeg is cutting that out by pushing the start further back.

**Comment by ksuhiyp** [comment]
Yes that is correct, the issue is caused by libopus, as I've posted this somewhere else shifting start time in negative is fine and should not be considered as a malform, to be specific shaka packager is throwing an error complaining about the media content I input to it as malformed according to shaka collaborators 

error is    
[1026/002802:ERROR:webm_cluster_parser.cc(329)] Got a block with a timecode before the previous block.
shaka collaborator yelled that the content generated by the libsvt_av1 is bad   on [issue 668](https://github.com/google/shaka-packager/issues/668#issuecomment-546515051)

**Comment by ksuhiyp** [comment]
here are the timestamps for the generated sample with libopus and SVT
[timestamp.log](https://github.com/OpenVisualCloud/SVT-AV1/files/3774771/timestamp.log)

**Comment by ksuhiyp** [comment]
and here timestamps also with libvpx and libopus which shows correct
[timestamp.log](https://github.com/OpenVisualCloud/SVT-AV1/files/3775309/timestamp.log)
 values

**Comment by hassount** [comment]
@ksuhiyp can you check that #972  addressed this issue?
