### ISSUE TITLE
Add option to build only the encoder in CMake

### ISSUE THREAD

**Issue by grill05** [OpenVisualCloud/SVT-AV1#749]
Currently the build script (build.sh on linux) makes building tests optional. This is sensible since tests wont be useful for ordinary users. Similarly, the decoder(SvtAv1DecApp/libSvtAv1Dec.so) is not very useful, since dav1d already fulfils that requirement pretty well. 

If there was an option to only enable the encoder (and not the decoder), then that would make the build faster. This is useful for people who want to build and test the git master on a regular basis.

If I understand correctly the lines 166-170 in CMakeLists.txt which are right now 

```
add_subdirectory(Source/Lib/Encoder)
add_subdirectory(Source/Lib/Decoder)
if(BUILD_APPS)
    add_subdirectory(Source/App/EncApp)
    add_subdirectory(Source/App/DecApp)
endif()
```

would have to change to something like
```
if(BUILD_ENCODER)
    add_subdirectory(Source/Lib/Encoder)
    add_subdirectory(Source/App/EncApp)
endif()
if(BUILD_DECODER)
    add_subdirectory(Source/Lib/Decoder)
    add_subdirectory(Source/App/DecApp)
endif()
```

and an additional line to be added after line 62 which is currently
```
option(BUILD_APPS "Build Enc and Dec Apps" ON)
```
should change to 
```
option(BUILD_ENCODER "Build Enc App" ON)
option(BUILD_DECODER "Build Dec App" OFF)
```

**Comment by 1480c1** [comment]
Yes, something like that
