### ISSUE TITLE
is_skip_mode_flag not used

### ISSUE THREAD

**Issue by joelsole** [OpenVisualCloud/SVT-AV1#75]
is_skip_mode_flag in PU and ModeDecisionCandidate doesn't seem to be used:

./Codec/EbModeDecision.c:645:        candidateArray[canTotalCnt].is_skip_mode_flag = 0;
./Codec/EbModeDecision.c:701:            candidateArray[canTotalCnt].is_skip_mode_flag = 0;
./Codec/EbModeDecision.c:783:            candidateArray[canTotalCnt].is_skip_mode_flag = 0;
./Codec/EbModeDecision.c:843:            candidateArray[canTotalCnt].is_skip_mode_flag = 0;
./Codec/EbModeDecision.c:971:    candidateArray[canIdx].is_skip_mode_flag = 0;
./Codec/EbModeDecision.c:1010:        candidateArray[canIdx].is_skip_mode_flag = 0;
./Codec/EbModeDecision.c:1039:        candidateArray[canIdx].is_skip_mode_flag = 0;
./Codec/EbModeDecision.c:1078:            candidateArray[canIdx].is_skip_mode_flag = 0;
./Codec/EbModeDecision.c:1103:        candidateArray[canIdx].is_skip_mode_flag = 0;
./Codec/EbModeDecision.c:1145:                candidateArray[canIdx].is_skip_mode_flag = 0;
./Codec/EbModeDecision.c:1296:        candidateArray[canTotalCnt].is_skip_mode_flag = 0;
./Codec/EbModeDecision.c:1349:            candidateArray[canTotalCnt].is_skip_mode_flag = 0;
./Codec/EbModeDecision.c:1400:                candidateArray[canTotalCnt].is_skip_mode_flag = 0;
./Codec/EbModeDecision.c:1464:            candidateArray[canTotalCnt].is_skip_mode_flag = 0;
./Codec/EbModeDecision.c:1521:        candidateArray[canTotalCnt].is_skip_mode_flag = 0;
./Codec/EbModeDecision.c:1557:        candidateArray[canTotalCnt].is_skip_mode_flag = 0;
./Codec/EbModeDecision.c:1602:        candidateArray[canTotalCnt].is_skip_mode_flag = 0;
./Codec/EbModeDecision.c:2194:        pu_ptr->is_skip_mode_flag = candidate_ptr->is_skip_mode_flag;
./Codec/EbPredictionUnit.h:43:        EbBool                       is_skip_mode_flag;
./Codec/EbModeDecision.h:181:        EbBool                                 is_skip_mode_flag;

**Comment by hassount** [comment]
@joelsole 
Thank you for pointing this out, this is on our cleanup list

**Comment by mafonsoN** [comment]
This is outdated now. closing
