### ISSUE TITLE
Segmentation fault in SvtAv1EncApp (on linux) when piping 10-bit output via ffmpeg

### ISSUE THREAD

**Issue by grill05** [OpenVisualCloud/SVT-AV1#760]
I'm not sure whether I'm using the wrong ffmpeg command-line or if this is a bug. But when I try to pipe 10-bit output via ffmpeg, I get a segmentation fault in SvtAv1EncApp (on linux). I get the same segfault if the input is from a 10-bit .yuv file (encoded via ffmpeg)

The command line I tried to use was:

```
ffmpeg  -i "t.mkv"  -s 424x240 -pix_fmt yuv420p10le -strict -1   -an  -f yuv4mpegpipe  - | SvtAv1EncApp -i stdin -w 424  -h 240 -bit-depth 10 -fps 24.0  -n 2877 -rc 2 -tbr 200000  -irefresh-type 2 -enc-mode 5 -b "out.webm"
```
Which gives the errors:
```
[yuv4mpegpipe @ 0x562a3e342680] Warning: generating non standard YUV stream. Mjpegtools will not work.
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe 
Conversion failed!
Segmentation fault (core dumped)
```

**Comment by grill05** [comment]
Could someone please add a sample command to for 10-bit encoding (via pipes) to svt-av1_encoder_user_guide.md ?

**Comment by xuguangxin** [comment]
This is a generic bug, none 16 aligned 10 bits input will have this problem.
@grill05 , you can set the width to 16 aligned or wait https://github.com/OpenVisualCloud/SVT-AV1/pull/853 merged.
