### ISSUE TITLE
Encoder gets stuck when VBR

### ISSUE THREAD

**Issue by mtangtencent** [OpenVisualCloud/SVT-AV1#767]
I was running the encoder (master branch d3880e0c2af53) with the following command line
./SvtAv1EncApp.exe -i BasketballDrill_832x480_50.yuv -w 832 -h 480 -b test.ivf -enc-mode 8 -n 300 -rc 2 -tbr 1000000 -intra-period -1
The encoder got stuck with the log ending at
`Encoding      ` 
There is no number printed after "Encoding", which is the position where the number of frames that have been encoded is printed.

**Comment by grill05** [comment]
I have observed the same issue on a xeon testbed, for enc-modes 3 and below. When the encoder is stuck, the cpu-usage goes to 0%, but SvtAv1EncApp doesn't crash

**Comment by hassount** [comment]
-intra-period -1 would probably be the issue. can you set it to a value for now to make sure it works ?

**Comment by hassount** [comment]
this is related to #710

**Comment by JackZhouVCD** [comment]
closing this issue as it is resolved by #854
