### ISSUE TITLE
Add single command for two-pass mode

### ISSUE THREAD

**Issue by EwoutH** [OpenVisualCloud/SVT-AV1#775]
A simple `-two-pass` switch that runs SVT-AV1 in 2-pass mode with a single command would be a useful addition.

**Comment by ultrawide** [comment]
Hi @EwoutH, thanks for the suggestion. This is addressed in #746 and is being evaluated. The flag '-passes 2' will do the trick.

**Comment by hassount** [comment]
done #1365
