### ISSUE TITLE
SVT-AV1 gets stuck when using pipe on Windows

### ISSUE THREAD

**Issue by moisespr123** [OpenVisualCloud/SVT-AV1#787]
Encoding is working fine if I feed a raw y4m file. However, when using pipe, it will encode the video but get stuck in the last frame.

I'm not sure if this is relevant, but I'm using a named pipe.

**Comment by hassount** [comment]
@moisespr123 Has this ever worked ? thought it was fine

**Comment by moisespr123** [comment]
@hassount it used to work, but now it gets stuck at the last frame. SVT-AV1 seems to use just one thread. Also, the video comes out glitchy. Not sure what changed here.

**Comment by hassount** [comment]
@moisespr123 
thnx, do you know when was it working ? was v0.7.0 working ?

**Comment by moisespr123** [comment]
v0.6.0 is the one I was using prior to the new releases, which are still getting stuck.

**Comment by moisespr123** [comment]
v0.7.0 doesn't work.

**Comment by xuguangxin** [comment]
@moisespr123  could you try https://github.com/OpenVisualCloud/SVT-AV1/pull/942?
if it's not fixed your issue, could you provide some command line here? 
so I can reproduce your issue.
thanks

**Comment by moisespr123** [comment]
It's fixed! Thanks!
