### ISSUE TITLE
Fail to  compile on old linux releases

### ISSUE THREAD

**Issue by mtangtencent** [OpenVisualCloud/SVT-AV1#791]
The latest version of SVT-AV1 can be compiled on my Ubuntu 18.04 server, but fails on old linux releases. I was using Centos 7.2 and gcc 4.8.5, which reports a few `unknown type name '__m256i'`

**Comment by hassount** [comment]
Min requirements as stated in the readme:
https://github.com/OpenVisualCloud/SVT-AV1#linux-operating-systems-64-bit

**Comment by grill05** [comment]
@mtangtencent @hassount I compile on debian jessie. It works fine. jessie is quite old

**Comment by kylophone** [comment]
Closing for now. Added a SIMD label if we need to refer to this later.
