### ISSUE TITLE
2-pass VBR

### ISSUE THREAD

**Issue by hassount** [OpenVisualCloud/SVT-AV1#798]
Also, this is completely unrelated , but as an ordinary user, its a little frustrating to see SVT-AV1 keep churning out speedups and BD-rate improvements while still being forced to use libaom for real-life encodes. Without at least a 2-pass VBR mode, its not really practical (in terms of quality/bit efficiency) to use SVT-AV1 in constant-q mode. However fast constant-quantizer mode may become , by its very nature, using a constant-q will waste bits. 

For example, I just encoded the new Mandalorian episode with libaom and svt-av1. I had to use 22% more bits to get the same visual quality (SSIM) in svt-avt with 2-pass constant-q mode, when compared with libaom in 2-pass crf mode. Though even SVT's higher bit-rate was  a little lower than 'vanilla' x265 (at roughly the same SSIM).

_Originally posted by @grill05 in https://github.com/OpenVisualCloud/SVT-AV1/pull/783#issuecomment-554195107_

**Comment by hassount** [comment]
@grill05 
Thank you for the feedback, as much as I agree with the needs that you have requested above, we are just finishing up the implementation of features, need to stabilize the encoder fixing bugs and optimize for better speed-quality trade-offs. A 2-pass VBR would not yield much value on top of a core that is not optimized nor stable. the 2-pass implementation that svt-av1 currently has does not include rate control information.
Comparing to more mature VBR algorithms that have been around for much longer than SVT-AV1 although tempting, does not make sense at this point. So it is a priority call here and everyone is requesting features for their own use case, but we can only do much in a certain amount of time with the team working on this.

**Comment by grill05** [comment]
>  we are just finishing up the implementation of features, need to stabilize the encoder fixing bugs

 
That seems sensible

> optimize for better speed-quality trade-offs.

Regarding speed alone, I think you guys have already done a pretty great job. 
Roughly speaking, on a a single-core Xeon testbed, I find that SVT's `-enc-mode 5` was about 3 times faster than the fastest libaom speed setting (using libaom's `--good` deadline ofcourse). And `-enc-mode 5` was only about 20% slower than x265's 'slow' preset. 
Given that x265 is more than twice as slow as x264, and av1 is in some ways the next step-up from H.265, that already seems a pretty remarkable speed. And at the rate at which svt is improving, maybe it will eventually become faster than x265's 'medium' preset :)

> So it is a priority call here and everyone is requesting features for their own use case, but we can only do much in a certain amount of time with the team working on this.


Thats understandable. It cant be too much fun to have different people pushing in different directions to implement their own favourite features.

**Comment by FRNK-BK** [comment]
@hassount I totally understand, that you want to take one step after another. And that is why I don't understand, that the [EncoderUserGuide](https://github.com/OpenVisualCloud/SVT-AV1/blob/master/Docs/svt-av1_encoder_user_guide.md) here on github features a sample command line for: **2 pass VBR 5000 Kbps at slow speed from 24fps yuv 1920x1080 input**
You should at least at **there**, that the functionality is not (fully) implemented (yet).

**Comment by hassount** [comment]
@FRNK-BK 
Agreed, we'll make the change to state so.

**Comment by hassount** [comment]
@FRNK-BK 
The command line example for this was removed in this commit: 1e94523

**Comment by grill05** [comment]
@hassount @NaderMahdi @anaghdin  Hi, is there any update on how work on this is progressing. Thanks.

**Comment by hassount** [comment]
@grill05 
not yet there as we're still currently working on the core optimization.

**Comment by grill05** [comment]
@hassount I've been out of touch with SVT's progress for a while. Any movement on this lately ? thanks

**Comment by grill05** [comment]
@hassount @tianjunwork  I've been out of touch with SVT-AV1's development for a while. Any movement on this issue lately? Thanks

**Comment by hassount** [comment]
> @hassount @tianjunwork I've been out of touch with SVT-AV1's development for a while. Any movement on this issue lately? Thanks

@grill05 unfortunately not much yet, still focused on Quality / Speed optimizations for VOD applications, but we are putting this project in the pipeline so hopefully before the EOY.

**Comment by grill05** [comment]
@xuguangxin @hassount 
Does https://github.com/OpenVisualCloud/SVT-AV1/commit/298dd88ca07fbc1217fa7aa63d75697d14c1fad6 close this issue ?

**Comment by grill05** [comment]
@xuguangxin @hassount 
Does https://github.com/OpenVisualCloud/SVT-AV1/commit/298dd88ca07fbc1217fa7aa63d75697d14c1fad6 close this issue ?

**Comment by grill05** [comment]
@xuguangxin @hassount 
Does https://github.com/OpenVisualCloud/SVT-AV1/commit/298dd88ca07fbc1217fa7aa63d75697d14c1fad6 close this issue ?

**Comment by grill05** [comment]
@xuguangxin @hassount 
Does https://github.com/OpenVisualCloud/SVT-AV1/commit/298dd88ca07fbc1217fa7aa63d75697d14c1fad6 close this issue ?

**Comment by grill05** [comment]
@xuguangxin @hassount 
Does https://github.com/OpenVisualCloud/SVT-AV1/commit/298dd88ca07fbc1217fa7aa63d75697d14c1fad6 close this issue ?

**Comment by grill05** [comment]
@xuguangxin @hassount
Does https://github.com/OpenVisualCloud/SVT-AV1/commit/298dd88ca07fbc1217fa7aa63d75697d14c1fad6
 close this issue ?
It seems like a pretty major change. Is there a corresponding PR for this ?

**Comment by hassount** [comment]
@kelvinhu325 please link to this when ready

**Comment by hassount** [comment]
Closing this, please track future work and any further feedback in #1458
