### ISSUE TITLE
MacOS clang build is broken on Travis

### ISSUE THREAD

**Issue by kylophone** [OpenVisualCloud/SVT-AV1#812]
I suspect the environment Travis is running in has changed.

Example: https://travis-ci.com/OpenVisualCloud/SVT-AV1/jobs/258874055

```
The command "pip install --user cpp-coveralls" failed and exited with 127 during .
```

**Comment by kylophone** [comment]
@1480c1, perhaps you have some insight?

**Comment by 1480c1** [comment]
It seems like travis removed python2 from their macOS build sometime between the beginning of this week to now. I am currently working on an updated travis-ci config to use python3

**Comment by kylophone** [comment]
> It seems like travis removed python2 from their macOS build sometime between the beginning of this week to now. I am currently working on an updated travis-ci config to use python3

Thank you!

**Comment by 1480c1** [comment]
One thing I am interested in is why the valgrind builds have been failing (Exits here due to no output for 10 minutes [here](https://travis-ci.com/OpenVisualCloud/SVT-AV1/jobs/249660216) and after adding travis_wait, it exits with 137 [here](https://travis-ci.com/1480c1/SVT-AV1/jobs/259060187))

**Comment by 1480c1** [comment]
I am able to run valgrind locally so I wonder why it's not finishing

**Comment by 1480c1** [comment]
Seems like travis is sending a `kill -9` signal to it (https://github.com/travis-ci/travis-ci/issues/4192) so maybe I need to give it more time

**Comment by adaria** [comment]
I did see `SIGILL        4       Core    Illegal Instruction` on some of the failed macOS builds, e.g.

https://travis-ci.com/OpenVisualCloud/SVT-AV1/jobs/258841457

**Comment by grill05** [comment]
> It seems like travis removed python2 from their macOS 
IIRC python2 is reaching end-of-life (no further support/updates) at the end of the year. So this might have something to do with that
