### ISSUE TITLE
Bug when encoding non-multiple of 8 resolution video

### ISSUE THREAD

**Issue by JackZhouVCD** [OpenVisualCloud/SVT-AV1#831]
<i>
"So I ran a test on my video whose width was 1460 and SVT-AV1 accepted the input, but it output some crazy video which I will link below and then also link what it looked like before encoding it to AV1. Other things to note is that the output width was 1464 so SVT-AV1 accepted my input, but stretched the output.

Here it is bugged out. https://gfycat.com/unawarefemininebluewhale

Here is the unbugged video https://gfycat.com/unrulydisloyalflyingfish

I have no idea what could have happened, but figured it was worth mentioning."
</i>

from https://www.reddit.com/r/AV1/comments/e22924/bug_when_encoding_non_multiple_of_8_resolution/

**Comment by grill05** [comment]
I thought this was a design decision? This also happens when trying to encode in 850x480 for example

**Comment by cwfitzgerald** [comment]
It would be really nice to have some sort of check in the CLI if an invalid size is given. It's very non-obvious what's going on.

**Comment by hassount** [comment]
merged in #1191
