### ISSUE TITLE
Remove unused functions in EbCdef.c

### ISSUE THREAD

**Issue by ultrawide** [OpenVisualCloud/SVT-AV1#833]
There are functions in EbCdef.c which are not called within the solution, namely `void eb_av1_cdef_search()` and `void av1_cdef_search16bit()`. It would be good to reduce dead code which may cause potential misunderstanding and administrative overhead.

**Comment by hassount** [comment]
@ultrawide 
thank you for reporting this, please addsuch to #668  and close this issue to avoid duplicates
