### ISSUE TITLE
[ffmpeg_plugin][Release] Ffmpeg app gets stuck when encoding 10 bitdepth videos on Windows

### ISSUE THREAD

**Issue by EsmeraldaQuintero** [OpenVisualCloud/SVT-AV1#839]
### Context
I compile FFmpeg (latest) with svt-av1  (latest) and aom-av1 as shared libraries on windows and linux.
I need to generate some 10bit/8bit depth videos from images, videos and yuv files.

### Description
I'm using a yuv file with three 10bit frames as input.  When I encode a **8 bitdepth** video everything looks to be ok (using -pix_fmt yuv420p). But when I encode a **10 bitdepth** video the application gets stuck at the end (using -pix_fmt yuv420p10).

The ffmpeg doesn't work with:
```
ffmpeg.exe -f rawvideo -pix_fmt yuv420p10 -s:v 1920x1080 -r 25 -i 3frames_10bit.yuv -c:v libsvt_av1 -pix_fmt yuv420p10 out_yuv_ffmpeg.ivf
```
But the SvtAv1EncApp works with:
```
SvtAv1EncApp.exe -i 3frames_10bit.yuv -b out_yuv_app.ivf -w 1920 -h 1080 -n 3 -fps 24 -intra-period 23 -bit-depth 10 -compressed-ten-bit-format 0 -rc 0 -q 27 -enc-mode 8 
```
Using a lot of images also fails at the end,
```
ffmpeg.exe -f image2 -framerate 24 -i %06d.tiff -c:v libsvt_av1 -pix_fmt yuv420p10 out_tiff.ivf
```

When I tried the same on **Ubuntu 14.04 Virtual Machine** everything looks to be ok.

### Debug
The method `flush_encoders()`  has a cycle `for (;;)` and a nested cycle `while` which calls `avcodec_receive_packet()` and `avcodec_send_frame()`, during the first iteration everything is ok but in the second one the application gets stuck and close.

During the first iteration the `eb_get_full_object_non_blocking()` is used, during the second iteration the `eb_get_full_object()` is used.

```
flush_encoders()-> for (;;) -> while on ffmpeg.c
{
  avcodec_receive_packet() on encode.c
  {
    eb_receive_packet() on libsvt_av1.c
	{
	  eb_svt_get_packet() on EbEncHandle.c
	  {
	    DO THIS eb_get_full_object_non_blocking() on EbSystemResourceManager.c
            OR THIS eb_get_full_object() on EbSystemResourceManager.c <- DIES
	  }
	}
  }
  avcodec_send_frame() on encode.c
  {
    eb_send_frame() on libsvt_av1.c
  }
}
```

### Notes
I tried to debug what happens with `eb_get_full_object()` but it is called several times, so I'm not sure if that method is the problem or is something with the threads

### Edit notes

- During debugging the app dies on `eb_block_on_semaphore()`
- ~Rarely SvtAv1EncApp doesn't close at the end but generates the output~ (That was an issue with my code for debugging, the app looks to work ok)

**Comment by JackZhouVCD** [comment]
seems to be related to #510

**Comment by EsmeraldaQuintero** [comment]
> seems to be related to #510
Yes, it could be.

Reviewing the ffmpeg console output this configuration is used: 
```
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 8
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 10 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1920 / 1080
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 25 / 1 / 32 / 1
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 50 / 33 / 0
```

Imitating that configuration with `-enc-mode 0` in SvtAv1EncApp, the result is the same as the one I mentioned.
```
SvtAv1EncApp.exe -i short/3frames_10bit.yuv -b out_yuv_app.ivf -w 1920 -h 1080 -bit-depth 10 -compressed-ten-bit-format 0 -enc-mode 0 -fps-num 25 -fps-denom 1 -intra-period 31 -irefresh-type 1
```

**Comment by EsmeraldaQuintero** [comment]
In the 8bd pipeline this point is reached:
* `packetization_kernel()` -> `eb_post_full_object()` -> `EbMuxingQueueObjectPushBack()` -> `EbMuxingQueueAssignation()` -> `eb_post_semaphore()`
During the execution of:
* `eb_receive_packet()` -> `eb_svt_get_packet()` -> `eb_get_full_object()` -> `eb_block_on_semaphore()`
But in 10bd pipeline the aplication dies in some place (I think in `eb_block_on_semaphore()`).

@JackZhouVCD I'm debugging printing some text in the console, Is there a better way to debug?

**Comment by hassount** [comment]
Closing this as it should be fixed by now, please re-open if the issue persists.
