### ISSUE TITLE
[Task] add 10 bit encoding test to Travis

### ISSUE THREAD

**Issue by mafonsoN** [OpenVisualCloud/SVT-AV1#850]
A trial encoding of a sample 10-bit sequence needs to be added to the Travis CI for the Linux/Mac/Windows builds and for the binary identical test.

Related to #622.

**Comment by 1480c1** [comment]
Do you know of a freely available 10-bit file that is small enough to be able to be quickly downloaded? Or should we just get a few minutes worth of clips from [10-bit test videos](https://media.xiph.org/video/derf/) cut ourselves and uploaded to [SVT-AV1-Resources](https://github.com/OpenVisualCloud/SVT-AV1-Resources)?

**Comment by mafonsoN** [comment]
Don't know of any low resolution open content readily available. I think we should do what you suggested: pick any of the 10-bit content from [https://media.xiph.org/video/derf/](url), resize to 640x360 or 480x270. I can do this today and add it to video.tar.gz. Can you please then upload it to [http://randomderp.com/](url) ?

**Comment by 1480c1** [comment]
Sure, will you just update the current one on SVT-AV1-Resources?

**Comment by mafonsoN** [comment]
> Sure, will you just update video.tar.gz on SVT-AV1-Resources?

yes

**Comment by grill05** [comment]
@mafonsoN 

> Can you please then upload it to http://randomderp.com/ ?

Not to nitpick, but randomderp.com redirects to this
![randomderp](https://user-images.githubusercontent.com/56592753/70028443-12728800-15d3-11ea-9a45-69fe3ab5c358.jpg)

**Comment by 1480c1** [comment]
Yep

**Comment by 1480c1** [comment]
Feel free to suggest any modifications. That was made in a really old adobe dreamweaver and then modified to match html5

**Comment by 1480c1** [comment]
I've updated `video.tar.gz` at the mirror, @mafonsoN or @hassount, what enc-mode(s) do you think we should test in travis?

**Comment by hassount** [comment]
@1480c1
I suggest -enc-mode 0,4,8 if we have enough compute?

**Comment by mafonsoN** [comment]
Should we add enc-mode 4 as well for all tests? I've created this branch yesterday to add the 10-bit test to the travis build tests and to the binary identical: https://github.com/OpenVisualCloud/SVT-AV1/tree/travis-10bit-test

**Comment by hassount** [comment]
#831
