### ISSUE TITLE
Set enable_adaptive_quantization = 1 would cause assert failed in the encoder with debugging build

### ISSUE THREAD

**Issue by wallerjiaotencent** [OpenVisualCloud/SVT-AV1#852]
I tried to set enable_adaptive_quantization = 1; when debug build, the encoder throw out "debug assert failed" message; when release build, the encoder can run normally and output playable bitstream.
It looks like some variables have not been initialized. The debugging build is on windows platform.

**Comment by wallerjiaotencent** [comment]
The debugging build is on windows platform.

**Comment by JackZhouVCD** [comment]
Thanks for reporting this issue! Can you share with us the command and perhaps the patch (as plaintext) you used that generated the assertion fail?

**Comment by wallerjiaotencent** [comment]
The following command line triggers this issue:
SvtAv1EncApp.exe -i FourPeople_1280x720_60.yuv -w 1280 -h 720 -b D:\testSequences\test.ivf -enc-mode 8 -n 200 -rc 0 -q 40 -intra-period 31 -adaptive-quantization 1

**Comment by JackZhouVCD** [comment]
> The following command line triggers this issue(with commit [e54f59e](https://github.com/OpenVisualCloud/SVT-AV1/commit/e54f59eb9041c28dd97497d5d8fbe67f40c7606f)):
> SvtAv1EncApp.exe -i FourPeople_1280x720_60.yuv -w 1280 -h 720 -b test.ivf -enc-mode 8 -n 200 -rc 0 -q 40 -intra-period 31 -adaptive-quantization 1

I see, thanks!

I tried to run with this command as well, same issue happens with `dark720p` clip. I found the following failed assert:

```css
Assertion failed: x < max, Source\Lib\Common\Codec\EbEntropyCoding.c, line 5864
```

I did a bit to digging and found that `cu_ptr->segment_id` was uninitialized. Setting it to 0 resolved the issue but the resulting bitstream has VERY prominent blocking artifacts.

@anaghdin can you please look into this?

**Comment by anaghdin** [comment]
@JackZhouVCD Thanks for checking it. I recall it was working. Could you do a regression test to figure out which commit broke it?

**Comment by JackZhouVCD** [comment]
> . I recall it was working. Could you do a regression test to figure out which commit broke it?

For sure, actually this issue happens even in the initial commit 47e6f527

**Comment by anaghdin** [comment]
> > . I recall it was working. Could you do a regression test to figure out which commit broke it?
> 
> For sure, actually this issue happens even in the initial commit [47e6f52](https://github.com/OpenVisualCloud/SVT-AV1/commit/47e6f527c4f3bf82cfaccf688068f5dfa52dad6e)

Thanks for checking. The support for segment was added by:
https://github.com/OpenVisualCloud/SVT-AV1/pull/337
 
Could you please check the master after it got merged?

**Comment by JackZhouVCD** [comment]
> > > . I recall it was working. Could you do a regression test to figure out which commit broke it?
> > 
> > 
> > ~~For sure, actually this issue happens even in the initial commit 47e6f52~~
> 
> Thanks for checking. The support for segment was added by:
> #337
> 
> Could you please check the master after it got merged?

Yes, the assert fails when this feature was introduced at be0ba80b

**Comment by wallerjiaotencent** [comment]
fixed 
commit bd05c08ddf3cb2e28ca27f21caad2092b94f8960
