### ISSUE TITLE
[CLEANUP] Major code cleanup patches coming in during the holidays / first week of January

### ISSUE THREAD

**Issue by hassount** [OpenVisualCloud/SVT-AV1#856]
Suggest a code freeze on December 16th.
Items to be addressed:
- #668 
- clang format
- tabs / spaces
- snake_case
- dead code
- macro removal and cleanup
- squash commits to clean up commit history (for example #402 introduced 169 commits into master when it really should be 1, and often many PR's include commits for vanity checks and build issues)

**Comment by hassount** [comment]
Pre-requisites for a code freeze:

- [ ] #773 
- [ ] #780 
- [ ] #785 
- [ ] #793 
- [ ] #800 
- [ ] #801 
- [ ] #809
- [ ] #813 
- [ ] #814 
- [ ] #822 
- [ ] #823 
- [ ] #824 
- [ ] #825 
- [ ] #834 
- [ ] #840 
- [ ] #841 
- [ ] #842 
- [ ] #844 
- [ ] #847 
- [ ] #848 
- [ ] #849 
- [ ] #853 
- [ ] #854 
- [ ] #855 
- [ ] #858

**Comment by EwoutH** [comment]
Can we do a 0.8.1 release when the cleanup window ends?
