### ISSUE TITLE
Touching PCS data in Ressource Coordination after releasing results to PicAnalysis

### ISSUE THREAD

**Issue by chkngit** [OpenVisualCloud/SVT-AV1#857]
a code is exectuted in Ressource Coordination under 
  if(sequence_control_set_ptr->static_config.unrestricted_motion_vector == 0)
            
is done even though the picture has been released.

This will cause a race condition or field corruption in PCS structure

**Comment by kelvinhu325** [comment]
@chkngit do we have any tests to cover this issue? The "umv 0" processing is for current picture_control_set and it's after released prevPictureControlSetWrapperPtr, it looks ok, to be careful, do you mean moving "umv 0" processing before releasing prevPictureControlSetWrapperPtr?

**Comment by chkngit** [comment]
I did not see that this is causing an issue, but as a good practice, we would like to have no code after releasing the results to the next process

**Comment by kelvinhu325** [comment]
@chkngit  created a PR https://github.com/OpenVisualCloud/SVT-AV1/pull/865 for this issue, pls review it, thanks!
