### ISSUE TITLE
refactoring CopySequenceControlSet

### ISSUE THREAD

**Issue by JackZhouVCD** [OpenVisualCloud/SVT-AV1#860]
Currently the CopySequenceControlSet function is long and tedious to work with. We should look into refactoring the function, and perhaps in the likes of how it is done in [SVT-HEVC](https://github.com/OpenVisualCloud/SVT-HEVC/blob/251cb8b361b16d0880cc7119dc91eca5b3597294/Source/Lib/Codec/EbSequenceControlSet.c#L187)

From https://github.com/OpenVisualCloud/SVT-AV1/pull/780#discussion_r346023374

**Comment by hassount** [comment]
Merged at #1016

**Comment by jryzkns** [comment]
> Merged at #1016

This was reverted in aa07c48, should this issue be reopened?
