### ISSUE TITLE
Rate estimation update

### ISSUE THREAD

**Issue by anaghdin** [OpenVisualCloud/SVT-AV1#867]
Adding the rate estimation updates used in MD for missing syntax elements

Active branch:
https://github.com/OpenVisualCloud/SVT-AV1/compare/Rate_est_update

**Comment by grill05** [comment]
@anaghdin could you please elaborate a bit on whats happening in that branch ?

**Comment by anaghdin** [comment]
I am adding the modes and MVs CDF updates. The CDFs are used to generate the rate/cost tables, which are used in mode decision.
