### ISSUE TITLE
reduce eb_init_encoder time.

### ISSUE THREAD

**Issue by xuguangxin** [OpenVisualCloud/SVT-AV1#898]
According to https://github.com/OpenVisualCloud/SVT-AV1/pull/893#issue-352793715, eb_init_encoder need 5.6350s on a 112 logical core system for a 1080P. It's a big latency for a realtime board cast system.

Most time spent on object allocation and all objects allocated by https://github.com/OpenVisualCloud/SVT-AV1/blob/169c1a373f0114f3cd7123544170b995b202a310/Source/Lib/Common/Codec/EbSystemResourceManager.c#L502
Do you think it's ok to delay the allocation at the running time? 
The basic logical is: if we can't get an object from the empty queue, and the (allocated items < object_total_count), we will allocate and return a new one. else we will wait in the empty queue.

thanks

**Comment by hassount** [comment]
still an issue ?

**Comment by xuguangxin** [comment]
@hassount , we can close it. I will reopen it if it still an issue.
