### ISSUE TITLE
Add support for y4m input

### ISSUE THREAD

**Issue by negge** [OpenVisualCloud/SVT-AV1#9]
The only input supported is yuv.  From the README.md:
```
SvtAV1EncApp.exe -i [in.yuv] -w [width] -h [height] -b [out.ivf]
```
The width, height and chroma subsampling are included in the first line of the y4m file and nearly all test samples are provided in this format.

For converting from yuv to y4m please see the open source tool:

https://git.xiph.org/?p=daala.git;a=blob;f=tools/yuv2yuv4mpeg.c

**Comment by kylophone** [comment]
Implemented in https://github.com/OpenVisualCloud/SVT-AV1/pull/5, still needs a just a little bit of work.

**Comment by kylophone** [comment]
#5 is merged.
