### ISSUE TITLE
mem leak when -scm 1

### ISSUE THREAD

**Issue by mtangtencent** [OpenVisualCloud/SVT-AV1#927]
I was trying to use SVT-AV1 (v0.8.0) to encode some screen content with the following command line
`./SvtAv1EncApp -i <video.yuv> -w <w> -h <h> -b out.ivf -enc-mode 4 -n <n> -rc 0 -q 24 -scm 1`

An overwhelming mem leak was observed, and a memory overflow error was observed on my laptop (16GB RAM) after encoding fewer than 50 frames of 1080p content.

**Comment by JackZhouVCD** [comment]
thanks for reporting this issue! which video clip did you use?

**Comment by mtangtencent** [comment]
Hi Jack, when -scm 1 is used, the screen content coding tools are always enabled no matter whether the input video is screen content video or not. I tested the command line with non-SCC video BQTerrace, which also failed due to the mem leak.

**Comment by hassount** [comment]
@mtangtencent 
can you please test using -lp 1 and check if you still see the issue ?

**Comment by mtangtencent** [comment]
@hassount lp 1 also has this issue.
And I found using screen content video and `-intra-period 0` can make this issue even worse

**Comment by hassount** [comment]
@mtangtencent 
Thank you for the details. the issue on our side is that we're not able to reproduce the memory leak thus suspecting that not having enough memory would be triggering that. 

in this case, we will need more details on your system to try to build a similar environment. a log capture of the output would also help

**Comment by spawlows** [comment]
Hi,

I can not reproduce memory leak error with: 
"./SvtAv1EncApp -i BQTerrace_1920x1080_60.yuv -w 1920 -h 1080 -b out.ivf -enc-mode 4 -n 50 -rc 0 -q 24 -scm 1"

To reduce ram usage you can set "-lp x", or you can set "-intrabc-mode 0" for "-intra-period 0", but this will disable feature IBC (intra block copy). 

@mtangtencent Could you confirm?

**Comment by mtangtencent** [comment]
The mem leak issue is gone when testing with the latest master.
