### ISSUE TITLE
Create real-time communication platform (IRC, Slack, Discord, e.g.)

### ISSUE THREAD

**Issue by EwoutH** [OpenVisualCloud/SVT-AV1#93]
A place to chat and discuss minor things in real time should be useful. #svt on freenode?

**Comment by kylophone** [comment]
Good idea. Not sure how many IRC users we have here, though. I'm open to suggestions from others though.

**Comment by EwoutH** [comment]
Kind of new, but [Matrix](https://matrix.org/blog/home/) looks nice. Modern open-source protocol with lot's of clients, like [Riot](https://about.riot.im/).

**Comment by gnafuthegreat** [comment]
I'd vote for IRC, just because I'm already on there (freenode, specifically) ;-).  Lots of other open source A/V developers are on there (#daala, #xiph, etc.).  On the topic of Matrix, I think you can connect to IRC with a Matrix client (or some kind of tunnel).

**Comment by EwoutH** [comment]
I've initiated `#svt` on [Freenode](https://freenode.net/). Join via [Freenode Webchat](https://webchat.freenode.net/?channels=svt) or use your favorite IRC client.

@hassount Hope to see you and your team there! Suggestions for other communication platforms are still welcome of course.

**Comment by hassount** [comment]
I believe this is done, thank you @EwoutH
