### ISSUE TITLE
Noise estimation [enhacement]

### ISSUE THREAD

**Issue by silverbacknet** [OpenVisualCloud/SVT-AV1#930]
I see that aomenc's noise estimation is left out of SVT. Would it be acceptable to integrate aomenc's existing noise estimation (basically temporal_filter.c/h) for now, or is an alternative planned, or is this a feature that SVT does not wish to include?

**Comment by hassount** [comment]
@silverbacknet 
my understanding is that it's already integrated in EbTemporalFiltering.c @mafonsoN could comment further on this

**Comment by mafonsoN** [comment]
@silverbacknet Noise estimation used for the temporal filtering tool,`estimate_noise()`, is implemented in EbTemporalFiltering.c. Is this what you were referring to?

**Comment by silverbacknet** [comment]
Thank you, I hadn't noticed that, or the -film-grain parameter to use it from the command line. I'm still getting familiar with SVT's codebase. I guess I can start testing it now!
