### ISSUE TITLE
Using SvtAv1EncApp in low memory environments

### ISSUE THREAD

**Issue by grill05** [OpenVisualCloud/SVT-AV1#933]
I understand the minimum memory requirements mentioned in the README, and mostly they are fine. However, I was trying to test av1 encoding on a server which has a very low memory quota (512m), but lots of cpu-quota. 

Is there some flag/parameter I can set in SvtAv1EncApp that will allow using SVT-AV1 in such a low memory environment? For example, I can get ffmpeg+libaom to run by specifying --threads=1/2. That reduces encoding speed somewhat, but allows ffmpeg to run within the memory limit. Is there some similar way to trade-off memory use for encoding speed in SVT-AV1 ?

**Comment by hassount** [comment]
Did you try running with -lp 1

**Comment by grill05** [comment]
> Did you try running with -lp 1

Using -lp 1 works, and seems to use 100% cpu (similar to 1-thread libaom behaviour). Using -lp 2 also seems to use only 100% (not 150-200%) unlike the behaviour of --threads=2

**Comment by hassount** [comment]
I see, it's mainly -lp 2 means that it will target the execution on 2 cores only but it's still limited resources. svt has a different architecture than most codecs (documentation soon coming to the repo hopefully will make things easier to understand). the minimum amount of threads that savt-av1 can start with is 16, but -lp 1 (or anything less than -lp 3) would usually use 1 pipeline of encoding thus you would see only 1 core working. the logic gets set in the functions:

```
EbErrorType load_default_buffer_configuration_settings(
    SequenceControlSet       *scs_ptr){
```
where the setting the number of coding loop pipeline buffers called child pcs is done in this function.
```
scs_ptr->picture_control_set_pool_init_count_child = MAX(MAX(MIN(3, core_count/2), core_count / 6), 1);
```
now it does not scale linearly but changing the min number to 2 might help you with the low cound -lp [2-~5]

```
scs_ptr->picture_control_set_pool_init_count_child = MAX(MAX(MIN(3, core_count/2), core_count / 6), 2);
```

**Comment by grill05** [comment]
@hassount I think your comments sufficiently explain this for now, so I'm closing the issue. Please re-open in the future if there are any major changes
