### ISSUE TITLE
segmentation fault when enc_mode 3 with vbr enabled

### ISSUE THREAD

**Issue by zpdongtencent** [OpenVisualCloud/SVT-AV1#940]
my command line is as following:
./SvtAv1EncApp -i ~/videos/vidyo4_720p_60fps_60f.y4m -enc-mode 3 -rc 1 -b output.ivf

my svt version was v0.8.0 (af16f70)

**Comment by OmranAbdelkafi** [comment]
Fixed at Pull Request #948
