### ISSUE TITLE
High overhead of multi-threading

### ISSUE THREAD

**Issue by mtangtencent** [OpenVisualCloud/SVT-AV1#943]
I did some profiling of SVT-AV1, which turns out to indicate that `WaitForSingleObjectEx` function consumes around 10% of the entire encoding time when preset 8 is used.

**Comment by hassount** [comment]
@mtangtencent 
can you give a little more details about the system / command line you're using ?

**Comment by mtangtencent** [comment]
I was using Win10 with VS 2017, running with preset 8, cqp=36, first 150 frames of BQTerrace_1920x1080_60.yuv, with all other parameters left to default.

**Comment by tianjunwork** [comment]
Using vtune on Xeon 6140, I didn't observe what you see. Laptop is not the primary platform that SVT encoder targets.

**Comment by mtangtencent** [comment]
There is still such issue on my laptop, over 20% of CPU time was used for multi-thread sync function. But as you said, it may be the platform issue.

**Comment by tianjunwork** [comment]
If you run svt-av1 encoder on your laptop(I guess it has less than 6 logical processors?), processors are over subscribed. Processing tasks in different kernels can't get done fast enough causing others to wait/sync. Laptop is not the primary platform to run SVT encoder. Probably it won't be fine tuned.

**Comment by hassount** [comment]
Closing this as there seems to be consensus.
