### ISSUE TITLE
corrupt bitstream generated under mode 6 and several other parameters.

### ISSUE THREAD

**Issue by zpdongtencent** [OpenVisualCloud/SVT-AV1#952]
the output bitstream generated by following parameters can not be decoded normally by ffmpeg.

**SVT commands-->**
./SvtAv1EncApp -i BasketballDrive_1920x1080_50.yuv -w 1920 -h 1080 -fps 50 -enc-mode 6 -obmc -q 24 -n 30 -enable-altrefs 1 -b output.ivf

**note:** you should use the same yuv file as mentioned in my command line.

**_ffmpeg log-->_**
[NULL @ 0x750a240] zero_bit out of range: 1, but must be in [0,0].
[NULL @ 0x750a240] Failed to read unit 1 (type 6).
[NULL @ 0x750a240] Failed to parse temporal unit.

**_SVT version:_**
af16f709522e4800643c6e16eff6f9b3b44e32d4 (HEAD, tag: v0.8.0)

**Comment by hassount** [comment]
@zpdongtencent 
This is now addressed with the head of master at rev 9ce7f5e74c6f3021e87dc00cbbfa51f01a23bd5e
