### ISSUE TITLE
source code for videocodectracker.dev

### ISSUE THREAD

**Issue by grill05** [OpenVisualCloud/SVT-AV1#953]
I've been a fan of videocodectracker.dev for sometime. A while ago, I requested the libaom people to make a similar tracker, and work on that is progressing nicely under [this issue](https://bugs.chromium.org/p/aomedia/issues/detail?id=2560)

However, I usually have a specific use-case in mind (for my personal use), and would prefer to test the encoder performance on that use-case only. If the code used to generate the raw-data files (used to make graphs for videocodectracker) was available, I think I could fork/adapt it for libaom/rav1e as well.

So, is the source code/scripts for generating the raw data files available somewhere. If its not proprietary, could it be open-sourced and uploaded to github? 

thanks

**Comment by mafonsoN** [comment]
Hi @grill05, sorry, I missed this issue! The encode jobs for the videocodectracker currently run on Netflix's internal infrastructure, so some of the code is specific to this environment, therefore, it wouldn't be useful to open source it.

If you want to run your own tests, you can find libaom and svt-av1's command lines in https://videocodectracker.dev/command_lines/svtav1_cli_changelog.html.

The function to compute BD-rate can be found here: https://chromium.googlesource.com/webm/contributor-guide/+/master/scripts/visual_metrics.py

AWCY is also a good reference: https://github.com/xiph/awcy.

Let me know if you have any questions.

**Comment by grill05** [comment]
@mafonsoN thanks. that pretty much answers everything. I'm closing this issue now
