### ISSUE TITLE
Segfault on exit

### ISSUE THREAD

**Issue by ePirat** [OpenVisualCloud/SVT-AV1#959]
Terminating the encoder process with SIGINT causes a segmentation fault:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x28)
    frame #0: 0x00000001002e88d5 libSvtAv1Enc.0.8.0.dylib`eb_fifo_pop_front(fifoPtr=0x00000002cd9e9790, wrapper_ptr=0x00007ffeefbff4f0) at EbSystemResourceManager.c:74:46
   71  	        (fifoPtr->first_ptr == fifoPtr->last_ptr) ? (EbObjectWrapper *)EB_NULL : fifoPtr->last_ptr;
   72  	
   73  	    // Update head of BufferPool
-> 74  	    fifoPtr->first_ptr = fifoPtr->first_ptr->next_ptr;
   75  	
   76  	    return return_error;
   77  	}
Target 0: (SvtAv1EncApp) stopped.
```

**Comment by mazharaIntel** [comment]
Hi @ePirat . Could you provide more information like branch used (I tried master branch and could not reproduce it yet). and the shell command?

**Comment by ePirat** [comment]
Used git master at that point, to be precise ba3dd4480d44d4d772fd0ab942ccc58c56cd3023

Command line used: `SvtAv1EncApp -asm 0 -i fireworks_3840x2160.yuv -n 450 -w 3840 -h 2160 -b ~/out.ivf`

**Comment by mazharaIntel** [comment]
Thanks. Did you use Ctrl +C to invoke SIGINT? And in a Linux environment?

**Comment by ePirat** [comment]
Both Ctrl-C and sending SIGINT using `kill` cause this. I can reproduce both on macOS and Linux.

**Comment by ePirat** [comment]
If needed I can share the yuv file used.

**Comment by mazharaIntel** [comment]
The yuv file would be helpful. Thanks

**Comment by ePirat** [comment]
Can be found here http://streams.videolan.org/misc/fireworks_3840x2160.yuv

**Comment by hassount** [comment]
is this still happening ?

**Comment by ePirat** [comment]
Yes

**Comment by ePirat** [comment]
I tried to reproduce again and can currently no longe reproduce the issue with master, neither with the old commit I used before. That's weird… So let's close this for now, I guess.
