### ISSUE TITLE
Add option to output PSNR values

### ISSUE THREAD

**Issue by EwoutH** [OpenVisualCloud/SVT-AV1#97]
It would be very useful to have the CLI output PSNR values. If I'm correct they are already calculated internally. I would suggest adding the option `-psnr` to output them in the CLI.

**Comment by digitalTrilunaire** [comment]
Any news about this enhancement/missing feature?

**Comment by hassount** [comment]
Working branch: https://github.com/OpenVisualCloud/SVT-AV1/tree/psnr-calc

**Comment by EwoutH** [comment]
@hassount Could you also add a line in the CLI output with the PSNR values?

**Comment by hassount** [comment]
@EwoutH not sure what you mean, so right now when you run the encoder with -stat-report 1 it will output the PSNR values at the end of the encoding in the branch above, are you suggesting something else to be added here ?

**Comment by EwoutH** [comment]
In addition to outputting PSNR data to a stat file, would it also be possible output an extra line in the CLI output with the (average/combined) PSNR? 
```
Average Speed:          50.016 fps
Total Encoding Time:    19194 ms
Total Execution Time:   23573 ms
Average Latency:        3142 ms
Max Latency:            6350 ms
```
Haven't seen you on IRC for a while btw.

**Comment by hassount** [comment]
it is:

```
SUMMARY --------------------------------- Channel 1  --------------------------------
Total Frames            Frame Rate              Byte Count              Bitrate
         501            60.00 fps                  1003219              961.17 kbps

Average QP              Y-PSNR                  U-PSNR                  V-PSNR
      46.54             34.49 dB                   40.70dB              40.30dB


Channel 1
Average Speed:          74.091 fps
Total Encoding Time:    6762 ms
Total Execution Time:   7167 ms
Average Latency:        1282 ms
Max Latency:            1739 ms
Encoder finished
```

**Comment by EwoutH** [comment]
@hassount Is it ready to merge?

**Comment by hassount** [comment]
Yes, I ll work on a PR today.

**Comment by digitalTrilunaire** [comment]
@hassount , how do you compute the PSNR?
I compared the two YUVs (the reference file and the reconstructed file) with ffmpeg and one tool of my company. I can not find the values printed by SVTEncApp either with ffmpeg and with our tool.
Here is my command with a video taken from xiph website:
`SvtAv1EncApp -stat-report 1 -i ../Netflix_Crosswalk_1920x1080p_60Hz_i420.yuv -w 1920 -h 1080 -fps 60 -b Netflix_Crosswalk_1920x1080p_60Hz_i420.ivf -o Netflix_Crosswalk_reconstruct_1920x1080p_60Hz_i420.yuv`

The table below gives you the PSNR with the three tools:

| Tool      | Avg PSNR Y | Avg PSNR U | Avg PSNR V | Overall PSNR Y | Overall PSNR U | Overall PSNR V |
|-----------|------------|------------|------------|----------------|----------------|----------------|
| SVTEncApp | 41.15      | 45.75      | 47.26      | N/A            | N/A            | N/A            |
| FFmpeg    | N/A        | N/A        | N/A        | 40.8539        | 45.5976        | 47.1388        |
| testpsnr  | 41.0075    | 45.6245    | 47.1677    | 40.8539        | 45.5976        | 47.1388        |

Here is the ffmpeg command used:
`ffmpeg -s 1920x1080 -r 60 -i ../Netflix_Crosswalk_1920x1080p_60Hz_i420.yuv -s 1920x1080 -r 60 -i Netflix_Crosswalk_reconstruct_1920x1080p_60Hz_i420.yuv -lavfi psnr -f null -`

**Comment by hassount** [comment]
linking #387
