### ISSUE TITLE
R2R in M4 

### ISSUE THREAD

**Issue by ttrigui** [OpenVisualCloud/SVT-AV1#985]
#790 
Sample command to trigger the R2R:
SvtAv1EncApp.exe -i F:\stream\ParkScene_1920x1080_24.yuv -w 1920 -h 1080 -b ParkScene_1920x1080_24_TRQ_Q43_M4_NOIntra_FIXOFF_120F_0.ivf -enc-mode 4 -rc 0 -q 43 -irefresh-type 2 -intra-period 250 -fps-num 24 -fps-denom 1 -n 120 

R2R is observed in modes 0 to 5.
Disabling over_boundary_block_mode (enabled by default for modes 0 to 5) fixes the problem.
More specifically using 
scs_ptr->sb_geom[sb_index].block_is_inside_md_scan[md_scan_block_index] =
                    ((scs_ptr->sb_geom[sb_index].origin_x + blk_geom->origin_x + blk_geom->bwidth >
                      scs_ptr->seq_header.max_frame_width) ||
                     (scs_ptr->sb_geom[sb_index].origin_y + blk_geom->origin_y + blk_geom->bheight >
                      scs_ptr->seq_header.max_frame_height))
                        ? EB_FALSE
                        : EB_TRUE;
instead of 
                scs_ptr->sb_geom[sb_index].block_is_inside_md_scan[md_scan_block_index] =
                    ((scs_ptr->sb_geom[sb_index].origin_x >= scs_ptr->seq_header.max_frame_width) ||
                     (scs_ptr->sb_geom[sb_index].origin_y >= scs_ptr->seq_header.max_frame_height))
                        ? EB_FALSE
                        : EB_TRUE;
( less blocks inside md scan) fixes the problem.

I was debugging in mode 4 but unfortunately the R2R does not always start at the same frame.
I looked at two bitstreams the affected SB is at (1280, 1024). The 16x16 block at location (1280, 1056) in one bitstream is skipped and not skipped in the other.

**Comment by hassount** [comment]
addressed with #1217
