### ISSUE TITLE
Bitstream Corruption due to GM

### ISSUE THREAD

**Issue by hassount** [OpenVisualCloud/SVT-AV1#986]
@magwyz 
while following some R2R mismatches we found out that this PR (#596) has introduced a bitstream corruption.

-i d:\stream\blue_sky_360p_60f.yuv -w 640 -h 360 -enc-mode 0 -n 600 -b test.ivf

Please note that the corruption happens only at around frame 200-300. even if the clip has 60 frames, it will go around and re-encode the same clip 10 times so the -n 600 is intentional. 
Setting the gm_level to GM_TRAN_ONLY instead of GM_FULL removes the corruption. Would you be able to look into this?

_Originally posted by @hassount in https://github.com/OpenVisualCloud/SVT-AV1/pull/596#issuecomment-579474551_

**Comment by magwyz** [comment]
I can reproduce. I'll try to track the bug.
Thank you for reporting the issue.

**Comment by magwyz** [comment]
This issue should be fixed by #993.
With this PR, I can no longer reproduce the bitstream corruption with the sample and the given command line.
